// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.ZeroFiveFour {
    [STU(0x5CE04BB1)]
    public class STU_5CE04BB1 : STU_866672AD {
        [STUField(0x45A7A69C)]
        public STU_25D5B0B1 m_45A7A69C;

        [STUField(0x2DAD8E99)]
        public STU_25D5B0B1 m_2DAD8E99;

        [STUField(0x0630F9D3)]
        public STU_25D5B0B1 m_0630F9D3;

        [STUField(0x81DBAA1A)]
        public STU_FA600F04 m_81DBAA1A;

        [STUField(0xC1926B2B)]
        public STU_FA600F04 m_C1926B2B;

        [STUField(0xDA4846A5, EmbeddedInstance = true)]
        public STU_25D5B0B1[] m_DA4846A5;

        [STUField(0x1C413B73)]
        public STU_239267EA[] m_1C413B73;

        [STUField(0x54B68306)]
        public float m_54B68306;

        [STUField(0x1D7C8ACE)]
        public float m_1D7C8ACE;

        [STUField(0x4D65010B)]
        public float m_4D65010B;

        [STUField(0x503F626D)]
        public float m_503F626D;
    }
}
