// File auto generated by STUHashTool

namespace STULib.Types.AnimationList.x020 {
    [STU(0x067EF854)]
    public class STU_067EF854 : STU_2F6BD485 {
        [STUField(0xBA66025F)]
        public float m_BA66025F;
    }
}
