// File auto generated by STUHashTool

namespace STULib.Types.AnimationList.x020 {
    [STU(0x3C6A88BF)]
    public class STU_3C6A88BF : STUAnimNode_Base {
        [STUField(0xF0CF068D)]
        public STUAnimBlendDriverParam m_F0CF068D;

        [STUField(0x8D244EC2)]
        public STUAnimBlendDriverParam m_8D244EC2;

        [STUField(0xEEA81ECC)]
        public STU_5ACD7C67 m_EEA81ECC;

        [STUField(0x134EE5BB, EmbeddedInstance = true)]
        public STU_295A9417[] m_134EE5BB;
    }
}
