// File auto generated by STUHashTool

using STULib.Types.AnimationList.x021;

namespace STULib.Types.AnimationList.x020 {
    [STU(0x597F8A0B)]
    public class STU_597F8A0B : STU_2F6BD485 {
        [STUField(0x37429C94)]
        public STU_F731C873 m_37429C94;

        [STUField(0x888FA52F)]
        public STU_ABD8FE73 m_888FA52F;

        [STUField(0xA5443C92, EmbeddedInstance = true)]
        public STU_5BF8DA7A m_A5443C92;
    }
}
