// File auto generated by STUHashTool

namespace STULib.Types.STUUnlock {
    [STU(0x136D45F1)]
    // ReSharper disable once InconsistentNaming
    public class CompetitiveCurrencyReward : Cosmetic {
        [STUField(0x760BF18E)]
        public uint Amount;
    }
}
