// File auto generated by STUHashTool

namespace STULib.Types.STUUnlock {
    [STU(0xC294A43B)]
    // ReSharper disable once InconsistentNaming
    public class STU_C294A43B : Cosmetic {  // some lootbox thing
        [STUField(0x7AB4E3F8)]
        public Enums.STUEnumEventID Event;

        [STUField(0xD8A49A4D)]
        public uint Unknown;
    }
}
