// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x1B4EBEEB)]
    public class STU_1B4EBEEB : STU_C7C085F6 {
        [STUField(0xF830FBBD)]
        public STUGUID m_F830FBBD;  // STUAnimation

        [STUField(0xED704301)]
        public STUGUID m_ED704301;  // STUAnimation

        [STUField(0x9514082C)]
        public STUGUID m_9514082C;  // STUAnimation

        [STUField(0x288ABC53)]
        public STUGUID m_288ABC53;  // STUAnimation

        [STUField(0x5EF0A31B)]
        public STUGUID m_5EF0A31B;  // STUAnimation

        [STUField(0x73C26D81)]
        public STUGUID m_73C26D81;  // STUAnimation

        [STUField(0xC9AF9A44)]
        public STUGUID m_C9AF9A44;  // STUAnimation

        [STUField(0xD25817CF)]
        public STUGUID m_D25817CF;  // STUAnimation

        [STUField(0x7237A98F)]
        public STUGUID m_7237A98F;  // STU_D2929F20

        [STUField(0xA9330380)]
        public float m_A9330380;

        [STUField(0x04EC121C)]
        public float m_04EC121C;

        [STUField(0xD520EF14)]
        public float m_D520EF14;

        [STUField(0x7881B69D)]
        public float m_7881B69D;

        [STUField(0x5A91C8F6)]
        public float m_5A91C8F6;

        [STUField(0xA5115B4A)]
        public float m_A5115B4A;

        [STUField(0xEB39F65D)]
        public float m_EB39F65D;

        [STUField(0xEA1AB40E)]
        public float m_EA1AB40E;
    }
}
