// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xA90795E2)]
    public class STU_A90795E2 : STU_E896B267 {
        [STUField(0x6CE7A900, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_6CE7A900;
    }
}
