// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x8BF80D88)]
    public class STU_8BF80D88 : STU_8F4AD712 {
        [STUField(0x886C9E6E, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_886C9E6E;

        [STUField(0x7F1035A6, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_7F1035A6;
    }
}
