// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xF0E34581)]
    public class STU_F0E34581 : STUInstance {
        [STUField(0xB48F1D22, "m_name")]
        public string Name;

        [STUField(0x888BCD8B)]
        public STUGUID m_888BCD8B;  // STU_7A0B33DA

        [STUField(0xEDF0511C)]
        public ulong m_EDF0511C;

        [STUField(0xFF592924)]
        public ulong m_FF592924;

        [STUField(0xAF9D3A0C)]
        public STUQuaternion m_AF9D3A0C;

        [STUField(0x7DC1550F)]
        public STUVec3 m_7DC1550F;
    }
}
