// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x2F4E2E3F)]
    public class STU_2F4E2E3F : STUStatescriptState {
        [STUField(0xB7A3CF78, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_B7A3CF78;

        [STUField(0x48A8CDEC, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_48A8CDEC;

        [STUField(0xA70DB860, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUStatescriptOutputPlug m_A70DB860;
    }
}
