// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xB61E6681)]
    public class STU_B61E6681 : STU_6243C374 {
        [STUField(0x203D6B00, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_203D6B00;

        [STUField(0x9CDDC24D, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_9CDDC24D;
    }
}
