// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x6154B909)]
    public class STU_6154B909 : STU_F7B7BBA0 {
        [STUField(0x62F6795F, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_62F6795F;

        [STUField(0x4999D53A, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_4999D53A;

        [STUField(0x2A7E6E17, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_2A7E6E17;
    }
}
