// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x9AB8CF41)]
    public class STU_9AB8CF41 : STU_7639CFC1 {
        [STUField(0x33B0B2B6, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_33B0B2B6;
    }
}
