// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x737C5C41)]
    public class STU_737C5C41 : STULib.Types.STUEntityComponent2 {
    }
}
