// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x9F9C100B)]
    public class STU_9F9C100B : STUInstance {
        [STUField(0xE086BB06)]
        public STUGUID m_E086BB06;  // STU_9CADF2EC

        [STUField(0x17C34C1B, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_17C34C1B;
    }
}
