// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x6FEE499E)]
    public class STU_6FEE499E : STU_DD856C32 {
        [STUField(0x93CDFD2F)]
        public STULib.Types.Dump.Enums.STUEnum_2637CD6D m_93CDFD2F;
    }
}
