// File auto generated by STUHashTool

using STULib.Types.Dump.Enums;
using STULib.Types.Generic;

namespace STULib.Types.Dump {
    [STU(0x38F4E107)]
    public class STU_38F4E107 : Common.STUInstance {
        [STUField(0xB4FF0E2F)]
        public Common.STUGUID m_B4FF0E2F;  // STU_865FBB7E

        [STUField(0xDB084D42)]
        public STU_65436ABC[] m_DB084D42;

        [STUField(0x28E3DD84)]
        public STUEnum_613C4AA2 m_28E3DD84;
    }
}

