// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x3403B7AC)]
    public class STU_3403B7AC : STU_A46203AB {
        [STUField(0x27D324B3)]
        public ushort m_27D324B3;

        [STUField(0xBD631144)]
        public ushort m_BD631144;

        [STUField(0x43505DC5)]
        public ushort m_43505DC5;

        [STUField(0x20DC598F)]
        public byte m_20DC598F;
    }
}
