// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x7D59D23A)]
    public class STU_7D59D23A : STU_0C8ADF02 {
        [STUField(0x3CD6DC1E, "m_texture")]
        public STUGUID Texture;  // STUTexture

        [STUField(0x6FF59B86, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_95ECA8A6 m_6FF59B86;

        [STUField(0x25517A47, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_95ECA8A6 m_25517A47;

        [STUField(0x6FD22B0C)]
        public byte m_6FD22B0C;
    }
}
