// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x0FAD550D)]
    public class STU_0FAD550D : STUStatescriptState {
        [STUField(0x41F2FA6C, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_41F2FA6C;
    }
}
