// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x5E1EE180)]
    public class STU_5E1EE180 : STULib.Types.STU_866672AD {
        [STUField(0x7355FD0D)]
        public double m_7355FD0D;

        [STUField(0x46B5D9C3)]
        public double m_46B5D9C3;

        [STUField(0x3439D354)]
        public double m_3439D354;

        [STUField(0xB8DC1D02)]
        public double m_B8DC1D02;

        [STUField(0xCD69451A)]
        public double m_CD69451A;

        [STUField(0xFB994CAC)]
        public int m_FB994CAC;
    }
}
