// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x319619ED)]
    public class STU_319619ED : STULib.Types.STUConfigVar {
    }
}
