// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x016A1DF7)]
    public class STU_016A1DF7 : STU_C7C085F6 {
        [STUField(0x172CAE5E)]
        public STUGUID m_172CAE5E;  // STUAnimation

        [STUField(0x5620DA50)]
        public STULib.Types.Dump.STU_B0D9AEDF m_5620DA50;

        [STUField(0xEC42051A)]
        public STULib.Types.Dump.STU_57C43142 m_EC42051A;

        [STUField(0xF0E4656D)]
        public STULib.Types.Dump.STU_19354E9E m_F0E4656D;

        [STUField(0xAD7B135E)]
        public float m_AD7B135E;

        [STUField(0xABF34EEF)]
        public float m_ABF34EEF;

        [STUField(0xE8502460)]
        public float m_E8502460;

        [STUField(0x83CE3EB5)]
        public float m_83CE3EB5;
    }
}
