// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x60087DC7)]
    public class STU_60087DC7 : STU_7FA0F929 {
        [STUField(0x07DD813E, "m_value")]
        public string Value;
    }
}
