// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xBA4C2296)]
    public class STU_BA4C2296 : STUStatescriptState {
        [STUField(0x0A84537A)]
        public STUGUID m_0A84537A;  // STULib.Types.STUUISoundList

        [STUField(0xDC71317C, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_DC71317C;

        [STUField(0x04B2C103, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_04B2C103;

        [STUField(0x4A5CA514, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_4A5CA514;

        [STUField(0x6EFD110C, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_6EFD110C;

        [STUField(0xD80AEDB1, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_D80AEDB1;

        [STUField(0x3E3DFE0F, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_3E3DFE0F;

        [STUField(0x66D29548, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_66D29548;

        [STUField(0x86CE02DE)]
        public byte m_86CE02DE;
    }
}
