// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x3D5F853C)]
    public class STU_3D5F853C : STU_1482DDBB {
        [STUField(0xA83C2C26, "m_entity", EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar Entity;
    }
}
