// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xF3104738)]
    public class STU_F3104738 : STUStatescriptState {
        [STUField(0x68666D2D)]
        public STULib.Types.Dump.STU_543CF5E7[] m_68666D2D;

        [STUField(0x85FF200D)]
        public STULib.Types.Dump.STU_83587DEE[] m_85FF200D;

        [STUField(0xA58E69E4, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_A58E69E4;

        [STUField(0xB223A14E, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_B223A14E;

        [STUField(0x51EFC23E, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_51EFC23E;
    }
}
