// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x26A8F1EE)]
    public class STU_26A8F1EE : STU_DD856C32 {
        [STUField(0x37AB13D3, "m_hero", EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar Hero;

        [STUField(0xF24E4110, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_F24E4110;

        [STUField(0xF5087894, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_F5087894;
    }
}
