// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x4C96470A)]
    public class STU_4C96470A : STUStatescriptState {
        [STUField(0xDC05B2EE, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_DC05B2EE;

        [STUField(0xB3094B0E, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_B3094B0E;

        [STUField(0xB42B2BEB, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_B42B2BEB;

        [STUField(0x33C8E790, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_33C8E790;

        [STUField(0x60B6AF94, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_60B6AF94;

        [STUField(0x15F880A4, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_15F880A4;

        [STUField(0x00A23E4B, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_00A23E4B;

        [STUField(0x6386E7B4, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_6386E7B4;

        [STUField(0x1B05EA98, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_1B05EA98;

        [STUField(0x2ADABA5F, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_2ADABA5F;

        [STUField(0x3656A811, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_3656A811;

        [STUField(0xB221D18D, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_B221D18D;

        [STUField(0x6E8CA10B, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_6E8CA10B;

        [STUField(0x7404C882, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_8BB02FF3 m_7404C882;

        [STUField(0x6647ED22, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_A1AAB8C4 m_6647ED22;

        [STUField(0xF6955E81, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUStatescriptOutputPlug m_F6955E81;

        [STUField(0x425337C6, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUStatescriptOutputPlug m_425337C6;

        [STUField(0x3E0AE839, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_3E0AE839;

        [STUField(0xE21062B4, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_E21062B4;

        [STUField(0x30710B76, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_30710B76;

        [STUField(0x2339572B, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_2339572B;

        [STUField(0x1549F0F9, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_1549F0F9;

        [STUField(0x2FECD1E3, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_2FECD1E3;
    }
}
