// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xA9C41499)]
    public class STU_A9C41499 : STU_A3C7077A {
        [STUField(0xC3E03C7F)]
        public STUGUID m_C3E03C7F;  // STUTexture

        [STUField(0xB999DDE2)]
        public STUGUID m_B999DDE2;  // STU_58B3D0D0

        [STUField(0x4ED21288)]
        public float m_4ED21288;
    }
}
