// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x2B1A5E8C)]
    public class STU_2B1A5E8C : STULib.Types.STUEntityComponent {
        [STUField(0xA18274A3)]
        public STUGUID m_A18274A3;

        [STUField(0x6CB564CC)]
        public STUGUID m_6CB564CC;

        [STUField(0x2170A015)]
        public STUGUID m_2170A015;

        [STUField(0x306ABA15)]
        public STUGUID m_306ABA15;

        [STUField(0xAED73588)]
        public STUGUID m_AED73588;

        [STUField(0x707DF34C)]
        public STUGUID m_707DF34C;

        [STUField(0xFE1DDCEB)]
        public STUGUID m_FE1DDCEB;

        [STUField(0xBF7914D4)]
        public STUGUID m_BF7914D4;

        [STUField(0xBAB9824B)]
        public STUGUID m_BAB9824B;

        [STUField(0x93A2D5E5)]
        public STUGUID m_93A2D5E5;

        [STUField(0x0A84537A)]
        public STUGUID m_0A84537A;  // STULib.Types.STUUISoundList

        [STUField(0xD02E414F)]
        public STUGUID m_D02E414F;  // STULib.Types.STUUISoundList

        [STUField(0x930792A5, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_C6C0F8D7 m_930792A5;

        [STUField(0x3D2FFAAA)]
        public float m_3D2FFAAA;

        [STUField(0xA0D912A2)]
        public float m_A0D912A2;

        [STUField(0x2CE38384)]
        public float m_2CE38384;

        [STUField(0xC7B3A1FD)]
        public float m_C7B3A1FD;

        [STUField(0x1901FD3D)]
        public float m_1901FD3D;

        [STUField(0x1913CA4C)]
        public float m_1913CA4C;

        [STUField(0x8BEBC26A)]
        public float m_8BEBC26A;

        [STUField(0xCC568D8C)]
        public float m_CC568D8C;

        [STUField(0xE3758E81)]
        public float m_E3758E81;

        [STUField(0x111DE594)]
        public float m_111DE594;

        [STUField(0x86002240)]
        public byte m_86002240;

        [STUField(0x8390D843)]
        public byte m_8390D843;

        [STUField(0x601A083C)]
        public byte m_601A083C;

        [STUField(0x8192DFAC)]
        public byte m_8192DFAC;

        [STUField(0xBDF902EE)]
        public byte m_BDF902EE;

        [STUField(0xD21BB78F)]
        public byte m_D21BB78F;

        [STUField(0xB1AC509D)]
        public byte m_B1AC509D;

        [STUField(0xE826E9FC)]
        public byte m_E826E9FC;

        [STUField(0x9582A2FE)]
        public byte m_9582A2FE;

        [STUField(0x56BDFB00)]
        public byte m_56BDFB00;

        [STUField(0x32BA39E1)]
        public byte m_32BA39E1;
    }
}
