// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x9A40D4BB)]
    public class STU_9A40D4BB : STUInstance {
        [STUField(0x029AF534, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_9A40D4BB[] m_029AF534;

        [STUField(0x37EE887D, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_37EE887D;

        [STUField(0x012FEE23, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_012FEE23;
    }
}
