// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xF1306D2B)]
    public class STU_F1306D2B : STU_6B892D91 {
        [STUField(0x5180E750)]
        public ulong m_5180E750;
    }
}
