// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xA8EFC6F0)]
    public class STU_A8EFC6F0 : STULib.Types.STUGraphPlug {
    }
}
