// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x4AFA17B1)]
    public class STU_4AFA17B1 : STU_DD856C32 {
        [STUField(0xFDD34C25, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_F23DE9D7[] m_FDD34C25;

        [STUField(0x9AAAE373, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_9AAAE373;

        [STUField(0x262AE982, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_262AE982;

        [STUField(0xCD38D5DB, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_F23DE9D7 m_CD38D5DB;

        [STUField(0xF0F0720B)]
        public STULib.Types.Dump.Enums.STUEnum_F94C0730 m_F0F0720B;
    }
}
