// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x32B86547)]
    public class STU_32B86547 : STU_79862BCB {
        [STUField(0x00A48632, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_00A48632;
    }
}
