// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xFA258ECC)]
    public class STU_FA258ECC : STU_5DB5B1C9 {
        [STUField(0xC41767A5)]
        public float m_C41767A5;

        [STUField(0x4D530E8A)]
        public float m_4D530E8A;
    }
}
