// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x01AA07B0)]
    public class STU_01AA07B0 : STUInstance {
        [STUField(0x767792E4)]
        public STUUUID m_767792E4;

        [STUField(0xBB16810A, "m_priority")]
        public short Priority;
    }
}
