// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x0C8ADF02)]
    public class STU_0C8ADF02 : STU_ECC16B71 {
        [STUField(0x845D6D97, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_00ABC9FF m_845D6D97;

        [STUField(0x6BDE66BE)]
        public float m_6BDE66BE;

        [STUField(0xE2727329)]
        public byte m_E2727329;

        [STUField(0x75A18FC8)]
        public byte m_75A18FC8;
    }
}
