// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xE3CA5895)]
    public class STU_E3CA5895 : STU_4FF1DFFE {
        [STUField(0xB48F1D22, "m_name")]
        public string Name;

        [STUField(0x5056D4DE, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_3CD5636B m_5056D4DE;
    }
}
