// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xC3AC054C)]
    public class STU_C3AC054C : STU_6F37773E {
        [STUField(0x374D122D)]
        public STUGUID m_374D122D;  // STU_35AA91CE
    }
}
