// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xB113D362)]
    public class STU_B113D362 : STU_1413B6A1 {
        [STUField(0x7C831A8D, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_7C831A8D;

        [STUField(0xC0EDD7EC, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_C0EDD7EC;
    }
}
