// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x757C8356)]
    public class STU_757C8356 : STU_54FD3952 {
        [STUField(0xA83C2C26, "m_entity", EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar Entity;
    }
}
