// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x0E918813)]
    public class STU_0E918813 : STU_DD856C32 {
        [STUField(0x4E21F188, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUStatescriptOutputPlug m_4E21F188;

        [STUField(0x30B0FC09, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUStatescriptOutputPlug m_30B0FC09;
    }
}
