// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x9932D728)]
    public class STU_9932D728 : STUStatescriptState {
        [STUField(0x3AA1ACFD, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_3AA1ACFD;

        [STUField(0x2FB7B93C, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_2FB7B93C;

        [STUField(0x78FE8486, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_78FE8486;

        [STUField(0xF745334E, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_F745334E;

        [STUField(0x3BC31C57, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_3BC31C57;

        [STUField(0x53D01033, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_53D01033;

        [STUField(0xFB9FD621, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_FB9FD621;

        [STUField(0xD4E290F3, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_D4E290F3;

        [STUField(0x0B057C92, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_0B057C92;

        [STUField(0x2FE19ED6, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_2FE19ED6;

        [STUField(0x89C93A57, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_89C93A57;

        [STUField(0x270D9C32)]
        public byte m_270D9C32;

        [STUField(0x96F6561D)]
        public byte m_96F6561D;

        [STUField(0x5740D133)]
        public byte m_5740D133;

        [STUField(0x6A3C1510)]
        public byte m_6A3C1510;
    }
}
