// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xD184C474)]
    public class STU_D184C474 : STUInstance {
        [STUField(0xC04B2B37)]
        public string m_C04B2B37;

        [STUField(0x1DFED57A)]
        public uint m_1DFED57A;
    }
}
