// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x23A661BD)]
    public class STU_23A661BD : STUStatescriptState {
        [STUField(0x5A6D4FBD, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_5A6D4FBD;

        [STUField(0xF92402E9, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_F92402E9;

        [STUField(0xA83C2C26, "m_entity", EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_E7E3DD60 Entity;
    }
}
