// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x9F9A2B5C)]
    public class STU_9F9A2B5C : STUInstance {
        [STUField(0xF57ED0C8)]
        public long m_F57ED0C8;

        [STUField(0x3EE5B890)]
        public long m_3EE5B890;

        [STUField(0x6FC4EE35)]
        public int m_6FC4EE35;

        [STUField(0x80DFC3DA)]
        public byte m_80DFC3DA;
    }
}
