// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x4A7AC5BF)]
    public class STU_4A7AC5BF : STUInstance {
        [STUField(0xEE3055BD, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_EE3055BD;
    }
}
