// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xE91FC25A)]
    public class STU_E91FC25A : STU_4B6F9A4C {
        [STUField(0x887B7916)]
        public STULib.Types.Dump.STU_E095AE40 m_887B7916;

        [STUField(0xD697B92C)]
        public STULib.Types.Dump.STU_D11C922F m_D697B92C;

        [STUField(0x89F953D0)]
        public STULib.Types.Dump.STU_0B5C5FB3 m_89F953D0;
    }
}
