// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x3BC72DE1)]
    public class STU_3BC72DE1 : STUStatescriptState {
        [STUField(0x0468C6D4, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_0468C6D4;

        [STUField(0x176B72EC, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_176B72EC;
    }
}
