// File auto generated by STUHashTool

using STULib.Types.Generic;

namespace STULib.Types.Dump {
    [STU(0xF3D263C3)]
    public class STU_F3D263C3 : Common.STUInstance {
        [STUField(0x27AF7472)]
        public STU_ABD8FE73 m_27AF7472;

        [STUField(0xEADB4E1E)]
        public STU_586361C8[] m_EADB4E1E;
    }
}
