// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x0F4B5C2F)]
    public class STU_0F4B5C2F : STU_F0D215C7 {
        [STUField(0x4A0D3E2E)]
        public int m_4A0D3E2E;
    }
}
