// File auto generated by STUHashTool

namespace STULib.Types.Dump {
    [STU(0xCB30C7C3)]
    public class STU_CB30C7C3 : STU_B90213F3 {
        [STUField(0x7FCF7550)]
        public STU_ABD8FE73 m_7FCF7550;

        [STUField(0xA5B4A28E)]
        public STU_ABD8FE73 m_A5B4A28E;

        [STUField(0xB03BDF56)]
        public STU_ABD8FE73 m_B03BDF56;
    }
}

