// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xBE34EED4)]
    public class STU_BE34EED4 : STU_81C5DE19 {
        [STUField(0xF891229F)]
        public STULib.Types.Dump.STU_E0E0A00F m_F891229F;
    }
}
