// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xBC48636B)]
    public class STU_BC48636B : STUInstance {
        [STUField(0x335CC942)]
        public STULib.Types.Dump.STU_D3350D13 m_335CC942;
    }
}
