// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x3D376BBA)]
    public class STU_3D376BBA : STU_81C5DE19 {
        [STUField(0xF891229F)]
        public STULib.Types.Dump.STU_C47A99C1 m_F891229F;
    }
}
