// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xC55609C4)]
    public class STU_C55609C4 : STU_79F9EE42 {
        [STUField(0x82804596)]
        public byte m_82804596;
    }
}
