// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xC168636D)]
    public class STU_C168636D : STU_1C2FB897 {
        [STUField(0x717EAFE7, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_717EAFE7;

        [STUField(0x34A1CCB7, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_34A1CCB7;

        [STUField(0x6716919E, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_6716919E;
    }
}
