// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x3267AB13)]
    public class STU_3267AB13 : STU_81C5DE19 {
        [STUField(0xF891229F)]
        public STULib.Types.Dump.STU_6F42B9D1 m_F891229F;

        [STUField(0x4E9DD4C3, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_A8EFC6F0 m_4E9DD4C3;

        [STUField(0x4B67E58F, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_A8EFC6F0 m_4B67E58F;

        [STUField(0x0F148AD3, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_A8EFC6F0 m_0F148AD3;

        [STUField(0x83B15798, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_A8EFC6F0 m_83B15798;
    }
}
