// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x7AD4FB0C)]
    public class STU_7AD4FB0C : STU_C7C085F6 {
        [STUField(0x767FD1ED)]
        public float m_767FD1ED;

        [STUField(0x1B46194B)]
        public float m_1B46194B;

        [STUField(0x14E67C73)]
        public float m_14E67C73;

        [STUField(0xD32A2089)]
        public float m_D32A2089;
    }
}
