// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x929759C6)]
    public class STU_929759C6 : STU_05BDD390 {
        [STUField(0xFC1BFB66)]
        public STULib.Types.Dump.STU_F4F1F144 m_FC1BFB66;

        [STUField(0x58C6C40E)]
        public STULib.Types.Dump.STU_F4F1F144 m_58C6C40E;
    }
}
