// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x5E493D8B)]
    public class STU_5E493D8B : STUInstance {
        [STUField(0x96D9482C)]
        public STUGUID[] m_96D9482C;  // STULib.Types.STUEntityDefinition

        [STUField(0x925E7392)]
        public float m_925E7392;
    }
}
