// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x4EFF450F)]
    public class STU_4EFF450F : STUInstance {
        [STUField(0xB48F1D22, "m_name")]
        public string Name;

        [STUField(0x888BCD8B)]
        public STUGUID m_888BCD8B;  // STU_7A0B33DA

        [STUField(0xEDF0511C)]
        public ulong m_EDF0511C;
    }
}
