// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x269A37F8)]
    public class STU_269A37F8 : STU_A2B9762B {
        [STUField(0xF8D4FCA9)]
        public STUVec3 m_F8D4FCA9;
    }
}
