// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xE601DE30)]
    public class STU_E601DE30 : STU_C7C085F6 {
        [STUField(0x836924DF)]
        public STUGUID m_836924DF;  // STUAnimation

        [STUField(0x2B6D89C1)]
        public STUGUID m_2B6D89C1;  // STUAnimation

        [STUField(0x1B4288DF)]
        public STUGUID m_1B4288DF;  // STUAnimation

        [STUField(0x2D85A9B2)]
        public STUGUID m_2D85A9B2;  // STUAnimation

        [STUField(0xCCDA23EA)]
        public STUGUID m_CCDA23EA;  // STUAnimation

        [STUField(0x5D8DBAF3)]
        public STUVec2 m_5D8DBAF3;

        [STUField(0x183BC0E3)]
        public float m_183BC0E3;

        [STUField(0x609AD386)]
        public float m_609AD386;

        [STUField(0x2DBE921D)]
        public float m_2DBE921D;

        [STUField(0x27158126)]
        public float m_27158126;

        [STUField(0xC5E663C0)]
        public float m_C5E663C0;

        [STUField(0x2C95CD87)]
        public float m_2C95CD87;

        [STUField(0x42AD1319)]
        public float m_42AD1319;

        [STUField(0x497ADC45)]
        public float m_497ADC45;

        [STUField(0x796BAC2C)]
        public float m_796BAC2C;

        [STUField(0x63BA70FA)]
        public float m_63BA70FA;

        [STUField(0x35D0EDFE)]
        public float m_35D0EDFE;

        [STUField(0xDD794862)]
        public float m_DD794862;

        [STUField(0x14E67C73)]
        public float m_14E67C73;

        [STUField(0xD32A2089)]
        public float m_D32A2089;

        [STUField(0x7D22FF82)]
        public float m_7D22FF82;

        [STUField(0x1F5C172D)]
        public float m_1F5C172D;

        [STUField(0xB4C36FFC)]
        public byte m_B4C36FFC;
    }
}
