// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x7A7F2732)]
    public class STU_7A7F2732 : STUStatescriptState {
        [STUField(0x87C575BB)]
        public STULib.Types.Dump.STU_D3350D13 m_87C575BB;

        [STUField(0x470B318E, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_34C0F0A2[] m_470B318E;

        [STUField(0xDF6FB9C5, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_ABE9D44B[] m_DF6FB9C5;

        [STUField(0x45216F79, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_4586592B m_45216F79;

        [STUField(0x45017CEA, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_45017CEA;

        [STUField(0xE5265589, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_8BB02FF3 m_E5265589;

        [STUField(0x4BA4C058)]
        public STULib.Types.Dump.Enums.STUEnum_CEBBB217 m_4BA4C058;
    }
}
