// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x86882FB6)]
    public class STU_86882FB6 : STUStatescriptOutputPlug {
    }
}
