// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xF7262B36)]
    public class STU_F7262B36 : STU_54FD3952 {
        [STUField(0x801B298F, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_801B298F;
    }
}
