// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x61DACB9B)]
    public class STU_61DACB9B : STU_A3C7077A {
        [STUField(0xB999DDE2)]
        public STUGUID m_B999DDE2;  // STU_58B3D0D0

        [STUField(0xB14EAA65)]
        public float m_B14EAA65;
    }
}
