// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x04772F44)]
    public class STU_04772F44 : STU_DD856C32 {
        [STUField(0x5589C1B3, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_5589C1B3;

        [STUField(0xE1CE3497, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_E1CE3497;

        [STUField(0x886B1AA1, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_886B1AA1;

        [STUField(0xE1395228, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_E1395228;

        [STUField(0x077A7D96, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_077A7D96;
    }
}
