// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xCE1A62F7)]
    public class STU_CE1A62F7 : STUStatescriptState {
        [STUField(0xB22239A3, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_B22239A3;

        [STUField(0x05F43762, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_05F43762;

        [STUField(0x3B7D8043, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_3B7D8043;
    }
}
