// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xE3E39626)]
    public class STU_E3E39626 : STUInstance {
        [STUField(0xC6C60F7D)]
        public float m_C6C60F7D;

        [STUField(0x7C5B44F1)]
        public float m_7C5B44F1;

        [STUField(0xC8A1AFE2)]
        public float m_C8A1AFE2;

        [STUField(0x0DA2B382)]
        public float m_0DA2B382;

        [STUField(0x85AB6A94)]
        public float m_85AB6A94;

        [STUField(0x5D1307EA)]
        public float m_5D1307EA;
    }
}
