// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x74B41EA0)]
    public class STU_74B41EA0 : STU_DD856C32 {
        [STUField(0xEDB2BD2A, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_EDB2BD2A;

        [STUField(0x8ABF9743, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_8ABF9743;
    }
}
