// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x904BFCEC)]
    public class STU_904BFCEC : STUStatescriptOutputPlug {
        [STUField(0xFF3DAF1E)]
        public int[] m_FF3DAF1E;
    }
}
