// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x3388617A)]
    public class STU_3388617A : STU_1482DDBB {
        [STUField(0xF3E612FD, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_F3E612FD;
    }
}
