// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x4326B1D9)]
    public class STU_4326B1D9 : STUStatescriptState {
        [STUField(0xFC1AFF3E, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_FC1AFF3E;

        [STUField(0xF5087894, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_F5087894;

        [STUField(0x4C167404, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_4C167404;

        [STUField(0xD963F238, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_D963F238;

        [STUField(0x9613163D, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_904BFCEC m_9613163D;
    }
}
