// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xFCA3FB42)]
    public class STU_FCA3FB42 : STULib.Types.STU_866672AD {
        [STUField(0xB55BAFC3)]
        public STUGUID m_B55BAFC3;

        [STUField(0x462BE053)]
        public STUGUID m_462BE053;

        [STUField(0x03632F3D)]
        public STUGUID m_03632F3D;
    }
}
