// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xE6A9213B)]
    public class STU_E6A9213B : STU_1413B6A1 {
        [STUField(0x11B47C68, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_11B47C68;
    }
}
