// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x6393F390)]
    public class STU_6393F390 : STU_DA1C9A21 {
        [STUField(0x8B47E263)]
        public STULib.Types.Dump.STU_1C5C04E0 m_8B47E263;
    }
}
