// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x143DAF0C)]
    public class STU_143DAF0C : STULib.Types.STUGraphPlug {
    }
}
