// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xE25468B3)]
    public class STU_E25468B3 : STU_3660CDED {
        [STUField(0x3FAFF222)]
        public STULib.Types.Dump.Enums.STUEnum_ADF0A7EE m_3FAFF222;
    }
}
