// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x520E0AB7)]
    public class STU_520E0AB7 : STU_F029B472 {
        [STUField(0x334938EC, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_0CF6650E m_334938EC;
    }
}
