// File auto generated by STUHashTool

using STULib.Types.Generic;

namespace STULib.Types.Dump {
    [STU(0x8880FCB0)]
    public class STU_8880FCB0 : Common.STUInstance {
        [STUField(0x5A7D86C7)]
        public STU_6B3A03D7 m_5A7D86C7;

        [STUField(0x80B01FC2)]
        public STU_2854069F m_80B01FC2;

        [STUField(0xAE42D53E)]
        public STU_7CD6F719 m_AE42D53E; // Always null ??

        [STUField(0xD74D5F6F)]
        public STU_176E7ACB m_D74D5F6F;

        [STUField(0x939ABB2C)]
        public Common.STUGUID Material;

        [STUField(0x94C9FBD7)]
        public Common.STUColorRGBA Color;
    }
}

