// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x5A648624)]
    public class STU_5A648624 : STU_1482DDBB {
        [STUField(0x0C83DEFC, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_0C83DEFC;
    }
}
