// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x6C945453)]
    public class STU_6C945453 : STUStatescriptState {
        [STUField(0x4E87690F, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_4E87690F;

        [STUField(0x2334A7D6, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_2334A7D6;

        [STUField(0x41F6368D, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_41F6368D;

        [STUField(0x9613163D, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_904BFCEC m_9613163D;
    }
}
