// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xE526E527)]
    public class STU_E526E527 : STU_7A7F2732 {
        [STUField(0xE0EAC161, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_E0EAC161;

        [STUField(0x5E1E47C5, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUStatescriptOutputPlug m_5E1E47C5;

        [STUField(0xDA239D27, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUStatescriptOutputPlug m_DA239D27;

        [STUField(0x70CCDE78, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUStatescriptOutputPlug m_70CCDE78;
    }
}
