// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xE4C1C275)]
    public class STU_E4C1C275 : STU_05BDD390 {
        [STUField(0x9884BDEE)]
        public uint m_9884BDEE;
    }
}
