// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xE3E48766)]
    public class STU_E3E48766 : STU_79F9EE42 {
        [STUField(0x0EE72694)]
        public STUGUID m_0EE72694;  // STUTexture

        [STUField(0x79E5C961)]
        public string m_79E5C961;
    }
}
