// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x264F6EBC)]
    public class STU_264F6EBC : STU_C7C085F6 {
        [STUField(0x172CAE5E)]
        public STUGUID m_172CAE5E;  // STUAnimation

        [STUField(0x95BD9624)]
        public STUGUID m_95BD9624;  // STU_D2929F20

        [STUField(0xEC42051A)]
        public STULib.Types.Dump.STU_57C43142 m_EC42051A;

        [STUField(0xF0E4656D)]
        public STULib.Types.Dump.STU_19354E9E m_F0E4656D;

        [STUField(0xE8502460)]
        public float m_E8502460;

        [STUField(0x83CE3EB5)]
        public float m_83CE3EB5;

        [STUField(0x37EE887D)]
        public byte m_37EE887D;

        [STUField(0x2FBD6CBA)]
        public byte m_2FBD6CBA;
    }
}
