// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xD3650B28)]
    public class STU_D3650B28 : STU_22DB169C {
        [STUField(0xB5C0F593)]
        public STUGUID m_B5C0F593;  // STU_2376C502
    }
}
