// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xC38B92B4)]
    public class STU_C38B92B4 : STUStatescriptState {
        [STUField(0xEF3C5C73)]
        public STULib.Types.Dump.STU_D2EA359E[] m_EF3C5C73;

        [STUField(0x19899EAC)]
        public STULib.Types.Dump.STU_D2EA359E[] m_19899EAC;

        [STUField(0x65FB422B)]
        public STULib.Types.Dump.STU_D2EA359E[] m_65FB422B;

        [STUField(0x47FDAB68)]
        public STULib.Types.Dump.STU_D2EA359E[] m_47FDAB68;

        [STUField(0xAD46D658)]
        public STULib.Types.Dump.STU_D2EA359E[] m_AD46D658;

        [STUField(0x34F90311, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_34F90311;

        [STUField(0x835F4CE6, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_835F4CE6;

        [STUField(0x246438AD, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_246438AD;

        [STUField(0xA368407D, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_A368407D;

        [STUField(0xA5F1A77B, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_A5F1A77B;

        [STUField(0x8CBD15DA, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_8CBD15DA;

        [STUField(0xC68C19C4, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_C68C19C4;

        [STUField(0x1D9BA88D, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_1D9BA88D;

        [STUField(0xFF11BD3F, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_FF11BD3F;

        [STUField(0xF6BF1466, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_F6BF1466;

        [STUField(0xBBC9EFFF, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_BBC9EFFF;

        [STUField(0xF495731F, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_F495731F;

        [STUField(0x150F0D92, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_150F0D92;

        [STUField(0xE9420655, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_E9420655;

        [STUField(0xC558D07B, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_C558D07B;

        [STUField(0x1A9F17E4, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_1A9F17E4;

        [STUField(0x343E99EE, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_343E99EE;

        [STUField(0x3C0EB4A6, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_3C0EB4A6;

        [STUField(0x5E561E77, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_5E561E77;

        [STUField(0x3B7BED2E, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_A1AAB8C4 m_3B7BED2E;

        [STUField(0xB969AFC9, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_904BFCEC m_B969AFC9;

        [STUField(0x4E22B5C4, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUStatescriptOutputPlug m_4E22B5C4;

        [STUField(0x6EEEC0AA, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUStatescriptOutputPlug m_6EEEC0AA;
    }
}
