// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xA21064F1)]
    public class STU_A21064F1 : STULib.Types.STUConfigVar {
        [STUField(0x03EB0E34, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_03EB0E34;

        [STUField(0x7AB4E3F8, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_7AB4E3F8;

        [STUField(0x0619C597, "m_type")]
        public STULib.Types.Dump.Enums.STUEnum_2551B350 Type;
    }
}
