// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x216FE961)]
    public class STU_216FE961 : STU_3355C48D {
        [STUField(0xBC2DD253, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_00ABC9FF m_BC2DD253;

        [STUField(0x12751DF3, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_00ABC9FF m_12751DF3;
    }
}
