// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x2B7ACCC9)]
    public class STU_2B7ACCC9 : STU_DD856C32 {
        [STUField(0xFC1AFF3E, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_FC1AFF3E;

        [STUField(0xF5087894, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_F5087894;

        [STUField(0x52901F5C, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_52901F5C;

        [STUField(0xD115A49D, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_D115A49D;

        [STUField(0xB337A52B, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_B337A52B;

        [STUField(0x3A938263, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_3A938263;

        [STUField(0xB49B152F, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_B49B152F;

        [STUField(0xC0082C5F, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_C0082C5F;

        [STUField(0x261CB7E4, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_261CB7E4;

        [STUField(0x85B247CB, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_85B247CB;

        [STUField(0xDED09004, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_DED09004;
    }
}
