// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x440EFC3E)]
    public class STU_440EFC3E : STU_11E07FD7 {
        [STUField(0x0BCD10D6, "m_materialEffect")]
        public STULib.Types.Dump.STU_1A7B9DD3 MaterialEffect;

        [STUField(0x8332FCB2)]
        public STULib.Types.Dump.STU_5FF2A50C m_8332FCB2;

        [STUField(0xB2BFA0D7)]
        public STULib.Types.Dump.STU_5FF2A50C m_B2BFA0D7;

        [STUField(0xC6AAF4A0)]
        public STULib.Types.Dump.STU_5FF2A50C m_C6AAF4A0;
    }
}
