// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x1F15E24D)]
    public class STU_1F15E24D : STU_81C5DE19 {
        [STUField(0xF891229F)]
        public STULib.Types.Dump.STU_F7618109 m_F891229F;
    }
}
