// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xC817414F)]
    public class STU_C817414F : STU_DD856C32 {
        [STUField(0x1C413B73, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_9A40D4BB[] m_1C413B73;
    }
}
