// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xF4C02979)]
    public class STU_F4C02979 : STU_1F17F37B {
        [STUField(0xC8B9BBD1, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_FECA664E m_C8B9BBD1;
    }
}
