// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xA1BAFA3E)]
    public class STU_A1BAFA3E : STUInstance {
        [STUField(0xF2160520)]
        public STUGUID m_F2160520;  // STU_CDB49979

        [STUField(0x25521BD9)]
        public string m_25521BD9;

        [STUField(0xE7702748)]
        public uint m_E7702748;
    }
}
