// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x5FE555AA)]
    public class STU_5FE555AA : STU_6B892D91 {
        [STUField(0x5180E750)]
        public byte m_5180E750;
    }
}
