// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x3C61114B)]
    public class STU_3C61114B : STU_78D39627 {
        [STUField(0x07DD813E, "m_value")]
        public STUColorRGBA Value;
    }
}
