// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x6621502E)]
    public class STU_6621502E : STUStatescriptState {
        [STUField(0xC41767A5, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_C41767A5;

        [STUField(0x4D530E8A, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_4D530E8A;

        [STUField(0xF8072B62, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_F8072B62;

        [STUField(0x36634ED8, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_36634ED8;

        [STUField(0x678E6DC9, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_678E6DC9;

        [STUField(0x41CF4BA7, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_41CF4BA7;

        [STUField(0xA5DA12F3, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_A5DA12F3;

        [STUField(0xE9335452, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_E9335452;

        [STUField(0x6E880E01, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_6E880E01;

        [STUField(0x7320117C, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_7320117C;

        [STUField(0xB7A7D6B8, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_B7A7D6B8;

        [STUField(0x2DCE8B53, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_2DCE8B53;

        [STUField(0x6854990D, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_F6279B0F m_6854990D;

        [STUField(0x665704C8, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_F6279B0F m_665704C8;

        [STUField(0xB318A744, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_F6279B0F m_B318A744;
    }
}
