// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x37D754C8)]
    public class STU_37D754C8 : STU_72849AE5 {
        [STUField(0xF09A03B3, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_CD398197[] m_F09A03B3;

        [STUField(0x4C82A775, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_4C82A775;
    }
}
