// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x9F6C97AF)]
    public class STU_9F6C97AF : STU_A3C7077A {
        [STUField(0xAB865FDF)]
        public STUGUID m_AB865FDF;  // STUTexture

        [STUField(0xB999DDE2)]
        public STUGUID m_B999DDE2;  // STU_58B3D0D0

        [STUField(0xFD19FF42, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_851FBF1A m_FD19FF42;

        [STUField(0x2E05AF4F, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_851FBF1A m_2E05AF4F;

        [STUField(0x60C7A1E1, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_851FBF1A m_60C7A1E1;

        [STUField(0x09FC5294, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_851FBF1A m_09FC5294;

        [STUField(0x0403A33B, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_851FBF1A m_0403A33B;

        [STUField(0x76A0AE13)]
        public float m_76A0AE13;

        [STUField(0xD551B44D)]
        public float m_D551B44D;

        [STUField(0xAA110E15)]
        public byte m_AA110E15;

        [STUField(0xA47A57FE)]
        public byte m_A47A57FE;

        [STUField(0x4AB9A663)]
        public byte m_4AB9A663;
    }
}
