// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x4573639A)]
    public class STU_4573639A : STU_7A7F2732 {
        [STUField(0xD1B20DBC, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_D1B20DBC;

        [STUField(0x6E08307A, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUStatescriptOutputPlug m_6E08307A;
    }
}
