// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xA408D74F)]
    public class STU_A408D74F : STUInstance {
        [STUField(0x401F5484)]
        public STUGUID m_401F5484;  // STU_3FBD80C6

        [STUField(0xF79D31F9)]
        public STULib.Types.Dump.STU_6BB3C6F8[] m_F79D31F9;

        [STUField(0x4FF98D41, EmbeddedInstance = true)]
        public STULib.Types.STU_C1A2DB26 m_4FF98D41;

        [STUField(0x9CDDC24D)]
        public float m_9CDDC24D;
    }
}
