// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xE1AD8268)]
    public class STU_E1AD8268 : STU_6B892D91 {
        [STUField(0x5180E750)]
        public float m_5180E750;
    }
}
