// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xE75FE496)]
    public class STU_E75FE496 : STUInstance {
        [STUField(0x5CD2CFD4)]
        public ulong m_5CD2CFD4;

        [STUField(0x9626427F)]
        public uint m_9626427F;
    }
}
