// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xC3BB51AB)]
    public class STU_C3BB51AB : STU_1482DDBB {
        [STUField(0x669474F5, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_669474F5;

        [STUField(0xF12409D0, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_F12409D0;
    }
}
