// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x4648F8B2)]
    public class STU_4648F8B2 : STULib.Types.STU_866672AD {
        [STUField(0xCB8F4822)]
        public STULib.Types.Dump.STU_62679ECC m_CB8F4822;
    }
}
