// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x25ECB55F)]
    public class STU_25ECB55F : STU_1482DDBB {
        [STUField(0x88B0050A)]
        public STUGUID m_88B0050A;  // STU_0A29DB0D

        [STUField(0xA83C2C26, "m_entity", EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar Entity;
    }
}
