// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x15971773)]
    public class STU_15971773 : STULib.Types.STUEntityComponent2 {
        [STUField(0x59A530A3)]
        public byte m_59A530A3;
    }
}
