// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xC43F9944)]
    public class STU_C43F9944 : STU_DD856C32 {
        [STUField(0xBC2A8DA3, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_814D595E[] m_BC2A8DA3;

        [STUField(0xBAA74493, "m_condition", EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar Condition;

        [STUField(0x92A85396, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_92A85396;
    }
}
