// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x820A411A)]
    public class STU_820A411A : STU_11E07FD7 {
        [STUField(0xC0FB22A0)]
        public STULib.Types.Dump.STU_57C7508E m_C0FB22A0;

        [STUField(0x8D06BC6B)]
        public STULib.Types.Dump.STU_5FF2A50C m_8D06BC6B;

        [STUField(0x87D6D90B)]
        public STULib.Types.Dump.STU_5FF2A50C m_87D6D90B;

        [STUField(0x3823C999)]
        public STULib.Types.Dump.STU_8E54BCB2 m_3823C999;

        [STUField(0x2D78DB1F)]
        public STULib.Types.Dump.STU_8E54BCB2 m_2D78DB1F;

        [STUField(0x7EC17208)]
        public STULib.Types.Dump.STU_531DC494 m_7EC17208;

        [STUField(0x7DC1550F, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_00ABC9FF m_7DC1550F;

        [STUField(0xAF9D3A0C, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_00ABC9FF m_AF9D3A0C;

        [STUField(0x40AF7E2D, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_00ABC9FF m_40AF7E2D;

        [STUField(0x7C460E8F, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_00ABC9FF m_7C460E8F;

        [STUField(0x8FD005D3, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_00ABC9FF m_8FD005D3;

        [STUField(0x69810AA3, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_00ABC9FF m_69810AA3;

        [STUField(0x05874FA7, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_00ABC9FF m_05874FA7;

        [STUField(0xE70BB978, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_00ABC9FF m_E70BB978;
    }
}
