// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x785A6D26)]
    public class STU_785A6D26 : STULib.Types.STUEntityComponent {
    }
}
