// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x3FBD80C6)]
    public class STU_3FBD80C6 : STUInstance {
        [STUField(0x87DCD58E)]
        public STUGUID m_87DCD58E;  // STU_F38E9E14

        [STUField(0x099F25C9)]
        public STUGUID m_099F25C9;  // STULib.Types.STU_866672AD

        [STUField(0x2C54AEAF, "m_category")]
        public STUGUID Category;  // STU_23F2C185

        [STUField(0x4FF98D41, EmbeddedInstance = true)]
        public STULib.Types.STU_C1A2DB26 m_4FF98D41;

        [STUField(0xDF647B95)]
        public STULib.Types.Dump.Enums.STUEnum_BC00E017 m_DF647B95;

        [STUField(0x35EC21DC)]
        public STULib.Types.Dump.Enums.STUEnum_4368B765 m_35EC21DC;

        [STUField(0xA73F2EBE)]
        public float m_A73F2EBE;

        [STUField(0xDD27AC95)]
        public float m_DD27AC95;

        [STUField(0xF6658B6B)]
        public STULib.Types.Dump.Enums.STUEnum_A3FB08F9 m_F6658B6B;

        [STUField(0xBB16810A, "m_priority")]
        public uint Priority;

        [STUField(0x1CC5EF25)]
        public float m_1CC5EF25;

        [STUField(0xB1C6CDA2)]
        public float m_B1C6CDA2;

        [STUField(0xED61D926)]
        public float m_ED61D926;

        [STUField(0x9502010D)]
        public byte m_9502010D;

        [STUField(0xDC30A92A)]
        public byte m_DC30A92A;

        [STUField(0xAB866031)]
        public byte m_AB866031;

        [STUField(0xAC80C14A)]
        public byte m_AC80C14A;

        [STUField(0xEE144B9E)]
        public byte m_EE144B9E;

        [STUField(0xA9A901C1)]
        public byte m_A9A901C1;

        [STUField(0xAFCF2626)]
        public byte m_AFCF2626;

        [STUField(0xD7FE39AA)]
        public byte m_D7FE39AA;

        [STUField(0x345921CC)]
        public byte m_345921CC;

        [STUField(0x14A22FA7)]
        public byte m_14A22FA7;

        [STUField(0x252D7B29)]
        public byte m_252D7B29;

        [STUField(0x5D07FCC3)]
        public byte m_5D07FCC3;

        [STUField(0x1AD9EC4A)]
        public byte m_1AD9EC4A;
    }
}
