// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xCF0BA93B)]
    public class STU_CF0BA93B : STULib.Types.STU_866672AD {
        [STUField(0x736CEC96)]
        public STULib.Types.Dump.STU_7D5225A4 m_736CEC96;
    }
}
