// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x0996DA9C)]
    public class STU_0996DA9C : STU_6B892D91 {
        [STUField(0x5180E750)]
        public uint m_5180E750;
    }
}
