// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x7FD6D646)]
    public class STU_7FD6D646 : STU_2B795EDC {
        [STUField(0x9884BDEE, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_00ABC9FF m_9884BDEE;
    }
}
