// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x324FC4D1)]
    public class STU_324FC4D1 : STU_E896B267 {
        [STUField(0x52EA7AB9, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_52EA7AB9;

        [STUField(0x23D7F018, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_23D7F018;
    }
}
