// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x298FC27F)]
    public class STU_298FC27F : STUComponentInstanceData {
        [STUField(0x2746D7E4)]
        public STUUUID m_2746D7E4;

        [STUField(0x106543DC, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_A23BFD3B[] m_106543DC;

        [STUField(0x3A6C757E)]
        public STULib.Types.Enums.STUEnumTeamType[] m_3A6C757E;

        [STUField(0xE005252F)]
        public STULib.Types.Dump.Enums.STUEnum_FB7F61B4[] m_E005252F;

        [STUField(0x44CE67EA)]
        public int m_44CE67EA;

        [STUField(0x428B4854)]
        public STULib.Types.Dump.Enums.STUEnum_135DBBD2 m_428B4854;

        [STUField(0x7F8C228D)]
        public byte m_7F8C228D;
    }
}
