// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x3AA5CB04)]
    public class STU_3AA5CB04 : STULib.Types.STUEntityComponent2 {
        [STUField(0xC9D669B6)]
        public STUGUID Animation;  // STUAnimation

        [STUField(0xD91EF907)]
        public STUGUID Model;

        [STUField(0x7D921E31, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_2BA91EC5 m_7D921E31;

        [STUField(0x25D54A00, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_E93236BC m_25D54A00;

        [STUField(0x422B4A8E)]
        public int m_422B4A8E;

        [STUField(0xEDF6D105)]
        public float m_EDF6D105;

        [STUField(0x8D7C6FCE)]
        public uint m_8D7C6FCE;

        [STUField(0x5E009A60)]
        public byte m_5E009A60;
    }
}
