// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x6B63BDB4)]
    public class STU_6B63BDB4 : STU_1413B6A1 {
        [STUField(0xDC0C1E22, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_DC0C1E22;
    }
}
