// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x13BA4A46)]
    public class STU_13BA4A46 : STU_DD856C32 {
        [STUField(0x039D6F04)]
        public STUGUID[] m_039D6F04;  // STU_9CADF2EC
    }
}
