// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xB9BE2BE1)]
    public class STU_B9BE2BE1 : STU_7639CFC1 {
        [STUField(0x1A69E234)]
        public STULib.Types.Dump.Enums.STUEnum_AD46F1CE m_1A69E234;
    }
}
