// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x7EA1FCC6)]
    public class STU_7EA1FCC6 : STU_64C11507 {
        [STUField(0xF76C5837, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_6B892D91 m_F76C5837;
    }
}
