// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x98F34AAA)]
    public class STU_98F34AAA : STULib.Types.STU_866672AD {
        [STUField(0x6E7E23A2)]
        public STULib.Types.Dump.STU_78EB1F0C m_6E7E23A2;

        [STUField(0xB88E9E4E)]
        public STULib.Types.Dump.STU_E0EBAF96 m_B88E9E4E;

        [STUField(0x109FF315)]
        public STUGUID m_109FF315;

        [STUField(0xD3FB6931)]
        public STULib.Types.Dump.STU_43D7FE33[] m_D3FB6931;
    }
}
