// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x0A019882)]
    public class STU_0A019882 : STU_E5863169 {
        [STUField(0x8AD739CE, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_8AD739CE;

        [STUField(0x8213EB22, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_8213EB22;

        [STUField(0xA9561CA0)]
        public STULib.Types.Dump.Enums.STUEnum_4AC84BBD m_A9561CA0;
    }
}
