// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x55F837C2)]
    public class STU_55F837C2 : STU_CCAD18DB {
        [STUField(0x5180E750, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_5180E750;
    }
}
