// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xDD42A5FB)]
    public class STU_DD42A5FB : STU_8BE2DB4D {
        [STUField(0x64F87F5E, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_00ABC9FF m_64F87F5E;

        [STUField(0x6FF59B86, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_95ECA8A6 m_6FF59B86;

        [STUField(0x25517A47, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_95ECA8A6 m_25517A47;

        [STUField(0xCC1E4A6E, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_95ECA8A6 m_CC1E4A6E;
    }
}
