// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x739A3C1E)]
    public class STU_739A3C1E : STUStatescriptState {
        [STUField(0x33B0B2B6, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_33B0B2B6;
    }
}
