// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xCBEC0113)]
    public class STU_CBEC0113 : STU_1482DDBB {
        [STUField(0xF81F4386)]
        public STUDateAndTime m_F81F4386;

        [STUField(0xFBEBAD6F)]
        public STUDateAndTime m_FBEBAD6F;
    }
}
