// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x9C54C383)]
    public class STU_9C54C383 : STU_6D3ED020 {
        [STUField(0x7E2A700B, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_7E2A700B;
    }
}
