// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xCEBE1A86)]
    public class STU_CEBE1A86 : STU_81C5DE19 {
        [STUField(0xF891229F)]
        public STULib.Types.Dump.STU_EF734202 m_F891229F;

        [STUField(0xAEDA14F2, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_A8EFC6F0 m_AEDA14F2;

        [STUField(0x45A7A69C, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_A8EFC6F0 m_45A7A69C;
    }
}
