// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xBDB687C1)]
    public class STU_BDB687C1 : STUInstance {
        [STUField(0x4C0A85CC)]
        public float m_4C0A85CC;

        [STUField(0x90040B40)]
        public float m_90040B40;
    }
}
