// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xD7C0CE6D)]
    public class STU_D7C0CE6D : STU_7639CFC1 {
        [STUField(0x37AB13D3, "m_hero", EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar Hero;
    }
}
