// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x302A1299)]
    public class STU_302A1299 : STUInstance {
        [STUField(0x2DEE07D2, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_3CE15663[] m_2DEE07D2;

        [STUField(0x01689346)]
        public STUGUID m_01689346;  // STU_9CADF2EC
    }
}
