// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x6DBD812C)]
    public class STU_6DBD812C : STU_C7C085F6 {
        [STUField(0xAE4AC1D5)]
        public STUGUID m_AE4AC1D5;  // STUAnimation

        [STUField(0x88368856)]
        public STUGUID m_88368856;  // STUAnimation

        [STUField(0xA644447E)]
        public STUGUID m_A644447E;  // STUAnimation

        [STUField(0x78DDAEF6)]
        public STUGUID m_78DDAEF6;  // STUAnimation
    }
}
