// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x22926252)]
    public class STU_22926252 : STU_DD856C32 {
        [STUField(0x67B81D25, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_67B81D25;

        [STUField(0xEB35D2F1, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_EB35D2F1;
    }
}
