// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x34B3026E)]
    public class STU_34B3026E : STU_DD856C32 {
        [STUField(0x646B9249)]
        public byte m_646B9249;
    }
}
