// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x34ECF4D2)]
    public class STU_34ECF4D2 : STUInstance {
        [STUField(0x96053EC6)]
        public STULib.Types.STUStatescriptGraphWithOverrides[] m_96053EC6;

        [STUField(0x200EF939, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUStatescriptSchema m_200EF939;
    }
}
