// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xB1FA9C2A)]
    public class STU_B1FA9C2A : STUStatescriptState {
        [STUField(0x11E0A658, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_11E0A658;
    }
}
