// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x4703386B)]
    public class STU_4703386B : STUInstance {
        [STUField(0xEBD8430D)]
        public STUUUID m_EBD8430D;

        [STUField(0x3D00FDE1)]
        public STUUUID m_3D00FDE1;

        [STUField(0x9B62E942)]
        public string m_9B62E942;
    }
}
