// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xF1B7842C)]
    public class STU_F1B7842C : STULib.Types.STUEntityComponent {
    }
}
