// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x1B529163)]
    public class STU_1B529163 : STU_1361E674 {
        [STUField(0x57CBDD1E, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar[] m_57CBDD1E;
    }
}
