// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x76AF64F0)]
    public class STU_76AF64F0 : STULib.Types.STUEntityComponent {
        [STUField(0x0D7E5DF7)]
        public byte m_0D7E5DF7;
    }
}
