// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xF3894725)]
    public class STU_F3894725 : STU_DD856C32 {
        [STUField(0x66102571, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_66102571;

        [STUField(0x821F831C, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_821F831C;
    }
}
