// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x9AB01A35)]
    public class STU_9AB01A35 : STUComponentInstanceData {
        [STUField(0x2746D7E4)]
        public STUUUID m_2746D7E4;

        [STUField(0xA92070A2)]
        public STULib.Types.Dump.Enums.STUEnum_06FA22BB m_A92070A2;

        [STUField(0x30CD4137)]
        public float m_30CD4137;

        [STUField(0x4579B961)]
        public float m_4579B961;

        [STUField(0x2C0246C1)]
        public float m_2C0246C1;

        [STUField(0xA3B3682C)]
        public byte m_A3B3682C;
    }
}
