// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xAF97FFDF)]
    public class STU_AF97FFDF : STU_79F9EE42 {
        [STUField(0xC08C4427)]
        public string m_C08C4427;

        [STUField(0xC43222BC)]
        public string m_C43222BC;

        [STUField(0xF90C6330)]
        public string m_F90C6330;

        [STUField(0xBE17C500)]
        public ulong m_BE17C500;

        [STUField(0xAB15196B)]
        public float m_AB15196B;

        [STUField(0xB8B6FB84)]
        public float m_B8B6FB84;

        [STUField(0xCC84D865)]
        public int m_CC84D865;

        [STUField(0x16D6D2C4)]
        public int m_16D6D2C4;

        [STUField(0xF40C44B2)]
        public int m_F40C44B2;

        [STUField(0x54847F6D)]
        public int m_54847F6D;

        [STUField(0x98EC9B0F)]
        public byte m_98EC9B0F;

        [STUField(0x4B94049E)]
        public byte m_4B94049E;

        [STUField(0x070C5DB4)]
        public byte m_070C5DB4;

        [STUField(0x410CF0BB)]
        public byte m_410CF0BB;
    }
}
