// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x73E1C5F0)]
    public class STU_73E1C5F0 : STU_1482DDBB {
        [STUField(0xA8D12F28, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_A8D12F28;

        [STUField(0xA83C2C26, "m_entity", EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar Entity;
    }
}
