// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xC2DC60F6)]
    public class STU_C2DC60F6 : STULib.Types.STUGraphNode {
        [STUField(0x5328E4F8)]
        public string m_5328E4F8;

        [STUField(0xBF5B22B7)]
        public STULib.Types.Dump.STUStatescriptRemoteSyncVar[] m_BF5B22B7;

        [STUField(0x8BF03679)]
        public STULib.Types.Dump.STUStatescriptRemoteSyncVar[] m_8BF03679;

        [STUField(0x871A8203)]
        public int m_871A8203;

        [STUField(0x602E1F8F)]
        public int m_602E1F8F;

        [STUField(0xAED90719)]
        public STULib.Types.Dump.Enums.STUEnum_CEBBB217 m_AED90719;

        [STUField(0x2BBEEAB8)]
        public byte m_2BBEEAB8;

        [STUField(0xADEB6E05)]
        public byte m_ADEB6E05;

        [STUField(0xE1B0C07F)]
        public byte m_E1B0C07F;

        [STUField(0x9A861B79)]
        public byte m_9A861B79;
    }
}
