// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x05765425)]
    public class STU_05765425 : STU_E896B267 {
        [STUField(0x5902E774, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_5902E774;
    }
}
