// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x632B0263)]
    public class STU_632B0263 : STU_6D3ED020 {
        [STUField(0x181A7823, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_181A7823;

        [STUField(0x0619C597, "m_type")]
        public STULib.Types.Dump.Enums.STUEnum_43CDE438 Type;
    }
}
