// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x68F68CD7)]
    public class STU_68F68CD7 : STU_1482DDBB {
        [STUField(0xA83C2C26, "m_entity", EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar Entity;
    }
}
