// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x3F0712C9)]
    public class STU_3F0712C9 : STU_4B6F9A4C {
        [STUField(0x79FF9EB6)]
        public STULib.Types.Dump.STU_AE2F63FC m_79FF9EB6;

        [STUField(0xD697B92C)]
        public STULib.Types.Dump.STU_D11C922F m_D697B92C;

        [STUField(0x89F953D0)]
        public STULib.Types.Dump.STU_0B5C5FB3 m_89F953D0;
    }
}
