// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xE3EF9AFE)]
    public class STU_E3EF9AFE : STU_0BCD3EFA {
        [STUField(0xB3C3FC65, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_B3C3FC65;

        [STUField(0xD860501E)]
        public STULib.Types.Dump.Enums.STUEnum_DF89E084 m_D860501E;
    }
}
