// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xD5808AB6)]
    public class STU_D5808AB6 : STU_3660CDED {
        [STUField(0x3FAFF222)]
        public STULib.Types.Dump.Enums.STUEnum_BB366339 m_3FAFF222;
    }
}
