// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x6AE5D1A1)]
    public class STU_6AE5D1A1 : STUStatescriptState {
        [STUField(0x20D151F5, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_20D151F5;

        [STUField(0x07BA97ED, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_07BA97ED;

        [STUField(0x8CD49F22, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_8CD49F22;

        [STUField(0x426B3962, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_426B3962;

        [STUField(0x50CF633B, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_50CF633B;

        [STUField(0xEB0FC261, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_EB0FC261;

        [STUField(0x592D15F7, "m_out_Var", EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic OutVar;

        [STUField(0x9B0385B4, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_9B0385B4;

        [STUField(0x5BEFF040, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_5BEFF040;

        [STUField(0x5DA62D02, "m_onAbortPlug", EmbeddedInstance = true)]
        public STULib.Types.Dump.STUStatescriptOutputPlug OnAbortPlug;

        [STUField(0xA0B58111, "m_onFinishedPlug", EmbeddedInstance = true)]
        public STULib.Types.Dump.STUStatescriptOutputPlug OnFinishedPlug;

        [STUField(0xCB671004)]
        public byte m_CB671004;

        [STUField(0x9FF96195)]
        public byte m_9FF96195;
    }
}
