// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x5AFB02C7)]
    public class STU_5AFB02C7 : STUStatescriptState {
        [STUField(0xF3E612FD, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_F3E612FD;

        [STUField(0x50D63347, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_50D63347;
    }
}
