// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xD3C407EA)]
    public class STU_D3C407EA : STU_0C8ADF02 {
        [STUField(0x3CD6DC1E, "m_texture")]
        public STUGUID Texture;  // STUTexture

        [STUField(0x6B7FA624, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_95ECA8A6 m_6B7FA624;

        [STUField(0x0989C43B, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_95ECA8A6 m_0989C43B;

        [STUField(0xC708FD07, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_95ECA8A6 m_C708FD07;

        [STUField(0x190ECECC, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_95ECA8A6 m_190ECECC;
    }
}
