// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xBD47F80F)]
    public class STU_BD47F80F : STULib.Types.STU_866672AD {
        [STUField(0x37AB13D3, "m_hero")]
        public STUGUID Hero;  // STULib.Types.STUHero

        [STUField(0xCB6873D7)]
        public STUGUID[] m_CB6873D7;  // STULib.Types.STUEntityDefinition
    }
}
