// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xF4EBAC89)]
    public class STU_F4EBAC89 : STU_7AC83411 {
        [STUField(0x7594F80E)]
        public STUVec4 m_7594F80E;

        [STUField(0x7CEA65C7)]
        public STUVec4 m_7CEA65C7;

        [STUField(0x8EBB2A67)]
        public byte m_8EBB2A67;
    }
}
