// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xA90C5991)]
    public class STU_A90C5991 : STU_DD856C32 {
        [STUField(0x2B82763B, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_2B82763B;

        [STUField(0x22248C37, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_22248C37;

        [STUField(0x5C22817C, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_5C22817C;

        [STUField(0xE3798C00, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_E3798C00;
    }
}
