// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x9163D489)]
    public class STU_9163D489 : STUStatescriptState {
        [STUField(0x1A18950A, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_1A18950A;
    }
}
