// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x8811A9AC)]
    public class STU_8811A9AC : STUInstance {
        [STUField(0x11B47C68)]
        public STUGUID m_11B47C68;  // STU_9CADF2EC
    }
}
