// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xE2BCEF50)]
    public class STU_E2BCEF50 : STU_DD856C32 {
        [STUField(0x3CFA3EE6, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_3CFA3EE6;

        [STUField(0xC2AD5EAC, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_C2AD5EAC;

        [STUField(0x746D78FE, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_746D78FE;
    }
}
