// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x70CB9161)]
    public class STU_70CB9161 : STUInstance {
        [STUField(0xB0CFD234, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_115D40BB[] m_B0CFD234;
    }
}
