// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x5F887DF9)]
    public class STU_5F887DF9 : STU_DD856C32 {
        [STUField(0x039D6F04)]
        public STUGUID[] m_039D6F04;  // STU_9CADF2EC

        [STUField(0xCC5A5415, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_CC5A5415;

        [STUField(0x3222698F, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_3222698F;

        [STUField(0x736EC9C3, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_736EC9C3;

        [STUField(0x2D922A09, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_2D922A09;

        [STUField(0xFE6205BA, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_FE6205BA;

        [STUField(0x12988ACA, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_12988ACA;

        [STUField(0x6A3B2047, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_6A3B2047;
    }
}
