// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x1C68E74D)]
    public class STU_1C68E74D : STU_BB7E7366 {
        [STUField(0x75DD5735)]
        public STUGUID m_75DD5735;  // STU_BC48636B

        [STUField(0x3547155A, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_EDCF5A52 m_3547155A;

        [STUField(0x4B31E7B9, EmbeddedInstance = true)]
        public STULib.Types.Dump.STU_C1210E7A m_4B31E7B9;
    }
}
