// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x02F7FEA4)]
    public class STU_02F7FEA4 : STU_7A7F2732 {
        [STUField(0x7C91E3AB)]
        public STUGUID m_7C91E3AB;

        [STUField(0x06DEF45D, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_06DEF45D;

        [STUField(0x1C509E3A, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_1C509E3A;

        [STUField(0xDF98EE87, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_DF98EE87;

        [STUField(0xD4801407, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_D4801407;

        [STUField(0x65A4E503, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUStatescriptOutputPlug m_65A4E503;

        [STUField(0x659088F1, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUStatescriptOutputPlug m_659088F1;

        [STUField(0x63E5B241, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUStatescriptOutputPlug m_63E5B241;

        [STUField(0x0D54AA0B, EmbeddedInstance = true)]
        public STULib.Types.Dump.STUConfigVarDynamic m_0D54AA0B;

        [STUField(0xB2818AF4, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_B2818AF4;

        [STUField(0xD79BF2C4, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_D79BF2C4;
    }
}
