// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x0AB00BC1)]
    public class STU_0AB00BC1 : STU_DD856C32 {
        [STUField(0xEC7246B3)]
        public STULib.Types.Dump.Enums.STUEnum_5F827B4A m_EC7246B3;
    }
}
