// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x54FDFF64)]
    public class STU_54FDFF64 : STU_F4431A1F {
        [STUField(0xDC8A3A89, EmbeddedInstance = true)]
        public STULib.Types.STUConfigVar m_DC8A3A89;
    }
}
