// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0xAA1BBA7B)]
    public class STU_AA1BBA7B : STU_15043B61 {
        [STUField(0x3CD6DC1E, "m_texture")]
        public STULib.Types.Dump.STU_10F1ED2F Texture;
    }
}
