// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x187495F3)]
    public class STU_187495F3 : STU_416D9897 {
        [STUField(0xB44A42A0)]
        public STULib.Types.Dump.Enums.STUEnum_E7FEC166 m_B44A42A0;
    }
}
