// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x3CE15663)]
    public class STU_3CE15663 : STUInstance {
        [STUField(0x1574C6B7)]
        public STUGUID m_1574C6B7;  // STU_9CADF2EC

        [STUField(0xDEEF0875)]
        public STUGUID m_DEEF0875;  // STU_1C5DE3A3
    }
}
