// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Dump {
    [STU(0x5981B16B, "STUStatescriptSchema")]
    public class STUStatescriptSchema : STUInstance {
        [STUField(0x16B4863C, EmbeddedInstance = true)]
        public STULib.Types.STUStatescriptSchemaEntry[] m_16B4863C;
    }
}
