// File auto generated by STUHashTool

using STULib.Types.Enums;
using static STULib.Types.Generic.Common;

namespace STULib.Types.GameParams {
    [STU(0x074EDCB9)]
    public class STUGameParam : STUInstance {
        [STUField(0xAA76FAD1)]
        public STUGUID Name;

        [STUField(0x7DF418A5)]
        public STUGUID Name2;

        [STUField(0x3E783677)]
        public STUGUID Virtual01C;  // STU_9CADF2EC

        [STUField(0x7E3ED979)]
        public STUGUID[] m_7E3ED979;  // STU_0A29DB0D

        [STUField(0x34993B2E)]
        public STUGUID[] m_34993B2E;  // STU_0A29DB0D

        [STUField(0x07DD813E, EmbeddedInstance = true)]
        public STUGameParamBaseOptions Options;

        [STUField(0x65184E78, EmbeddedInstance = true)]
        public STU_96788737 m_65184E78;

        [STUField(0x2C54AEAF, "m_category")]
        public STUEnum_F2F62E3D Category;

        [STUField(0x37D4F9CD)]
        public int UnknownInt;
    }
}
