// File auto generated by STUHashTool

namespace STULib.Types.AnimationList.x021 {
    [STU(0x3426C7F2)]
    public class STU_3426C7F2 : STUAnimationListWrapperBase {
        [STUField(0x07DD813E)]
        public STU_F6279B0F m_07DD813E;
    }
}
