// File auto generated by STUHashTool

using STULib.Types.Generic;

namespace STULib.Types.AnimationList.x021 {
    [STU(0xDF9B7DE2)]
    public class STU_DF9B7DE2 : Common.STUInstance {
        [STUField(0x7EEFB57A)]
        public ushort m_7EEFB57A;
    }
}
