// File auto generated by STUHashTool

using STULib.Types.Generic;

namespace STULib.Types.AnimationList.x021 {
    [STU(0x152ED1AE)]
    public class STU_152ED1AE : Common.STUInstance {
        [STUField(0x6DE8A8A1, Demangle = false)]
        public Common.STUGUID Variable;

        [STUField(0x07DD813E, "m_value")]
        public float Value;
    }
}
