// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0xB396243E, "LineupOverrideCharacter")]
    public class LineupOverrideCharacter : STUInstance
    {
        [STUField(0xC0A83121)]
        public teStructuredDataAssetRef<ulong> m_skin;
        
        [STUField(0x7DD89F4F)]
        public teStructuredDataAssetRef<ulong> m_entityDef;
        
        [STUField(0xEF19F506)]
        public teStructuredDataAssetRef<STUUnlock> m_poseUnlock;
    }
}
