// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7D75D3EF, "SDD_AABB3D")]
    public class SDD_AABB3D : SDD_3D {
        [STUFieldAttribute(0x982D7B62, "vPosTo_WS")]
        public teVec3 vPosTo_WS;
    }
}
