// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3DD6C6E9, "SDD_3D")]
    public class SDD_3D : SDD_Base {
        [STUFieldAttribute(0xB58C7E7A, "vPos_WS")]
        public teVec3 vPos_WS;
    }
}
