// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF6A17A1C, "SDD_TriList")]
    public class SDD_TriList : SDD_Base {
        [STUFieldAttribute(0x320FB5B4, "TriList", ReaderType = typeof(InlineInstanceFieldReader))]
        public SDD_Tri[] TriList;
    }
}
