// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5FD84627)]
    public class STU_5FD84627 : STUStatescriptStateUXPresenter {
    }
}
