// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFB4767A4)]
    public class STU_FB4767A4 : STU_252FDE3A {
        [STUFieldAttribute(0xC9AD5769, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C9AD5769;
    }
}
