// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3E938620)]
    public class STU_3E938620 : STUConfigVarNumeric {
        [STUFieldAttribute(0x5427168E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5427168E;

        [STUFieldAttribute(0x08DB7212, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_08DB7212;
    }
}
