// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5A381A2F)]
    public class STU_5A381A2F : STUInstance {
        [STUFieldAttribute(0x136D7F30)]
        public byte m_136D7F30;
    }
}
