// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD1A190D9)]
    public class STU_D1A190D9 : STU_4CD7AF84 {
        [STUFieldAttribute(0xC3E03C7F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_C3E03C7F;

        [STUFieldAttribute(0xBA05C78B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_BA05C78B;
    }
}
