// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x523A0948)]
    public class STU_523A0948 : STU_B70E6976 {
        [STUFieldAttribute(0x38BFB46C, "m_resourceKey")]
        public teStructuredDataAssetRef<STUResourceKey> m_resourceKey;

        [STUFieldAttribute(0x0201671C)]
        public ulong m_0201671C;

        [STUFieldAttribute(0x8C4782E9, "m_outPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_5DA834CA m_outPlug;

        [STUFieldAttribute(0xE4AACE6E)]
        public byte m_E4AACE6E;
    }
}
