// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5FDDF6E9)]
    public class STU_5FDDF6E9 : STU_CF110906 {
        [STUFieldAttribute(0xF9C9453C)]
        public ulong m_F9C9453C;

        [STUFieldAttribute(0x33DCB4EB)]
        public byte m_33DCB4EB;

        [STUFieldAttribute(0x7C9BE696)]
        public byte m_7C9BE696;

        [STUFieldAttribute(0x42E1D14D)]
        public byte m_42E1D14D;
    }
}
