// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1ADE6F60)]
    public class STU_1ADE6F60 : STUConfigVarBoolBase {
        [STUFieldAttribute(0xA83C2C26, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;

        [STUFieldAttribute(0xAA32165B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_AA32165B;

        [STUFieldAttribute(0xC13A7F78, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C13A7F78;

        [STUFieldAttribute(0x03E1A642, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_03E1A642;
    }
}
