// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x058958BF)]
    public class STU_058958BF : STU_F9C57875 {
        [STUFieldAttribute(0xA83C2C26, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;

        [STUFieldAttribute(0x1491A204, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1491A204;

        [STUFieldAttribute(0x37AB13D3, "m_hero", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_hero;

        [STUFieldAttribute(0xBC4326FF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BC4326FF;

        [STUFieldAttribute(0x5ED79353)]
        public Enum_10064D07 m_5ED79353;
    }
}
