// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF0580634)]
    public class STU_F0580634 : STU_A3C7077A {
        [STUFieldAttribute(0xCDBFC5EC)]
        public teStructuredDataAssetRef<STUTexture> m_CDBFC5EC;

        [STUFieldAttribute(0x7E1EF4A3)]
        public teStructuredDataAssetRef<STUTexture> m_7E1EF4A3;

        [STUFieldAttribute(0x2997BBEC)]
        public teStructuredDataAssetRef<STUTexture> m_2997BBEC;

        [STUFieldAttribute(0x6EE70996)]
        public teStructuredDataAssetRef<STUTexture> m_6EE70996;

        [STUFieldAttribute(0x09E32A58)]
        public teStructuredDataAssetRef<STUTexture> m_09E32A58;

        [STUFieldAttribute(0xB999DDE2)]
        public teStructuredDataAssetRef<STUEmptyAsset> m_B999DDE2;

        [STUFieldAttribute(0x02C2A46E)]
        public teStructuredDataAssetRef<STUTexture> m_02C2A46E;

        [STUFieldAttribute(0x6C7256B5)]
        public float m_6C7256B5;

        [STUFieldAttribute(0x8C565BF8)]
        public uint m_8C565BF8;

        [STUFieldAttribute(0x18E97C4F)]
        public float m_18E97C4F;
    }
}
