// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC7CA73B1)]
    public class STU_C7CA73B1 : STU_2F33B1B7 {
        [STUFieldAttribute(0xE02BEE24, "m_celebration")]
        public teStructuredDataAssetRef<STUCelebration> m_celebration;
    }
}
