// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x63DD95AD)]
    public class STU_63DD95AD : STUConfigVarBoolBase {
    }
}
