// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA94C5E3B)]
    public class STU_A94C5E3B : STU_4BA3D4E6 {
        [STUFieldAttribute(0xF1CB3BA0, "m_text")]
        public teString m_text;
    }
}
