// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4C8D9F5E)]
    public class STU_4C8D9F5E : STU_82AA6830 {
        [STUFieldAttribute(0x10EFDE90)]
        public teVec3 m_10EFDE90;

        [STUFieldAttribute(0xC320C90B)]
        public teVec3 m_C320C90B;

        [STUFieldAttribute(0xED61D926, "m_radius")]
        public float m_radius;
    }
}
