// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x72B012B8)]
    public class STU_72B012B8 : STUStatescriptState {
        [STUFieldAttribute(0x9D07CD91)]
        public teStructuredDataAssetRef<STU_51BAFC27> m_9D07CD91;

        [STUFieldAttribute(0x133B14AC, "m_onGoingDownPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onGoingDownPlug;

        [STUFieldAttribute(0xA36EEE40, "m_onComingUpPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onComingUpPlug;

        [STUFieldAttribute(0x80AF45FB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_904BFCEC m_80AF45FB;

        [STUFieldAttribute(0x1C9EF058, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_904BFCEC m_1C9EF058;
    }
}
