// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFA258ECC)]
    public class STU_FA258ECC : STU_5DB5B1C9 {
        [STUFieldAttribute(0xC41767A5)]
        public float m_C41767A5;

        [STUFieldAttribute(0x4D530E8A)]
        public float m_4D530E8A;
    }
}
