// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB8A901AC)]
    public class STU_B8A901AC : STUUXDependencyObject {
    }
}
