// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xEF7D4667)]
    public class STU_EF7D4667 : STUGameModeLegacy {
        [STUFieldAttribute(0x37AB13D3, "m_hero")]
        public teStructuredDataAssetRef<STUHero> m_hero;
    }
}
