// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0C37A184)]
    public class STU_0C37A184 : STU_1361E674 {
        [STUFieldAttribute(0x5B9DD0CB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5B9DD0CB;
    }
}
