// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF66CEBE4)]
    public class STU_F66CEBE4 : STUStatescriptState {
        [STUFieldAttribute(0xB5A24467, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B5A24467;
    }
}
