// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x6243C768)]
    public class STU_6243C768 : STUStatescriptState {
        [STUFieldAttribute(0xF869F71E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_F869F71E;

        [STUFieldAttribute(0xA620F372, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A620F372;

        [STUFieldAttribute(0x9FE321EE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9FE321EE;
    }
}
