// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFEA540AB)]
    public class STU_FEA540AB : STU_81C5DE19 {
        [STUFieldAttribute(0xF891229F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_2F54E672 m_F891229F;
    }
}
