// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB7C66FFD)]
    public class STU_B7C66FFD : STU_C7C085F6 {
        [STUFieldAttribute(0x1E3118F7)]
        public teStructuredDataAssetRef<ulong> m_1E3118F7;

        [STUFieldAttribute(0x5F150DBC, "m_jump")]
        public teStructuredDataAssetRef<ulong> m_jump;

        [STUFieldAttribute(0x29BEC526)]
        public float m_29BEC526;

        [STUFieldAttribute(0xDB28A84C)]
        public float m_DB28A84C;

        [STUFieldAttribute(0x83CE3EB5)]
        public float m_83CE3EB5;

        [STUFieldAttribute(0x7910195B)]
        public byte m_7910195B;
    }
}
