// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xAC0B4B19)]
    public class STU_AC0B4B19 : STU_54FD3952 {
        [STUFieldAttribute(0xEE8626EF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EE8626EF;
    }
}
