// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD0BC4B50)]
    public class STU_D0BC4B50 : STU_64C11507 {
        [STUFieldAttribute(0x1BFAA158, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUUXObject m_1BFAA158;

        [STUFieldAttribute(0xC6DE7D6E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUUXObject m_C6DE7D6E;

        [STUFieldAttribute(0x68272D39, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUUXObject m_68272D39;

        [STUFieldAttribute(0x20AE2CCB)]
        public Enum_1E2FFF3B m_20AE2CCB;

        [STUFieldAttribute(0xB979C324)]
        public Enum_B89BB376 m_B979C324;
    }
}
