// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x2BB9B0AE)]
    public class STU_2BB9B0AE : STU_EED46159 {
        [STUFieldAttribute(0x2D18B3DB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2D18B3DB;

        [STUFieldAttribute(0x10EE20FF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_10EE20FF;
    }
}
