// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1392EB73)]
    public class STU_1392EB73 : STUConfigVarNumeric {
        [STUFieldAttribute(0x81FBE359)]
        public Enum_B748E23E m_81FBE359;
    }
}
