// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x74B41EA0)]
    public class STU_74B41EA0 : STU_DD856C32 {
        [STUFieldAttribute(0xEDB2BD2A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EDB2BD2A;

        [STUFieldAttribute(0x8ABF9743, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8ABF9743;

        [STUFieldAttribute(0xF1AB5AF4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F1AB5AF4;

        [STUFieldAttribute(0xF929CB26, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F929CB26;
    }
}
