// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8DF12675)]
    public class STU_8DF12675 : STU_F86AF375 {
        [STUFieldAttribute(0x66D09C06)]
        public ulong m_66D09C06;
    }
}
