// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3388617A)]
    public class STU_3388617A : STU_1482DDBB {
        [STUFieldAttribute(0xF3E612FD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F3E612FD;
    }
}
