// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE088225F)]
    public class STU_E088225F : STUConfigVarIntBase {
    }
}
