// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xAD4DC133)]
    public class STU_AD4DC133 : STU_A2B9762B {
        [STUFieldAttribute(0x2756356E)]
        public teStructuredDataAssetRef<ulong> m_2756356E;

        [STUFieldAttribute(0x516C59FA)]
        public teStructuredDataAssetRef<ulong> m_516C59FA;

        [STUFieldAttribute(0x74638B25, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_362761D6[] m_74638B25;

        [STUFieldAttribute(0xFCE12C19, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_4703386B[] m_FCE12C19;

        [STUFieldAttribute(0xB51441D9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_4294267F[] m_B51441D9;

        [STUFieldAttribute(0xA22DBBCD)]
        public teUUID[] m_A22DBBCD;

        [STUFieldAttribute(0xE577592B)]
        public byte m_E577592B;
    }
}
