// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBBF32277)]
    public class STU_BBF32277 : STUStatescriptState {
        [STUFieldAttribute(0xA60150E2)]
        public uint m_A60150E2;
    }
}
