// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0780EFFD)]
    public class STU_0780EFFD : STUConfigVarBoolBase {
    }
}
