// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x582E0D5F)]
    public class STU_582E0D5F : STUStatescriptState {
        [STUFieldAttribute(0xF5C94645, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F5C94645;

        [STUFieldAttribute(0x63FFE8DF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_63FFE8DF;

        [STUFieldAttribute(0x494A6B1F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_494A6B1F;

        [STUFieldAttribute(0x6A79BD98, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6A79BD98;

        [STUFieldAttribute(0x6B30E42C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6B30E42C;

        [STUFieldAttribute(0xB53E150A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B53E150A;

        [STUFieldAttribute(0x0C4BE468, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0C4BE468;

        [STUFieldAttribute(0x51EFD5D6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_51EFD5D6;

        [STUFieldAttribute(0x02400C28, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_02400C28;

        [STUFieldAttribute(0x767D90FD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_767D90FD;

        [STUFieldAttribute(0x4AB67781, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4AB67781;

        [STUFieldAttribute(0xD0103F1A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D0103F1A;

        [STUFieldAttribute(0x595AE325, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_595AE325;

        [STUFieldAttribute(0x8C563869, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8C563869;

        [STUFieldAttribute(0x7642C777, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7642C777;

        [STUFieldAttribute(0xAB5F32F7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_AB5F32F7;

        [STUFieldAttribute(0x79370307, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_79370307;

        [STUFieldAttribute(0xB31CA390, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B31CA390;

        [STUFieldAttribute(0x84DD5440, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_84DD5440;

        [STUFieldAttribute(0x481B15D1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_481B15D1;

        [STUFieldAttribute(0xF4669F53, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F4669F53;

        [STUFieldAttribute(0xB05ABDFF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B05ABDFF;

        [STUFieldAttribute(0x1A76C130, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1A76C130;

        [STUFieldAttribute(0x62F44973, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_62F44973;
    }
}
