// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x714EA6C9)]
    public class STU_714EA6C9 : STU_8811A9AC {
        [STUFieldAttribute(0xB48F1D22, "m_name")]
        public teStructuredDataAssetRef<ulong> m_name;

        [STUFieldAttribute(0x5E000370)]
        public teStructuredDataAssetRef<STUUXLink> m_5E000370;
    }
}
