// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x02C0109E)]
    public class STU_02C0109E : STUStatescriptDataFlowEntity {
    }
}
