// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x78EF92B0)]
    public class STU_78EF92B0 : STUInstance {
        [STUFieldAttribute(0x54D5D418)]
        public teString m_54D5D418;

        [STUFieldAttribute(0x5A225D06)]
        public teString m_5A225D06;

        [STUFieldAttribute(0x7B2B78C1)]
        public ulong m_7B2B78C1;

        [STUFieldAttribute(0xBCAB7478)]
        public uint m_BCAB7478;
    }
}
