// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7E1706D1)]
    public class STU_7E1706D1 : STUInstance {
        [STUFieldAttribute(0x40ADB62A)]
        public teUUID m_40ADB62A;

        [STUFieldAttribute(0x4DE207E1)]
        public teStructuredDataAssetRef<ulong> m_4DE207E1;
    }
}
