// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x94320319)]
    public class STU_94320319 : STU_48A39D9B {
        [STUFieldAttribute(0x8CF4A632, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_7FA0F929[] m_8CF4A632;
    }
}
