// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x888494B6)]
    public class STU_888494B6 : STUConfigVarBoolBase {
    }
}
