// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xCCECB92D)]
    public class STU_CCECB92D : STU_1361E674 {
        [STUFieldAttribute(0x57CBDD1E, "m_configVars", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar[] m_configVars;
    }
}
