// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x482ABA91)]
    public class STU_482ABA91 : STU_1361E674 {
        [STUFieldAttribute(0x57CBDD1E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar[] m_57CBDD1E;
    }
}
