// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC3ABE193)]
    public class STU_C3ABE193 : STUEntityComponent {
    }
}
