// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFBFF5DE7)]
    public class STU_FBFF5DE7 : STUStatescriptState {
        [STUFieldAttribute(0x87A4D0AD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_87A4D0AD;

        [STUFieldAttribute(0x3A5CB679, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3A5CB679;

        [STUFieldAttribute(0xB1003775, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B1003775;

        [STUFieldAttribute(0x9A978490, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9A978490;

        [STUFieldAttribute(0xB988692B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B988692B;

        [STUFieldAttribute(0x59FD6833, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_59FD6833;

        [STUFieldAttribute(0x8A696888, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8A696888;

        [STUFieldAttribute(0x7CBA482F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7CBA482F;

        [STUFieldAttribute(0x81759372, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_81759372;

        [STUFieldAttribute(0x26DA7CF8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_26DA7CF8;
    }
}
