// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x653C3526)]
    public class STU_653C3526 : STUInstance {
        [STUFieldAttribute(0xC3E03C7F, "m_color")]
        public teColorRGB m_color;

        [STUFieldAttribute(0xAE2D8911, "m_index")]
        public int m_index;
    }
}
