// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x11F91F88)]
    public class STU_11F91F88 : STU_BDB86C7B {
        [STUFieldAttribute(0x3CE25BEF, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_25B808BD m_3CE25BEF;

        [STUFieldAttribute(0x07DD2836, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_ABD8FE73 m_07DD2836;

        [STUFieldAttribute(0x56FB28DA, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_ABD8FE73 m_56FB28DA;

        [STUFieldAttribute(0x73CA0463, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_ABD8FE73 m_73CA0463;
    }
}
