// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE0A69706)]
    public class STU_E0A69706 : STUConfigVarStringBase {
        [STUFieldAttribute(0xAA76FAD1, "m_displayText", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_displayText;
    }
}
