// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA636010F)]
    public class STU_A636010F : STUUXDependencyObject {
    }
}
