// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x61D59E77)]
    public class STU_61D59E77 : STUInstance {
        [STUFieldAttribute(0xC3885423, "m_rankedSeason")]
        public int m_rankedSeason;

        [STUFieldAttribute(0xB0999384)]
        public byte m_B0999384;

        [STUFieldAttribute(0xC2F1227D)]
        public byte m_C2F1227D;

        [STUFieldAttribute(0x4DED9A95)]
        public byte m_4DED9A95;

        [STUFieldAttribute(0x58AF2221)]
        public byte m_58AF2221;

        [STUFieldAttribute(0x3AF982FE)]
        public byte m_3AF982FE;
    }
}
