// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9B1122C1)]
    public class STU_9B1122C1 : STUStatescriptInputPlug {
    }
}
