// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x39C45A97)]
    public class STU_39C45A97 : STUStatescriptAction {
    }
}
