// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0BD44E3B)]
    public class STU_0BD44E3B : STUUXViewModel {
        [STUFieldAttribute(0x3E39ADA3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_970D008F[] m_3E39ADA3;

        [STUFieldAttribute(0x63DFD7EF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A0BDC3D3 m_63DFD7EF;

        [STUFieldAttribute(0x09657D8A, "m_mode")]
        public int m_mode;

        [STUFieldAttribute(0xBFABC230)]
        public float m_BFABC230;

        [STUFieldAttribute(0x7D0DBDE5)]
        public uint m_7D0DBDE5;

        [STUFieldAttribute(0xF10CDDB8)]
        public byte m_F10CDDB8;

        [STUFieldAttribute(0x792E1BC9)]
        public byte m_792E1BC9;

        [STUFieldAttribute(0x9C12FD92)]
        public byte m_9C12FD92;

        [STUFieldAttribute(0x901C7A5D)]
        public byte m_901C7A5D;

        [STUFieldAttribute(0xC3A40C09)]
        public byte m_C3A40C09;

        [STUFieldAttribute(0x22C6B36A)]
        public byte m_22C6B36A;

        [STUFieldAttribute(0x44B2188B)]
        public byte m_44B2188B;

        [STUFieldAttribute(0x52595913)]
        public byte m_52595913;
    }
}
