// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x38733FCC)]
    public class STU_38733FCC : STUInstance {
        [STUFieldAttribute(0x5DB91CE2, "m_displayName")]
        public teString m_displayName;

        [STUFieldAttribute(0xE8D9FEB2)]
        public teStructuredDataAssetRef<STU_CD3B0D14> m_E8D9FEB2;

        [STUFieldAttribute(0xD45946D7)]
        public uint m_D45946D7;
    }
}
