// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4D89A1EE)]
    public class STU_4D89A1EE : STUStatescriptAction {
        [STUFieldAttribute(0x78A08312, "m_string", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_string;
    }
}
