// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5AFB02C7)]
    public class STU_5AFB02C7 : STUStatescriptState {
        [STUFieldAttribute(0xF3E612FD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F3E612FD;

        [STUFieldAttribute(0x50D63347, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_50D63347;
    }
}
