// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC795AFF0)]
    public class STU_C795AFF0 : STUConfigVarResource {
        [STUFieldAttribute(0x37AB13D3, "m_hero", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_hero;

        [STUFieldAttribute(0xDF8ABDB9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_DF8ABDB9;
    }
}
