// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB96D3A98)]
    public class STU_B96D3A98 : STU_1482DDBB {
        [STUFieldAttribute(0xA83C2C26, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;
    }
}
