// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB6C6668E)]
    public class STU_B6C6668E : STUStatescriptStateUXPresenter {
        [STUFieldAttribute(0xDF8ABDB9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_DF8ABDB9;

        [STUFieldAttribute(0xF018B0FE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F018B0FE;

        [STUFieldAttribute(0x4245AFEE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_4245AFEE;
    }
}
