// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7C69EA0F)]
    public class STU_7C69EA0F : STU_2F33B1B7 {
        [STUFieldAttribute(0x4FF98D41, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_C1A2DB26[] m_4FF98D41;

        [STUFieldAttribute(0xAF872E86)]
        public uint m_AF872E86;
    }
}
