// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x97368A55)]
    public class STU_97368A55 : STUInstance {
        [STUFieldAttribute(0xDC71317C, "m_start", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_start;

        [STUFieldAttribute(0x83BE3F26, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_83BE3F26;

        [STUFieldAttribute(0x04B2C103, "m_end", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_end;
    }
}
