// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x520E0AB7)]
    public class STU_520E0AB7 : STU_F029B472 {
        [STUFieldAttribute(0x334938EC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_0CF6650E m_334938EC;
    }
}
