// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB025A89F)]
    public class STU_B025A89F : STUUXAnimatable {
    }
}
