// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xAF97FFDF)]
    public class STU_AF97FFDF : STUUXViewModel {
        [STUFieldAttribute(0xC08C4427, "m_name")]
        public teString m_name;

        [STUFieldAttribute(0xC43222BC, "m_amount")]
        public teString m_amount;

        [STUFieldAttribute(0xF90C6330)]
        public teString m_F90C6330;

        [STUFieldAttribute(0xBE17C500, "m_stat")]
        public ulong m_stat;

        [STUFieldAttribute(0xAB15196B)]
        public float m_AB15196B;

        [STUFieldAttribute(0xB8B6FB84)]
        public float m_B8B6FB84;

        [STUFieldAttribute(0xCC84D865)]
        public int m_CC84D865;

        [STUFieldAttribute(0x16D6D2C4, "m_rank")]
        public int m_rank;

        [STUFieldAttribute(0xF40C44B2)]
        public int m_F40C44B2;

        [STUFieldAttribute(0x54847F6D)]
        public int m_54847F6D;

        [STUFieldAttribute(0x98EC9B0F)]
        public byte m_98EC9B0F;

        [STUFieldAttribute(0x4B94049E)]
        public byte m_4B94049E;

        [STUFieldAttribute(0x070C5DB4)]
        public byte m_070C5DB4;

        [STUFieldAttribute(0x410CF0BB)]
        public byte m_410CF0BB;
    }
}
