// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9F6C97AF)]
    public class STU_9F6C97AF : STU_A3C7077A {
        [STUFieldAttribute(0xAB865FDF)]
        public teStructuredDataAssetRef<STUTexture> m_AB865FDF;

        [STUFieldAttribute(0xB999DDE2)]
        public teStructuredDataAssetRef<STUEmptyAsset> m_B999DDE2;

        [STUFieldAttribute(0x1B5648DE)]
        public teStructuredDataAssetRef<STUIdentifier> m_1B5648DE;

        [STUFieldAttribute(0xFD19FF42, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_851FBF1A m_FD19FF42;

        [STUFieldAttribute(0x2E05AF4F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_851FBF1A m_2E05AF4F;

        [STUFieldAttribute(0x60C7A1E1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_851FBF1A m_60C7A1E1;

        [STUFieldAttribute(0x09FC5294, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_851FBF1A m_09FC5294;

        [STUFieldAttribute(0x0403A33B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_851FBF1A m_0403A33B;

        [STUFieldAttribute(0x76A0AE13)]
        public float m_76A0AE13;

        [STUFieldAttribute(0xD551B44D)]
        public float m_D551B44D;

        [STUFieldAttribute(0xAA110E15)]
        public byte m_AA110E15;

        [STUFieldAttribute(0xA47A57FE)]
        public byte m_A47A57FE;

        [STUFieldAttribute(0x4AB9A663)]
        public byte m_4AB9A663;

        [STUFieldAttribute(0x10AEBFA1)]
        public byte m_10AEBFA1;
    }
}
