// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8462E0A8)]
    public class STU_8462E0A8 : STU_7639CFC1 {
        [STUFieldAttribute(0x52223784)]
        public Enum_B26D0BFA m_52223784;
    }
}
