// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x93B8758C)]
    public class STU_93B8758C : STUStatescriptState {
        [STUFieldAttribute(0xA5B7A147)]
        public teStructuredDataAssetRef<ulong> m_A5B7A147;

        [STUFieldAttribute(0x4A5CA514, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4A5CA514;
    }
}
