// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x953A25F9)]
    public class STU_953A25F9 : STUGenericSettings_Base {
        [STUFieldAttribute(0x176E889D)]
        public teString[] m_176E889D;

        [STUFieldAttribute(0x56E5100A, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_2D619054[] m_56E5100A;
    }
}
