// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9C3FFA87)]
    public class STU_9C3FFA87 : STUInstance {
        [STUFieldAttribute(0x2AF1FCC8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2AF1FCC8;

        [STUFieldAttribute(0x07DD813E, "m_value", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_value;
    }
}
