// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBE000386)]
    public class STU_BE000386 : STUMapLayer {
        [STUFieldAttribute(0x60BA1950, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_5B028314[] m_60BA1950;

        [STUFieldAttribute(0xDAF86B4D)]
        public teStructuredDataAssetRef<STU_F3EB00D4> m_DAF86B4D;
    }
}
