// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0A2AA55B)]
    public class STU_0A2AA55B : STUStatescriptStateUXPresenter {
    }
}
