// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3B150012)]
    public class STU_3B150012 : STUInstance {
        [STUFieldAttribute(0xC486B05D)]
        public float[] m_C486B05D;

        [STUFieldAttribute(0xC8893DFC)]
        public teVec2[] m_C8893DFC;

        [STUFieldAttribute(0x92DE5D4B)]
        public teVec3[] m_92DE5D4B;

        [STUFieldAttribute(0xC76F0FE9)]
        public byte[] m_C76F0FE9;

        [STUFieldAttribute(0x5AD927D3)]
        public teStructuredDataAssetRef<STUAnimation>[] m_5AD927D3;

        [STUFieldAttribute(0x69D5B5ED)]
        public ulong[] m_69D5B5ED;

        [STUFieldAttribute(0xB4975FA6)]
        public teStructuredDataAssetRef<STUAnimCategory>[] m_B4975FA6;

        [STUFieldAttribute(0x12FC4EE4)]
        public teStructuredDataAssetRef<STUDataFlow>[] m_12FC4EE4;

        [STUFieldAttribute(0x2E394711)]
        public teStructuredDataAssetRef<STUAnimSynchGroup>[] m_2E394711;

        [STUFieldAttribute(0x5DB71937)]
        public teStructuredDataAssetRef<STUAnimIdentifier>[] m_5DB71937;

        [STUFieldAttribute(0xD196E84C)]
        public teStructuredDataAssetRef<STUBoneLabel>[] m_D196E84C;

        [STUFieldAttribute(0x30CB50F5)]
        public teStructuredDataAssetRef<STUHardPoint>[] m_30CB50F5;

        [STUFieldAttribute(0x45F3B47D)]
        public teStructuredDataAssetRef<STUAnimBoneWeightMask>[] m_45F3B47D;

        [STUFieldAttribute(0x38BB939A, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimCurveCompiled[] m_38BB939A;

        [STUFieldAttribute(0x29EFF18D, "m_crc")]
        public ulong m_crc;

        [STUFieldAttribute(0xFA7268E4)]
        public uint m_FA7268E4;
    }
}
