// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB206B380)]
    public class STU_B206B380 : STU_9248C10B {
        [STUFieldAttribute(0xA53100D5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A53100D5;
    }
}
