// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC1C2EFA3)]
    public class STU_C1C2EFA3 : STU_F0DD346F {
        [STUFieldAttribute(0xA845975B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A845975B;
    }
}
