// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x71D4FA0B)]
    public class STU_71D4FA0B : STUConfigVarIntBase {
        [STUFieldAttribute(0x37AB13D3, "m_hero", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_hero;

        [STUFieldAttribute(0x1A69E234, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1A69E234;
    }
}
