// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD66BFB3A)]
    public class STU_D66BFB3A : STUGameModeLegacy {
        [STUFieldAttribute(0x5EF69B1D)]
        public uint m_5EF69B1D;

        [STUFieldAttribute(0x7A4EDD2B)]
        public uint m_7A4EDD2B;
    }
}
