// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x111A6193)]
    public class STU_111A6193 : STUInstance {
        [STUFieldAttribute(0xBA891264, "m_dataFlow")]
        public teStructuredDataAssetRef<STUDataFlow> m_dataFlow;

        [STUFieldAttribute(0x1F3357A2)]
        public byte m_1F3357A2;
    }
}
