// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5A959709)]
    public class STU_5A959709 : STUStatescriptAction {
    }
}
