// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF3EB00D4)]
    public class STU_F3EB00D4 : STUInstance {
        [STUFieldAttribute(0xB3685B0D)]
        public teStructuredDataAssetRef<ulong> m_B3685B0D;

        [STUFieldAttribute(0xF7BBC834)]
        public teStructuredDataAssetRef<ulong> m_F7BBC834;

        [STUFieldAttribute(0xBD1B72B9, "m_soundSwitch")]
        public teStructuredDataAssetRef<ulong> m_soundSwitch;

        [STUFieldAttribute(0xEE400AC2)]
        public teStructuredDataAssetRef<ulong> m_EE400AC2;

        [STUFieldAttribute(0x7F032FBB)]
        public teStructuredDataAssetRef<ulong> m_7F032FBB;

        [STUFieldAttribute(0x2EE47073)]
        public teStructuredDataAssetRef<ulong>[] m_2EE47073;

        [STUFieldAttribute(0x6F28B37B)]
        public float m_6F28B37B;

        [STUFieldAttribute(0xAA9332D3)]
        public float m_AA9332D3;

        [STUFieldAttribute(0xC3D42367)]
        public float m_C3D42367;

        [STUFieldAttribute(0xD3B0B025)]
        public float m_D3B0B025;
    }
}
