// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x092D53B5)]
    public class STU_092D53B5 : STU_A3C7077A {
        [STUFieldAttribute(0x09E32A58)]
        public teStructuredDataAssetRef<STUTexture> m_09E32A58;

        [STUFieldAttribute(0x369489D8)]
        public teStructuredDataAssetRef<STUTexture> m_369489D8;

        [STUFieldAttribute(0xB999DDE2)]
        public teStructuredDataAssetRef<STUEmptyAsset> m_B999DDE2;

        [STUFieldAttribute(0xAB865FDF)]
        public float m_AB865FDF;

        [STUFieldAttribute(0xE47A724C)]
        public float m_E47A724C;

        [STUFieldAttribute(0x6FA6AE0D)]
        public float m_6FA6AE0D;

        [STUFieldAttribute(0x1A864EF2)]
        public float m_1A864EF2;

        [STUFieldAttribute(0x4A195F0E)]
        public byte m_4A195F0E;
    }
}
