// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBC48636B)]
    public class STU_BC48636B : STUInstance {
        [STUFieldAttribute(0x335CC942, "m_data", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D3350D13 m_data;
    }
}
