// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD06FC89B)]
    public class STU_D06FC89B : STUStatescriptState {
        [STUFieldAttribute(0x9595751F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9595751F;

        [STUFieldAttribute(0xB23D7599, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B23D7599;

        [STUFieldAttribute(0x819D0B1C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_819D0B1C;

        [STUFieldAttribute(0xA27F013E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A27F013E;

        [STUFieldAttribute(0x653B5C29, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_653B5C29;

        [STUFieldAttribute(0x71DBDBE0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_71DBDBE0;

        [STUFieldAttribute(0x23B3F791, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_23B3F791;

        [STUFieldAttribute(0x87709A20, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_87709A20;

        [STUFieldAttribute(0x554523AD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_554523AD;
    }
}
