// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA037D670)]
    public class STU_A037D670 : STUConfigVarEntityID {
        [STUFieldAttribute(0xC7021C2A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C7021C2A;

        [STUFieldAttribute(0xF8274C10, "m_filter", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarFilter m_filter;
    }
}
