// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA6E894BC)]
    public class STU_A6E894BC : STU_C7C085F6 {
        [STUFieldAttribute(0xBD2F9E2A)]
        public teStructuredDataAssetRef<STUAnimation> m_BD2F9E2A;

        [STUFieldAttribute(0x90F1CC7E)]
        public teStructuredDataAssetRef<STUAnimation> m_90F1CC7E;

        [STUFieldAttribute(0x439DEB0C)]
        public teStructuredDataAssetRef<STUAnimation> m_439DEB0C;

        [STUFieldAttribute(0x3A339D0E)]
        public teStructuredDataAssetRef<STUAnimation> m_3A339D0E;

        [STUFieldAttribute(0xB86BBFF7)]
        public teStructuredDataAssetRef<STUAnimation> m_B86BBFF7;

        [STUFieldAttribute(0xC027E938)]
        public teStructuredDataAssetRef<STUAnimation> m_C027E938;

        [STUFieldAttribute(0x5620DA50, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_B0D9AEDF m_5620DA50;

        [STUFieldAttribute(0xEC42051A, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_57C43142 m_EC42051A;

        [STUFieldAttribute(0xF0E4656D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_19354E9E m_F0E4656D;

        [STUFieldAttribute(0xCFE161F4)]
        public float m_CFE161F4;

        [STUFieldAttribute(0x7CFDCCAE)]
        public float m_7CFDCCAE;

        [STUFieldAttribute(0xB8665261)]
        public float m_B8665261;

        [STUFieldAttribute(0x6C8B21FF)]
        public float m_6C8B21FF;

        [STUFieldAttribute(0x3C58C7E2)]
        public float m_3C58C7E2;

        [STUFieldAttribute(0x0493A576)]
        public float m_0493A576;

        [STUFieldAttribute(0xE8502460)]
        public float m_E8502460;

        [STUFieldAttribute(0x83CE3EB5)]
        public float m_83CE3EB5;
    }
}
