// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x35AA91CE)]
    public class STU_35AA91CE : STUInstance {
        [STUFieldAttribute(0x4227DBDA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_7C27312D[] m_4227DBDA;

        [STUFieldAttribute(0x96BA111F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_87CF2645 m_96BA111F;

        [STUFieldAttribute(0xD7A96218)]
        public uint[] m_D7A96218;

        [STUFieldAttribute(0x5E1BC440, "m_base", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_024ED1FF m_base;
    }
}
