// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x2FA26A06)]
    public class STU_2FA26A06 : STU_A30EF84D {
        [STUFieldAttribute(0x6525E98B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6525E98B;
    }
}
