// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x2B8093CD)]
    public class STU_2B8093CD : STUInstance {
        [STUFieldAttribute(0x2226CBD8, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_91B28B0A m_2226CBD8;

        [STUFieldAttribute(0x0503A846)]
        public teStructuredDataAssetRef<STUIdentifier> m_0503A846;

        [STUFieldAttribute(0x2C05CD95, "m_catalog")]
        public teStructuredDataAssetRef<STUMapCatalog> m_catalog;

        [STUFieldAttribute(0x4EEA6AF4, "m_rulesets")]
        public teStructuredDataAssetRef<STUGameRuleset>[] m_rulesets;

        [STUFieldAttribute(0x6F71E9AA, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUGameModeVarValuePair[] m_6F71E9AA;

        [STUFieldAttribute(0xAF929704)]
        public teStructuredDataAssetRef<STU_8B0E97DC>[] m_AF929704;

        [STUFieldAttribute(0x3CE93B76, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUGameModeVarValuePair[] m_3CE93B76;

        [STUFieldAttribute(0x13E9E420)]
        public teStructuredDataAssetRef<STUIdentifier> m_13E9E420;

        [STUFieldAttribute(0x70045C77, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_58E4EC09[] m_70045C77;

        [STUFieldAttribute(0x27326EE2)]
        public teStructuredDataAssetRef<STUStat> m_27326EE2;

        [STUFieldAttribute(0xBA265ADB)]
        public teStructuredDataAssetRef<STUStat>[] m_BA265ADB;

        [STUFieldAttribute(0x920F5684)]
        public teStructuredDataAssetRef<STUIdentifier>[] m_920F5684;

        [STUFieldAttribute(0x7B61EE6D)]
        public teStructuredDataAssetRef<STUStat>[] m_7B61EE6D;

        [STUFieldAttribute(0xA848F2C7)]
        public teStructuredDataAssetRef<STU_4B259FE1> m_A848F2C7;

        [STUFieldAttribute(0xECCC6D23)]
        public teStructuredDataAssetRef<STUAchievement>[] m_ECCC6D23;

        [STUFieldAttribute(0xB1449DF7)]
        public teStructuredDataAssetRef<STUUnlock>[] m_B1449DF7;

        [STUFieldAttribute(0x66C923AF, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_1A325379[] m_66C923AF;

        [STUFieldAttribute(0x7FB46D96, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_2B17E5B4[] m_7FB46D96;

        [STUFieldAttribute(0xD7E28280)]
        public teStructuredDataAssetRef<ulong> m_D7E28280;

        [STUFieldAttribute(0x679737B3)]
        public teStructuredDataAssetRef<STU_2B8093CD> m_679737B3;

        [STUFieldAttribute(0xAB6047ED)]
        public float m_AB6047ED;

        [STUFieldAttribute(0xDF66954A)]
        public float m_DF66954A;

        [STUFieldAttribute(0xFE68E10F)]
        public float m_FE68E10F;

        [STUFieldAttribute(0x53EE78EF)]
        public float m_53EE78EF;

        [STUFieldAttribute(0xD0D08449)]
        public float m_D0D08449;

        [STUFieldAttribute(0x68F23F53)]
        public int m_68F23F53;

        [STUFieldAttribute(0x44BB5E3A)]
        public byte m_44BB5E3A;

        [STUFieldAttribute(0x5E1EE04A)]
        public byte m_5E1EE04A;

        [STUFieldAttribute(0x08E3EC71)]
        public byte m_08E3EC71;

        [STUFieldAttribute(0x9C833A7F)]
        public byte m_9C833A7F;

        [STUFieldAttribute(0x0BB1E4C3)]
        public byte m_0BB1E4C3;

        [STUFieldAttribute(0x157AF68C)]
        public byte m_157AF68C;

        [STUFieldAttribute(0x3A9D36A5)]
        public byte m_3A9D36A5;

        [STUFieldAttribute(0x0BF2EFB0)]
        public byte m_0BF2EFB0;

        [STUFieldAttribute(0xB412D9AA)]
        public byte m_B412D9AA;

        [STUFieldAttribute(0xF67DA48B)]
        public byte m_F67DA48B;

        [STUFieldAttribute(0x58739879)]
        public byte m_58739879;

        [STUFieldAttribute(0xA6570990)]
        public byte m_A6570990;

        [STUFieldAttribute(0xD66FABE0)]
        public byte m_D66FABE0;

        [STUFieldAttribute(0x7F08E444)]
        public byte m_7F08E444;

        [STUFieldAttribute(0x313C5ED5)]
        public byte m_313C5ED5;

        [STUFieldAttribute(0xF011ED7A)]
        public byte m_F011ED7A;

        [STUFieldAttribute(0x8F862EC7)]
        public byte m_8F862EC7;

        [STUFieldAttribute(0xE566638A)]
        public byte m_E566638A;

        [STUFieldAttribute(0x14F75354)]
        public byte m_14F75354;

        [STUFieldAttribute(0x60F1B417)]
        public byte m_60F1B417;

        [STUFieldAttribute(0xCC271A4B)]
        public byte m_CC271A4B;
    }
}
