// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF6CCDAFC)]
    public class STU_F6CCDAFC : STU_B7EEA3BE {
        [STUFieldAttribute(0x0EDCE350)]
        public teStructuredDataAssetRef<ulong> m_0EDCE350;

        [STUFieldAttribute(0xA5C9CA02)]
        public teString m_A5C9CA02;

        [STUFieldAttribute(0xF61E3F46)]
        public teString m_F61E3F46;

        [STUFieldAttribute(0x84625AA3)]
        public teStructuredDataAssetRef<ulong>[] m_84625AA3;

        [STUFieldAttribute(0x053595FD)]
        public teStructuredDataAssetRef<ulong> m_053595FD;

        [STUFieldAttribute(0xDBEF61FE)]
        public teStructuredDataAssetRef<ulong>[] m_DBEF61FE;

        [STUFieldAttribute(0x38BFB46C)]
        public teStructuredDataAssetRef<STU_1DA7C021> m_38BFB46C;

        [STUFieldAttribute(0x49A51309)]
        public teString m_49A51309;

        [STUFieldAttribute(0x62746D34)]
        public byte m_62746D34;
    }
}
