// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0EC9EF75)]
    public class STU_0EC9EF75 : STU_48A39D9B {
        [STUFieldAttribute(0xE1D625B8)]
        public teStructuredDataAssetRef<STU_06095C06> m_E1D625B8;
    }
}
