// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7DA1278D)]
    public class STU_7DA1278D : STUConfigVarBoolBase {
        [STUFieldAttribute(0x67B81D25, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_67B81D25;
    }
}
