// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x835A7560)]
    public class STU_835A7560 : STU_0CF6650E {
        [STUFieldAttribute(0x08CACF3A)]
        public Enum_149525F6 m_08CACF3A;
    }
}
