// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x86882FB6)]
    public class STU_86882FB6 : STUStatescriptOutputPlug {
    }
}
