// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x41B3FC2B)]
    public class STU_41B3FC2B : STUStatescriptState {
        [STUFieldAttribute(0x6B5DA460, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6B5DA460;

        [STUFieldAttribute(0xFAF3B2D3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FAF3B2D3;

        [STUFieldAttribute(0x57EB3097, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_57EB3097;

        [STUFieldAttribute(0x001619B6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_001619B6;

        [STUFieldAttribute(0x609E2FBF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_609E2FBF;

        [STUFieldAttribute(0x9B27B995, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9B27B995;

        [STUFieldAttribute(0x5DA62D02, "m_onAbortPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onAbortPlug;

        [STUFieldAttribute(0xA0B58111, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;

        [STUFieldAttribute(0xDB02E9FF)]
        public Enum_A5A116FF m_DB02E9FF;
    }
}
