// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x71C0D73D)]
    public class STU_71C0D73D : STUInstance {
        [STUFieldAttribute(0xBEBA3AEF)]
        public teStructuredDataAssetRef<ulong> m_BEBA3AEF;

        [STUFieldAttribute(0xC65AA24E)]
        public teStructuredDataAssetRef<ulong> m_C65AA24E;

        [STUFieldAttribute(0xC21DB248)]
        public teStructuredDataAssetRef<STU_B77FCA72> m_C21DB248;

        [STUFieldAttribute(0x7F40AF15)]
        public int m_7F40AF15;

        [STUFieldAttribute(0xBB850F3A)]
        public int m_BB850F3A;

        [STUFieldAttribute(0x007EC1B9)]
        public int m_007EC1B9;

        [STUFieldAttribute(0x475BF075)]
        public byte m_475BF075;

        [STUFieldAttribute(0x1237A4CB)]
        public byte m_1237A4CB;
    }
}
