// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4A7AC5BF)]
    public class STU_4A7AC5BF : STUInstance {
        [STUFieldAttribute(0xEE3055BD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EE3055BD;
    }
}
