// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9B4C6EBC)]
    public class STU_9B4C6EBC : STUStatescriptAction {
    }
}
