// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD906F79D)]
    public class STU_D906F79D : STUInstance {
        [STUFieldAttribute(0xA9EFE4DD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A9EFE4DD;

        [STUFieldAttribute(0x612CE3B3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_612CE3B3;

        [STUFieldAttribute(0x543725F7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_543725F7;

        [STUFieldAttribute(0xE0E2C915, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E0E2C915;

        [STUFieldAttribute(0x408295AF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_408295AF;

        [STUFieldAttribute(0x59ED78CF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_59ED78CF;

        [STUFieldAttribute(0xC6546C69, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C6546C69;

        [STUFieldAttribute(0x52DA5C08, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_52DA5C08;

        [STUFieldAttribute(0x82BF9656, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_82BF9656;

        [STUFieldAttribute(0x5B7874B5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5B7874B5;

        [STUFieldAttribute(0x49138914, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_49138914;

        [STUFieldAttribute(0x21411EEE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_21411EEE;

        [STUFieldAttribute(0xDF63D700, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_DF63D700;

        [STUFieldAttribute(0x7776FA89, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7776FA89;

        [STUFieldAttribute(0xBA8C2F5D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BA8C2F5D;

        [STUFieldAttribute(0xA90085ED, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A90085ED;

        [STUFieldAttribute(0x3EFCF512, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3EFCF512;

        [STUFieldAttribute(0xB29B96B2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B29B96B2;
    }
}
