// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9DF5D8CC)]
    public class STU_9DF5D8CC : STUUXAnimatable {
    }
}
