// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB0AD7FF2)]
    public class STU_B0AD7FF2 : STU_2B795EDC {
        [STUFieldAttribute(0xE1D92DC4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_E1D92DC4;
    }
}
