// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5E1D1776)]
    public class STU_5E1D1776 : STUInstance {
        [STUFieldAttribute(0xA58EE665)]
        public ulong m_A58EE665;

        [STUFieldAttribute(0xF2A58A6D)]
        public uint m_F2A58A6D;

        [STUFieldAttribute(0xFE67B51B)]
        public uint m_FE67B51B;

        [STUFieldAttribute(0xF036B16E)]
        public uint m_F036B16E;

        [STUFieldAttribute(0xDF2DA8B3)]
        public byte m_DF2DA8B3;
    }
}
