// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE178B0DC)]
    public class STU_E178B0DC : STUStatescriptStateUXPresenter {
    }
}
