// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB22F3583)]
    public class STU_B22F3583 : STUInstance {
        [STUFieldAttribute(0xF94DAB61, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_F94DAB61;
    }
}
