// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x992CD1C4)]
    public class STU_992CD1C4 : STU_22DB169C {
        [STUFieldAttribute(0xB5C0F593, "m_guid")]
        public teStructuredDataAssetRef<STUUXLink> m_guid;
    }
}
