// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x6810506D)]
    public class STU_6810506D : STU_E5863169 {
        [STUFieldAttribute(0x9B7A63EA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9B7A63EA;

        [STUFieldAttribute(0xA9561CA0)]
        public Enum_4AC84BBD m_A9561CA0;
    }
}
