// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xEE825B6F)]
    public class STU_EE825B6F : STU_C71ECB5D {
        [STUFieldAttribute(0x0619C597, "m_type", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_type;

        [STUFieldAttribute(0xF24E4110, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F24E4110;
    }
}
