// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA4F5B721)]
    public class STU_A4F5B721 : STU_4B6F9A4C {
        [STUFieldAttribute(0xA7AC6320, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_99556822 m_A7AC6320;
    }
}
