// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE04F510A)]
    public class STU_E04F510A : STUConfigVarFloatBase {
    }
}
