// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0519019F)]
    public class STU_0519019F : STUInstance {
        [STUFieldAttribute(0xF2810377)]
        public teStructuredDataAssetRef<STU_9CADF2EC> m_F2810377;

        [STUFieldAttribute(0xC3657821)]
        public teStructuredDataAssetRef<STUHardPoint> m_C3657821;

        [STUFieldAttribute(0x4F5E7D4C)]
        public Enum_909B56BB m_4F5E7D4C;

        [STUFieldAttribute(0xED6D601D)]
        public uint m_ED6D601D;

        [STUFieldAttribute(0xA60150E2)]
        public uint m_A60150E2;
    }
}
