// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5F31962C)]
    public class STU_5F31962C : STUInstance {
        [STUFieldAttribute(0xBAA74493, "m_condition", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_condition;

        [STUFieldAttribute(0x4BA4C058)]
        public Enum_CEBBB217 m_4BA4C058;
    }
}
