// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD2496A99)]
    public class STU_D2496A99 : STU_4B6F9A4C {
        [STUFieldAttribute(0xA7AC6320, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_28C8ED13 m_A7AC6320;

        [STUFieldAttribute(0xD697B92C, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D11C922F m_D697B92C;
    }
}
