// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5FF2A50C)]
    public class STU_5FF2A50C : STU_3660CDED {
        [STUFieldAttribute(0x3FAFF222)]
        public Enum_F7F34DD0 m_3FAFF222;
    }
}
