// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF7618109)]
    public class STU_F7618109 : STU_13CAF4F2 {
        [STUFieldAttribute(0x63691AF6, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigWeightSet m_63691AF6;

        [STUFieldAttribute(0x34EA4470, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigWeightSet m_34EA4470;

        [STUFieldAttribute(0x099F3E75, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigWeightSet m_099F3E75;

        [STUFieldAttribute(0x0CCE726E, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigWeightSet m_0CCE726E;

        [STUFieldAttribute(0xED840ACB, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigWeightSet m_ED840ACB;

        [STUFieldAttribute(0x0DCDCE86, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigWeightSet m_0DCDCE86;

        [STUFieldAttribute(0x8AD014A4, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigWeightSet m_8AD014A4;

        [STUFieldAttribute(0xF64B2B67, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigWeightSet m_F64B2B67;

        [STUFieldAttribute(0x3B439936, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigWeightSet m_3B439936;
    }
}
