// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x817BB7C6)]
    public class STU_817BB7C6 : STUConfigVarResource {
        [STUFieldAttribute(0xA9D270A9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A9D270A9;

        [STUFieldAttribute(0x37AB13D3, "m_hero", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_hero;

        [STUFieldAttribute(0x1D78837A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1D78837A;
    }
}
