// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDB63E5F8)]
    public class STU_DB63E5F8 : STU_A3C7077A {
        [STUFieldAttribute(0xB999DDE2)]
        public teStructuredDataAssetRef<STU_58B3D0D0> m_B999DDE2;

        [STUFieldAttribute(0xF0A9405A)]
        public teStructuredDataAssetRef<STUTeamColor> m_F0A9405A;

        [STUFieldAttribute(0xB14EAA65)]
        public float m_B14EAA65;
    }
}
