// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x017D75DF)]
    public class STU_017D75DF : STU_81C5DE19 {
        [STUFieldAttribute(0xF891229F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_E2DB55BC m_F891229F;

        [STUFieldAttribute(0x4376ACB9, "m_additiveFiring", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A8EFC6F0 m_additiveFiring;
    }
}
