// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC5B280AA)]
    public class STU_C5B280AA : STU_E896B267 {
        [STUFieldAttribute(0xA83C2C26, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;
    }
}
