// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD8FE5B96)]
    public class STU_D8FE5B96 : STU_5008135C {
        [STUFieldAttribute(0x98010FDB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_98010FDB;

        [STUFieldAttribute(0x0D37C471, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_0D37C471;

        [STUFieldAttribute(0x5B5F5868, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_5B5F5868;

        [STUFieldAttribute(0x94C46E4C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_94C46E4C;
    }
}
