// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC4C4708C)]
    public class STU_C4C4708C : STUStatescriptStateUXPresenter {
    }
}
