// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFDFD8B46)]
    public class STU_FDFD8B46 : STU_704FE611 {
        [STUFieldAttribute(0x63118DB8, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_75C51D6F[] m_63118DB8;
    }
}
