// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x16753B11)]
    public class STU_16753B11 : STU_1482DDBB {
        [STUFieldAttribute(0xEB4F2408, "m_gamemode", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_gamemode;
    }
}
