// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x2DADE18A)]
    public class STU_2DADE18A : STUConfigVarIntBase {
        [STUFieldAttribute(0x0619C597, "m_type")]
        public Enum_7827CC64 m_type;
    }
}
