// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC1B4892A)]
    public class STU_C1B4892A : STU_E9DE9DF8 {
        [STUFieldAttribute(0xC0EDA193, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUGraphPlug m_C0EDA193;

        [STUFieldAttribute(0x0619C597, "m_type", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_5008135C m_type;
    }
}
