// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x55E8AFA9)]
    public class STU_55E8AFA9 : STU_116D2B98 {
        [STUFieldAttribute(0xBA53D5ED, "m_guid", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_guid;
    }
}
