// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8270436D)]
    public class STU_8270436D : STUUXDependencyObject {
        [STUFieldAttribute(0xADE95629, "m_items", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_5B307C96[] m_items;
    }
}
