// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3EA7C732)]
    public class STU_3EA7C732 : STU_C7C085F6 {
        [STUFieldAttribute(0xADC07CC9)]
        public teStructuredDataAssetRef<STUAnimation> m_ADC07CC9;

        [STUFieldAttribute(0x84103042)]
        public teStructuredDataAssetRef<STUDataFlow> m_84103042;

        [STUFieldAttribute(0xABE79AB8)]
        public float m_ABE79AB8;

        [STUFieldAttribute(0x518C56AA)]
        public float m_518C56AA;
    }
}
