// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE13B30A8)]
    public class STU_E13B30A8 : STUStatescriptStateUXPresenter {
        [STUFieldAttribute(0xE92C3801, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E92C3801;
    }
}
