// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7C543D41)]
    public class STU_7C543D41 : STUInstance {
        [STUFieldAttribute(0x3D83C363, "m_assets", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5BB2E270[] m_assets;
    }
}
