// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF06E752D)]
    public class STU_F06E752D : STU_DD856C32 {
        [STUFieldAttribute(0xD1216388, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D1216388;

        [STUFieldAttribute(0x6A928816, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6A928816;

        [STUFieldAttribute(0xFA349AB6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FA349AB6;
    }
}
