// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA69B15DF)]
    public class STU_A69B15DF : STU_2B795EDC {
        [STUFieldAttribute(0x7FD2A8D4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_7FD2A8D4;

        [STUFieldAttribute(0x509903C1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_509903C1;

        [STUFieldAttribute(0x6FA6AE0D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_6FA6AE0D;

        [STUFieldAttribute(0x60C7A1E1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_60C7A1E1;

        [STUFieldAttribute(0x3A205C9C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_3A205C9C;

        [STUFieldAttribute(0x0403A33B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_0403A33B;

        [STUFieldAttribute(0xDA1D5BA0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_DA1D5BA0;

        [STUFieldAttribute(0x00C4E092, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_00ABC9FF m_00C4E092;
    }
}
