// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA1AAB8C4)]
    public class STU_A1AAB8C4 : STUStatescriptInputPlug {
    }
}
