// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF9F748C2)]
    public class STU_F9F748C2 : STU_12ED1E44 {
        [STUFieldAttribute(0xEEF46CEE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_416D9897 m_EEF46CEE;
    }
}
