// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8E69CC3A)]
    public class STU_8E69CC3A : STUComponentInstanceData {
        [STUFieldAttribute(0x2746D7E4)]
        public teUUID m_2746D7E4;
    }
}
