// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE4ACD88D)]
    public class STU_E4ACD88D : STU_DD856C32 {
        [STUFieldAttribute(0xA83C2C26, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;

        [STUFieldAttribute(0xE9CA9B34, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E9CA9B34;
    }
}
