// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xAFBF55DA)]
    public class STU_AFBF55DA : STUConfigVarBoolBase {
    }
}
