// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1232F9A3)]
    public class STU_1232F9A3 : STUConfigVarFloatBase {
    }
}
