// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xEC2C8685)]
    public class STU_EC2C8685 : STU_FF2016B1 {
        [STUFieldAttribute(0xA3A0BDD6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A3A0BDD6;
    }
}
