// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7197C080)]
    public class STU_7197C080 : STUConfigVarNumeric {
        [STUFieldAttribute(0x01AFADB6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_01AFADB6;

        [STUFieldAttribute(0xEA70ACC2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EA70ACC2;

        [STUFieldAttribute(0x69A20070, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_69A20070;
    }
}
