// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB6336C0A)]
    public class STU_B6336C0A : STUInstance {
        [STUFieldAttribute(0x11B47C68, "m_id")]
        public teStructuredDataAssetRef<STUIdentifier> m_id;

        [STUFieldAttribute(0x07DD813E, "m_value", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_value;
    }
}
