// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x91C12AF5)]
    public class STU_91C12AF5 : STU_B9D4863D {
        [STUFieldAttribute(0xD2F882C9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D2F882C9;

        [STUFieldAttribute(0x52EDF42F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_52EDF42F;

        [STUFieldAttribute(0x6F6EB528, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6F6EB528;
    }
}
