// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFDA44752)]
    public class STU_FDA44752 : STUUXObject {
        [STUFieldAttribute(0xC0EDFA4B, "m_width")]
        public float m_width;

        [STUFieldAttribute(0xBFDEB7F1, "m_height")]
        public float m_height;
    }
}
