// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xABDBF4BA)]
    public class STU_ABDBF4BA : STUGraphNode {
        [STUFieldAttribute(0xCB2634D7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_D3FB30E2[] m_CB2634D7;
    }
}
