// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBC4D3063)]
    public class STU_BC4D3063 : STUStatescriptAction {
        [STUFieldAttribute(0x040B9C77, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_040B9C77;

        [STUFieldAttribute(0x9A9E72EC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9A9E72EC;
    }
}
