// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xAABE3901)]
    public class STU_AABE3901 : STU_81C5DE19 {
        [STUFieldAttribute(0xF891229F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_3466AA12 m_F891229F;

        [STUFieldAttribute(0xED9A28ED, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A8EFC6F0 m_ED9A28ED;

        [STUFieldAttribute(0x9556D6E4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A8EFC6F0 m_9556D6E4;

        [STUFieldAttribute(0xBDD95289, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A8EFC6F0 m_BDD95289;

        [STUFieldAttribute(0x45A7A69C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A8EFC6F0 m_45A7A69C;
    }
}
