// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x967463AB)]
    public class STU_967463AB : STU_E896B267 {
        [STUFieldAttribute(0x92D12BE6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_92D12BE6;

        [STUFieldAttribute(0xC8655030, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C8655030;
    }
}
