// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x22926252)]
    public class STU_22926252 : STUStatescriptAction {
        [STUFieldAttribute(0x67B81D25, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_67B81D25;

        [STUFieldAttribute(0xEB35D2F1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EB35D2F1;
    }
}
