// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4B3C4D04)]
    public class STU_4B3C4D04 : STU_42EB8D8B {
        [STUFieldAttribute(0x54653E9B, "m_inPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_23E2141E m_inPlug;

        [STUFieldAttribute(0x8C4782E9, "m_outPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_B631D643 m_outPlug;

        [STUFieldAttribute(0xBA53D5ED, "m_guid")]
        public ulong m_guid;

        [STUFieldAttribute(0xB156CD4B)]
        public byte m_B156CD4B;

        [STUFieldAttribute(0xE8C1F3C9)]
        public byte m_E8C1F3C9;

        [STUFieldAttribute(0x051960C5)]
        public byte m_051960C5;

        [STUFieldAttribute(0x9FC475A6)]
        public byte m_9FC475A6;
    }
}
