// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA6668E8E)]
    public class STU_A6668E8E : STU_820A411A {
        [STUFieldAttribute(0x2D3CDFA9, "m_hardPoint", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_57C7508E m_hardPoint;

        [STUFieldAttribute(0x4D2DB658, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_6B62E4AD m_4D2DB658;

        [STUFieldAttribute(0xF72DF349, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_A3ECD978 m_F72DF349;

        [STUFieldAttribute(0xE96CBDAE, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FF2A50C m_E96CBDAE;
    }
}
