// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xAD9403C3)]
    public class STU_AD9403C3 : STU_C34E05B6 {
        [STUFieldAttribute(0x847115EB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_847115EB;

        [STUFieldAttribute(0x513ECE33, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_513ECE33;

        [STUFieldAttribute(0x42873C52, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_42873C52;

        [STUFieldAttribute(0x0C1FFB29, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0C1FFB29;

        [STUFieldAttribute(0x0C56DD7E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0C56DD7E;
    }
}
