// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x05712979)]
    public class STU_05712979 : STUStatescriptAction {
        [STUFieldAttribute(0x8F1335C4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8F1335C4;
    }
}
