// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x27C6AA11)]
    public class STU_27C6AA11 : STUInstance {
        [STUFieldAttribute(0x63DEDAC0)]
        public int m_63DEDAC0;
    }
}
