// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x944A28CB)]
    public class STU_944A28CB : STU_DD856C32 {
        [STUFieldAttribute(0xF1CB3BA0, "m_text", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_text;
    }
}
