// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xECCCBE80)]
    public class STU_ECCCBE80 : STU_81C5DE19 {
        [STUFieldAttribute(0xF891229F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_E31C3EF7 m_F891229F;
    }
}
