// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7B4C8984)]
    public class STU_7B4C8984 : STUUXDependencyObject {
        [STUFieldAttribute(0xADE95629, "m_items", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_731A6E12[] m_items;
    }
}
