// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x46B2224F)]
    public class STU_46B2224F : STUStatescriptScreenVM {
        [STUFieldAttribute(0xE5CC7250)]
        public teString m_E5CC7250;
    }
}
