// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x329C3A5B)]
    public class STU_329C3A5B : STU_A2B9762B {
        [STUFieldAttribute(0x8540C5D6)]
        public teStructuredDataAssetRef<STUTexture> m_8540C5D6;

        [STUFieldAttribute(0xF8D4FCA9)]
        public teVec3 m_F8D4FCA9;

        [STUFieldAttribute(0x7483D81C)]
        public teVec3 m_7483D81C;

        [STUFieldAttribute(0x81C8D603)]
        public teVec3 m_81C8D603;

        [STUFieldAttribute(0xC3E03C7F, "m_color")]
        public teColorRGB m_color;

        [STUFieldAttribute(0xAB55CE22)]
        public float m_AB55CE22;

        [STUFieldAttribute(0x5D001AA9)]
        public float m_5D001AA9;

        [STUFieldAttribute(0x2D316450)]
        public float m_2D316450;

        [STUFieldAttribute(0x7EEEFC5B)]
        public float m_7EEEFC5B;

        [STUFieldAttribute(0x2EB1C82E)]
        public float m_2EB1C82E;

        [STUFieldAttribute(0xCEF5AD09)]
        public float m_CEF5AD09;
    }
}
