// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xCA861E44)]
    public class STU_CA861E44 : STUStatescriptState {
        [STUFieldAttribute(0xF3E612FD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F3E612FD;

        [STUFieldAttribute(0xC98661CF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C98661CF;

        [STUFieldAttribute(0x039F7BEA)]
        public byte m_039F7BEA;

        [STUFieldAttribute(0xABB82E7C)]
        public byte m_ABB82E7C;
    }
}
