// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x61540E60)]
    public class STU_61540E60 : STUInstance {
        [STUFieldAttribute(0xCA19B315)]
        public teStructuredDataAssetRef<STUIdentifier> m_CA19B315;
    }
}
