// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xED45C5E8)]
    public class STU_ED45C5E8 : STU_1361E674 {
        [STUFieldAttribute(0xB2ABF4FF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B2ABF4FF;
    }
}
