// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC14F08B3)]
    public class STU_C14F08B3 : STU_6440565A {
        [STUFieldAttribute(0xA53100D5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A53100D5;
    }
}
