// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBEB8E56B)]
    public class STU_BEB8E56B : STU_54D6A5F9 {
        [STUFieldAttribute(0xF99D9D47)]
        public ulong m_F99D9D47;

        [STUFieldAttribute(0x3206B33C)]
        public ulong m_3206B33C;
    }
}
