// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xEF47A28F)]
    public class STU_EF47A28F : STU_BBF32277 {
        [STUFieldAttribute(0x54B37DE8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_54B37DE8;

        [STUFieldAttribute(0xA3A1EE34, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A3A1EE34;

        [STUFieldAttribute(0x4F232A5C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4F232A5C;

        [STUFieldAttribute(0x51609D56, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_51609D56;

        [STUFieldAttribute(0x3A792AD8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3A792AD8;
    }
}
