// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0357A363)]
    public class STU_0357A363 : STU_A30EF84D {
        [STUFieldAttribute(0x5DC61E59, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5DC61E59;
    }
}
