// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x69D510F1)]
    public class STU_69D510F1 : STUConfigVarStringBase {
        [STUFieldAttribute(0x3CD6DC1E, "m_texture", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_texture;
    }
}
