// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0BD5EA17)]
    public class STU_0BD5EA17 : STUInstance {
        [STUFieldAttribute(0x50558D63)]
        public teStructuredDataAssetRef<ulong>[] m_50558D63;

        [STUFieldAttribute(0x7CBECA0C)]
        public teStructuredDataAssetRef<ulong>[] m_7CBECA0C;
    }
}
