// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8B2CE6D0)]
    public class STU_8B2CE6D0 : STUStatescriptAction {
    }
}
