// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4D3275B9)]
    public class STU_4D3275B9 : STU_A2B9762B {
        [STUFieldAttribute(0xDAF86B4D)]
        public teStructuredDataAssetRef<ulong> m_DAF86B4D;

        [STUFieldAttribute(0xB56D0F08, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_649B2015[] m_B56D0F08;

        [STUFieldAttribute(0x32FC48A5)]
        public short m_32FC48A5;

        [STUFieldAttribute(0xCC7736C9)]
        public byte m_CC7736C9;
    }
}
