// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x70BFB706)]
    public class STU_70BFB706 : STUInstance {
        [STUFieldAttribute(0xF97609C8)]
        public teStructuredDataAssetRef<STU_7A0B33DA> m_F97609C8;

        [STUFieldAttribute(0x9CDDC24D)]
        public float m_9CDDC24D;

        [STUFieldAttribute(0xC7E4EB10)]
        public byte m_C7E4EB10;

        [STUFieldAttribute(0xA08C6C1C)]
        public byte m_A08C6C1C;
    }
}
