// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x571BE6A9)]
    public class STU_571BE6A9 : STU_B9FE55F9 {
        [STUFieldAttribute(0xEC4CAE23, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimBlendDriverParam m_EC4CAE23;

        [STUFieldAttribute(0xDCB88361, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_15EF3A7E m_DCB88361;

        [STUFieldAttribute(0xC73B6DD4)]
        public ushort m_C73B6DD4;

        [STUFieldAttribute(0xC23720BD)]
        public byte m_C23720BD;

        [STUFieldAttribute(0x15CBDCF1)]
        public byte m_15CBDCF1;
    }
}
