// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8BF80D88)]
    public class STU_8BF80D88 : STU_8F4AD712 {
        [STUFieldAttribute(0x886C9E6E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_886C9E6E;

        [STUFieldAttribute(0x7F1035A6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7F1035A6;
    }
}
