// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD584FE3E)]
    public class STU_D584FE3E : STU_DD856C32 {
        [STUFieldAttribute(0xCD239434, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_CD239434;
    }
}
