// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x130F92A2)]
    public class STU_130F92A2 : STUUXGeometry {
        [STUFieldAttribute(0x4AB5ED94, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_C9A8A95F m_4AB5ED94;
    }
}
