// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x61481286)]
    public class STU_61481286 : STUConfigVarVecBase {
        [STUFieldAttribute(0xA83C2C26, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;

        [STUFieldAttribute(0xA90ABAAE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A90ABAAE;

        [STUFieldAttribute(0x59F52E71)]
        public Enum_BE1AE4E9 m_59F52E71;
    }
}
