// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7B91CA1D)]
    public class STU_7B91CA1D : STU_63F8336D {
        [STUFieldAttribute(0xC3E03C7F, "m_color")]
        public teStructuredDataAssetRef<STUTeamColor> m_color;

        [STUFieldAttribute(0xC6AD14D9)]
        public teStructuredDataAssetRef<STUTeamColor> m_C6AD14D9;
    }
}
