// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x61FE0F01)]
    public class STU_61FE0F01 : STUStatescriptState {
        [STUFieldAttribute(0x8A12D912, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8A12D912;

        [STUFieldAttribute(0x69603948, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_69603948;
    }
}
