// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3CE15663)]
    public class STU_3CE15663 : STUInstance {
        [STUFieldAttribute(0xED8BCE99, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_B169BD65 m_ED8BCE99;

        [STUFieldAttribute(0x1574C6B7)]
        public teStructuredDataAssetRef<STUIdentifier> m_1574C6B7;

        [STUFieldAttribute(0x9D936260, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_3F88EA3B[] m_9D936260;

        [STUFieldAttribute(0x29A39423)]
        public float m_29A39423;

        [STUFieldAttribute(0x99C5C2BA)]
        public byte m_99C5C2BA;
    }
}
