// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1869F3BD)]
    public class STU_1869F3BD : STUConfigVarStringBase {
        [STUFieldAttribute(0xAE2D8911, "m_index", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_index;
    }
}
