// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7C005F8F)]
    public class STU_7C005F8F : STU_1482DDBB {
        [STUFieldAttribute(0xA83C2C26, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;

        [STUFieldAttribute(0x82B6345B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_82B6345B;
    }
}
