// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x6752C47D)]
    public class STU_6752C47D : STUEntityComponent {
    }
}
