// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFD1A6CCF)]
    public class STU_FD1A6CCF : STUInstance {
        [STUFieldAttribute(0x6B6D58D9)]
        public teStructuredDataAssetRef<STUEntityDefinition>[] m_6B6D58D9;

        [STUFieldAttribute(0x2F19E428)]
        public teStructuredDataAssetRef<STUEntityDefinition> m_2F19E428;

        [STUFieldAttribute(0x302AE799)]
        public teStructuredDataAssetRef<STUEntityDefinition> m_302AE799;

        [STUFieldAttribute(0xB48F1D22, "m_name")]
        public teString m_name;

        [STUFieldAttribute(0xEFA76E5F)]
        public byte m_EFA76E5F;
    }
}
