// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC5DD163C)]
    public class STU_C5DD163C : STUStatescriptAction {
        [STUFieldAttribute(0xA4258A77, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A4258A77;
    }
}
