// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x697B4060)]
    public class STU_697B4060 : STUInstance {
        [STUFieldAttribute(0x3D83C363, "m_assets", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_76052201[] m_assets;
    }
}
