// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBC84D288)]
    public class STU_BC84D288 : STU_DD856C32 {
        [STUFieldAttribute(0x07DD813E, "m_value", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_value;

        [STUFieldAttribute(0x2F709539, "m_key")]
        public Enum_C3BB057D m_key;
    }
}
