// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7A1151E6)]
    public class STU_7A1151E6 : STUStatescriptState {
    }
}
