// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9AB01A35)]
    public class STU_9AB01A35 : STUComponentInstanceData {
        [STUFieldAttribute(0x2746D7E4)]
        public teUUID m_2746D7E4;

        [STUFieldAttribute(0xA92070A2)]
        public Enum_06FA22BB m_A92070A2;

        [STUFieldAttribute(0x30CD4137)]
        public float m_30CD4137;

        [STUFieldAttribute(0x4579B961)]
        public float m_4579B961;

        [STUFieldAttribute(0x2C0246C1)]
        public float m_2C0246C1;

        [STUFieldAttribute(0xA3B3682C)]
        public byte m_A3B3682C;
    }
}
