// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC261FEA5)]
    public class STU_C261FEA5 : STUEntityComponent {
        [STUFieldAttribute(0xF69D3693, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_8DEFF143[] m_F69D3693;
    }
}
