// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x40E05F6B)]
    public class STU_40E05F6B : STUStatescriptState {
        [STUFieldAttribute(0x401F5484, "m_stimulus", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_stimulus;

        [STUFieldAttribute(0xE3798C00, "m_targets", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_targets;

        [STUFieldAttribute(0x8C8C5285, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8C8C5285;

        [STUFieldAttribute(0x297E0B63, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_297E0B63;

        [STUFieldAttribute(0xA732F9A2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A732F9A2;

        [STUFieldAttribute(0xB0263D2D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B0263D2D;

        [STUFieldAttribute(0xE0E02BD4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E0E02BD4;

        [STUFieldAttribute(0xE2990DDB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E2990DDB;

        [STUFieldAttribute(0xFC1DE541, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FC1DE541;

        [STUFieldAttribute(0xCC3687DF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_CC3687DF;

        [STUFieldAttribute(0x8D6962EC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8D6962EC;

        [STUFieldAttribute(0x7CAED42E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7CAED42E;

        [STUFieldAttribute(0x73F1803C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_73F1803C;

        [STUFieldAttribute(0xFC2F7AAA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_FC2F7AAA;

        [STUFieldAttribute(0x0687866A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_0687866A;

        [STUFieldAttribute(0xA0B58111, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;

        [STUFieldAttribute(0xF96FC964, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_F96FC964;

        [STUFieldAttribute(0xCB8B94CE)]
        public Enum_D2BF23BC m_CB8B94CE;
    }
}
