// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x13D35171)]
    public class STU_13D35171 : STUInstance {
        [STUFieldAttribute(0xF92402E9, "m_answer", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_answer;

        [STUFieldAttribute(0x5A6D4FBD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5A6D4FBD;
    }
}
