// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF632355B)]
    public class STU_F632355B : STU_2F6BD485 {
        [STUFieldAttribute(0x37429C94, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimBlendTimeParams m_37429C94;

        [STUFieldAttribute(0xA5443C92, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_5BF8DA7A m_A5443C92;
    }
}
