// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x84906368)]
    public class STU_84906368 : STUConfigVarBoolBase {
    }
}
