// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF4CBDCA9)]
    public class STU_F4CBDCA9 : STU_DD4307AF {
        [STUFieldAttribute(0x871FDCF2)]
        public teStructuredDataAssetRef<STU_419A52CA> m_871FDCF2;

        [STUFieldAttribute(0x6A9D3ACB)]
        public byte m_6A9D3ACB;
    }
}
