// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x67028732)]
    public class STU_67028732 : STU_ABA73F86 {
        [STUFieldAttribute(0xC1903771, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C1903771;

        [STUFieldAttribute(0x401E2D84, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarFilter m_401E2D84;

        [STUFieldAttribute(0xCC71479A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarFilter m_CC71479A;

        [STUFieldAttribute(0x1CB2F4E8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1CB2F4E8;

        [STUFieldAttribute(0x97CD8E69, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_97CD8E69;
    }
}
