// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x84515D93)]
    public class STU_84515D93 : STUUnlock {
        [STUFieldAttribute(0x1B25AB90, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5C713BD4 m_1B25AB90;

        [STUFieldAttribute(0xABFBD552, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_5C713BD4 m_ABFBD552;
    }
}
