// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x11A69B4F)]
    public class STU_11A69B4F : STUInstance {
        [STUFieldAttribute(0x279083B5, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_F76CB28A[] m_279083B5;

        [STUFieldAttribute(0xB48F1D22, "m_name")]
        public teString m_name;

        [STUFieldAttribute(0x80DFC3DA)]
        public byte m_80DFC3DA;

        [STUFieldAttribute(0x00810DDC)]
        public byte m_00810DDC;
    }
}
