// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x13E59842)]
    public class STU_13E59842 : STUInstance {
        [STUFieldAttribute(0xC0A83121)]
        public teStructuredDataAssetRef<STU_F6CCDAFC> m_C0A83121;

        [STUFieldAttribute(0x291F2404)]
        public long m_291F2404;
    }
}
