// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD1F94CCE)]
    public class STU_D1F94CCE : STUStatescriptAction {
    }
}
