// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x345F2405)]
    public class STU_345F2405 : STUConfigVarResource {
    }
}
