// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8CACF759)]
    public class STU_8CACF759 : STU_1482DDBB {
        [STUFieldAttribute(0x39A13B37, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_39A13B37;
    }
}
