// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDF7C7C63)]
    public class STU_DF7C7C63 : STU_EFB08E43 {
        [STUFieldAttribute(0xA83C2C26, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;

        [STUFieldAttribute(0xF24E4110, "m_slot", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_slot;
    }
}
