// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE62A1A33)]
    public class STU_E62A1A33 : STU_A2B9762B {
        [STUFieldAttribute(0xF8D4FCA9)]
        public teVec3 m_F8D4FCA9;
    }
}
