// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x928C04A2)]
    public class STU_928C04A2 : STU_A323F0F5 {
        [STUFieldAttribute(0xD13035F5)]
        public teStructuredDataAssetRef<STUDataFlow> m_D13035F5;

        [STUFieldAttribute(0x9FF7B93D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D9F6F922[] m_9FF7B93D;
    }
}
