// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE2D9CF85)]
    public class STU_E2D9CF85 : STU_9A40D4BB {
        [STUFieldAttribute(0x2F709539, "m_key", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_key;
    }
}
