// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x90637F41)]
    public class STU_90637F41 : STUGenericSettings_Base {
        [STUFieldAttribute(0xDB1A37E3)]
        public teStructuredDataHashMap<STU_DF2ABAA7> m_DB1A37E3;
    }
}
