// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x6891577D)]
    public class STU_6891577D : STU_15043B61 {
        [STUFieldAttribute(0xBD44C2AA, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_004C8CC7 m_BD44C2AA;
    }
}
