// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB31A0B40)]
    public class STU_B31A0B40 : STUInstance {
        [STUFieldAttribute(0xF81F4386, "m_startTime")]
        public teStructuredDataDateAndTime m_startTime;

        [STUFieldAttribute(0xFBEBAD6F, "m_endTime")]
        public teStructuredDataDateAndTime m_endTime;
    }
}
