// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1F15E24D)]
    public class STU_1F15E24D : STU_81C5DE19 {
        [STUFieldAttribute(0xF891229F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_F7618109 m_F891229F;
    }
}
