// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x406F6657)]
    public class STU_406F6657 : STUUXObject {
        [STUFieldAttribute(0xDCB339F4)]
        public float m_DCB339F4;

        [STUFieldAttribute(0xABB40962)]
        public float m_ABB40962;

        [STUFieldAttribute(0x32BD58D8)]
        public float m_32BD58D8;
    }
}
