// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8373AC4C)]
    public class STU_8373AC4C : STU_6440565A {
        [STUFieldAttribute(0xA53100D5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A53100D5;
    }
}
