// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8ED74BC8)]
    public class STU_8ED74BC8 : STU_81C5DE19 {
        [STUFieldAttribute(0xF891229F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_4A5C847B m_F891229F;
    }
}
