// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x380341C0)]
    public class STU_380341C0 : STUStatescriptAction {
        [STUFieldAttribute(0x6A928816)]
        public teString m_6A928816;
    }
}
