// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x42623635)]
    public class STU_42623635 : STUStatescriptState {
    }
}
