// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x67B43929)]
    public class STU_67B43929 : STUInstance {
        [STUFieldAttribute(0x89C0D8DA, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_4294267F[] m_89C0D8DA;
    }
}
