// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1C293E8D)]
    public class STU_1C293E8D : STUConfigVarVecBase {
    }
}
