// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3FC8568C)]
    public class STU_3FC8568C : STUInstance {
        [STUFieldAttribute(0xA85E1803, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_41999460[] m_A85E1803;

        [STUFieldAttribute(0xF72DF349)]
        public Enum_BDE32585 m_F72DF349;
    }
}
