// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3716E1D4)]
    public class STU_3716E1D4 : STUStatescriptState {
        [STUFieldAttribute(0x69A20070, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_69A20070;
    }
}
