// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1145C42E)]
    public class STU_1145C42E : STUStatescriptWeaponVolleyLaunch {
        [STUFieldAttribute(0x3C5E3E62, "m_spread", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_spread;

        [STUFieldAttribute(0xA2A9890A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A2A9890A;
    }
}
