// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0625A5AF)]
    public class STU_0625A5AF : STUConfigVarBoolBase {
    }
}
