// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8B4B379C)]
    public class STU_8B4B379C : STU_F7B7BBA0 {
        [STUFieldAttribute(0x84D349FB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_84D349FB;

        [STUFieldAttribute(0x865F3D01, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_865F3D01;

        [STUFieldAttribute(0x7183E9CE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7183E9CE;

        [STUFieldAttribute(0x59276C98, "m_destinationEntity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_destinationEntity;

        [STUFieldAttribute(0x07BA97ED, "m_destinationBone", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_destinationBone;

        [STUFieldAttribute(0x1866524C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1866524C;

        [STUFieldAttribute(0x3BC31C57, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3BC31C57;

        [STUFieldAttribute(0x5BEFF040, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5BEFF040;

        [STUFieldAttribute(0x9A855ABA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9A855ABA;

        [STUFieldAttribute(0x189141AE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_189141AE;

        [STUFieldAttribute(0xA57012D4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A57012D4;

        [STUFieldAttribute(0x79181D52, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_79181D52;

        [STUFieldAttribute(0xFAEBCE16, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FAEBCE16;

        [STUFieldAttribute(0x6A79BD98, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6A79BD98;

        [STUFieldAttribute(0x725EB364, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_725EB364;

        [STUFieldAttribute(0x5DA62D02, "m_onAbortPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onAbortPlug;

        [STUFieldAttribute(0xA0B58111, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;

        [STUFieldAttribute(0xB060F688)]
        public byte m_B060F688;
    }
}
