// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x137A3D5B)]
    public class STU_137A3D5B : STUInstance {
        [STUFieldAttribute(0xB48F1D22, "m_name")]
        public teString m_name;

        [STUFieldAttribute(0xA3D74E35, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_FB2A36D7[] m_A3D74E35;
    }
}
