// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB2795D4D)]
    public class STU_B2795D4D : STU_96788737 {
        [STUFieldAttribute(0x13313B24)]
        public teStructuredDataAssetRef<STU_9CADF2EC> m_13313B24;
    }
}
