// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC25281C3)]
    public class STU_C25281C3 : STUInstance {
        [STUFieldAttribute(0xCA7E6EDC, "m_description")]
        public teStructuredDataAssetRef<ulong> m_description;

        [STUFieldAttribute(0x91590545)]
        public teStructuredDataAssetRef<STU_6BE90C5C>[] m_91590545;

        [STUFieldAttribute(0x69A20070)]
        public float m_69A20070;

        [STUFieldAttribute(0x5C712614)]
        public float m_5C712614;
    }
}
