// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD040C3EF)]
    public class STU_D040C3EF : STUStatescriptState {
        [STUFieldAttribute(0x4A5CA514, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4A5CA514;
    }
}
