// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE288AB38)]
    public class STU_E288AB38 : STUConfigVarBoolBase {
    }
}
