// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5D81EF36)]
    public class STU_5D81EF36 : STU_A30EF84D {
        [STUFieldAttribute(0x216EA6DA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_216EA6DA;
    }
}
