// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xEAB7C819)]
    public class STU_EAB7C819 : STUConfigVarBoolBase {
        [STUFieldAttribute(0x46D6B412, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_46D6B412;
    }
}
