// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x024CE7CA)]
    public class STU_024CE7CA : STU_99C76CCD {
        [STUFieldAttribute(0x72E2921B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_72E2921B;

        [STUFieldAttribute(0xEE7E9891, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EE7E9891;

        [STUFieldAttribute(0x1E78E8A7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1E78E8A7;

        [STUFieldAttribute(0x11672F8B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_11672F8B;

        [STUFieldAttribute(0xBE8A2637, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BE8A2637;

        [STUFieldAttribute(0xBCAD9235, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BCAD9235;

        [STUFieldAttribute(0x396895EF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_396895EF;
    }
}
