// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x07AF5658)]
    public class STU_07AF5658 : STUConfigVarBoolBase {
    }
}
