// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE3C6AB71)]
    public class STU_E3C6AB71 : STUInstance {
        [STUFieldAttribute(0xF60AA143, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F60AA143;

        [STUFieldAttribute(0xBAA3A65F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BAA3A65F;
    }
}
