// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFC16FF45)]
    public class STU_FC16FF45 : STU_BCD004B5 {
        [STUFieldAttribute(0xB2F9D222, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B2F9D222;

        [STUFieldAttribute(0x7CCD8B4B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7CCD8B4B;
    }
}
