// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x534CE6BE)]
    public class STU_534CE6BE : STU_C87931B7 {
        [STUFieldAttribute(0x0C5B73B0, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_EF3E0E4C[] m_0C5B73B0;
    }
}
