// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5BAB8FC4)]
    public class STU_5BAB8FC4 : STUStatescriptAction {
    }
}
