// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBCD0088A)]
    public class STU_BCD0088A : STUStatescriptInputPlug {
    }
}
