// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDEE097B9)]
    public class STU_DEE097B9 : STU_1482DDBB {
        [STUFieldAttribute(0x00D49978, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_00D49978;
    }
}
