// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x61A6A17A)]
    public class STU_61A6A17A : STU_73F42778 {
        [STUFieldAttribute(0x15BE7741, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_3426C7F2 m_15BE7741;
    }
}
