// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x78863ACE)]
    public class STU_78863ACE : STUStatescriptAction {
        [STUFieldAttribute(0xA236519D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_A236519D;
    }
}
