// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBBC763F9)]
    public class STU_BBC763F9 : STUStatescriptStateUXPresenter {
        [STUFieldAttribute(0xEB4F2408, "m_gamemode", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_gamemode;

        [STUFieldAttribute(0x2C54AEAF, "m_category")]
        public Enum_F2F62E3D m_category;
    }
}
