// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xEB1C779B)]
    public class STU_EB1C779B : STU_C7C085F6 {
        [STUFieldAttribute(0x172CAE5E)]
        public teStructuredDataAssetRef<STUAnimation> m_172CAE5E;

        [STUFieldAttribute(0x6BAAD44E)]
        public teStructuredDataAssetRef<STUAnimation> m_6BAAD44E;

        [STUFieldAttribute(0xEC4CAE23)]
        public teStructuredDataAssetRef<STUDataFlow> m_EC4CAE23;

        [STUFieldAttribute(0x0CF1B802, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigWeightSet m_0CF1B802;

        [STUFieldAttribute(0x5620DA50, "m_globalWeightMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalWeightMultipliers m_globalWeightMultipliers;

        [STUFieldAttribute(0xEC42051A, "m_userWeights", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimUserWeights m_userWeights;

        [STUFieldAttribute(0xF0E4656D, "m_globalLayerMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalLayerMultipliers m_globalLayerMultipliers;

        [STUFieldAttribute(0xABF34EEF)]
        public float m_ABF34EEF;

        [STUFieldAttribute(0xE8502460)]
        public float m_E8502460;

        [STUFieldAttribute(0x83CE3EB5)]
        public float m_83CE3EB5;
    }
}
