// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x801A7230)]
    public class STU_801A7230 : STU_B719E73A {
        [STUFieldAttribute(0x056D3E39, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_CACA2D30 m_056D3E39;
    }
}
