// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9D8E0252)]
    public class STU_9D8E0252 : STU_1413B6A1 {
        [STUFieldAttribute(0xF291BE20, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_F291BE20;

        [STUFieldAttribute(0xA1656586, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A1656586;
    }
}
