// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x2C671D7C)]
    public class STU_2C671D7C : STU_502E0CB7 {
        [STUFieldAttribute(0x84A857B0)]
        public byte[] m_84A857B0;

        [STUFieldAttribute(0xBA53D5ED, "m_guid")]
        public ulong m_guid;

        [STUFieldAttribute(0x05129A94)]
        public ulong m_05129A94;

        [STUFieldAttribute(0x7EEFB57A, "m_flags")]
        public uint m_flags;
    }
}
