// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA95E4B99)]
    public class STU_A95E4B99 : STUCriteria {
        [STUFieldAttribute(0x7D88A63A, "m_gender")]
        public Enum_0C014B4A m_gender;
    }
}
