// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB13E2A22)]
    public class STU_B13E2A22 : STUInstance {
        [STUFieldAttribute(0xAA76FAD1)]
        public teStructuredDataAssetRef<ulong> m_AA76FAD1;

        [STUFieldAttribute(0x4D2DB658)]
        public teStructuredDataAssetRef<STU_9CADF2EC> m_4D2DB658;
    }
}
