// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD30D15AC)]
    public class STU_D30D15AC : STUStatescriptStateUXPresenter {
        [STUFieldAttribute(0x37AB13D3, "m_hero", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_hero;
    }
}
