// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8A359690)]
    public class STU_8A359690 : STUStatescriptState {
        [STUFieldAttribute(0x9AC007B3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9AC007B3;

        [STUFieldAttribute(0x56B8547E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_56B8547E;

        [STUFieldAttribute(0x4A5CA514, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4A5CA514;

        [STUFieldAttribute(0xDA7B9B57, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_DA7B9B57;

        [STUFieldAttribute(0xD6CB434B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D6CB434B;

        [STUFieldAttribute(0x1AA0C296, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1AA0C296;

        [STUFieldAttribute(0x80D013AF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_80D013AF;

        [STUFieldAttribute(0x1C8E776A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_1C8E776A;

        [STUFieldAttribute(0x679E9939, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_679E9939;

        [STUFieldAttribute(0x9102D364)]
        public Enum_DEB9DF3B m_9102D364;
    }
}
