// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x50C2C41D)]
    public class STU_50C2C41D : STUInstance {
        [STUFieldAttribute(0xB48F1D22, "m_name")]
        public teStructuredDataAssetRef<ulong> m_name;

        [STUFieldAttribute(0x977EE055)]
        public teStructuredDataAssetRef<ulong>[] m_977EE055;
    }
}
