// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF5F28D6A)]
    public class STU_F5F28D6A : STU_24E99C78 {
        [STUFieldAttribute(0xADE95629, "m_items", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_items;
    }
}
