// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4EFF450F)]
    public class STU_4EFF450F : STUInstance {
        [STUFieldAttribute(0xB48F1D22, "m_name")]
        public teString m_name;

        [STUFieldAttribute(0x888BCD8B)]
        public teStructuredDataAssetRef<STUBoneLabel> m_888BCD8B;

        [STUFieldAttribute(0xEDF0511C)]
        public ulong m_EDF0511C;
    }
}
