// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x760F33BB)]
    public class STU_760F33BB : STUConfigVar {
        [STUFieldAttribute(0x814F8EC3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_814F8EC3;

        [STUFieldAttribute(0xA53100D5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A53100D5;
    }
}
