// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x62FE9160)]
    public class STU_62FE9160 : STUConfigVarNumeric {
        [STUFieldAttribute(0xA8D12F28, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A8D12F28;
    }
}
