// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4638D64C)]
    public class STU_4638D64C : STU_E5863169 {
        [STUFieldAttribute(0x9B7A63EA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9B7A63EA;

        [STUFieldAttribute(0xCFEC5F76)]
        public Enum_46B10D78 m_CFEC5F76;
    }
}
