// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x18ADE228)]
    public class STU_18ADE228 : STU_28F49095 {
        [STUFieldAttribute(0x90119470, "m_enum")]
        public teStructuredDataAssetRef<ulong> m_enum;
    }
}
