// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDB456584)]
    public class STU_DB456584 : STU_48A39D9B {
        [STUFieldAttribute(0xE1D625B8)]
        public teStructuredDataAssetRef<ulong> m_E1D625B8;
    }
}
