// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDCD6F8D3)]
    public class STU_DCD6F8D3 : STU_C7C085F6 {
        [STUFieldAttribute(0x24C2CB2F)]
        public teStructuredDataAssetRef<STUAnimation> m_24C2CB2F;

        [STUFieldAttribute(0x0EFACA16)]
        public teStructuredDataAssetRef<STUAnimation> m_0EFACA16;

        [STUFieldAttribute(0x26DCA69D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_F92E0197 m_26DCA69D;

        [STUFieldAttribute(0xEC42051A, "m_userWeights", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimUserWeights m_userWeights;

        [STUFieldAttribute(0xF0E4656D, "m_globalLayerMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalLayerMultipliers m_globalLayerMultipliers;

        [STUFieldAttribute(0xE56B739B)]
        public float m_E56B739B;

        [STUFieldAttribute(0xE8502460)]
        public float m_E8502460;

        [STUFieldAttribute(0x83CE3EB5)]
        public float m_83CE3EB5;

        [STUFieldAttribute(0x5620DA50, "m_globalWeightMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_7C094509 m_globalWeightMultipliers;
    }
}
