// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD315B031)]
    public class STU_D315B031 : STUGenericSettings_Base {
        [STUFieldAttribute(0xB51A9985)]
        public float m_B51A9985;

        [STUFieldAttribute(0xD9AE365E)]
        public float m_D9AE365E;

        [STUFieldAttribute(0x56BC9D58)]
        public float m_56BC9D58;

        [STUFieldAttribute(0xA0AA21FF)]
        public float m_A0AA21FF;
    }
}
