// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF76CB28A)]
    public class STU_F76CB28A : STUInstance {
        [STUFieldAttribute(0xB48F1D22, "m_name")]
        public teString m_name;

        [STUFieldAttribute(0x80DFC3DA)]
        public byte m_80DFC3DA;

        [STUFieldAttribute(0xEBE3BB41)]
        public byte m_EBE3BB41;
    }
}
