// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x2376C502)]
    public class STU_2376C502 : STUInstance {
        [STUFieldAttribute(0x24482B14)]
        public teStructuredDataAssetRef<ulong>[] m_24482B14;

        [STUFieldAttribute(0xA162176B)]
        public teStructuredDataAssetRef<ulong>[] m_A162176B;

        [STUFieldAttribute(0x1B15A92D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D0C29598[] m_1B15A92D;
    }
}
