// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0589C835)]
    public class STU_0589C835 : STU_D74E5E25 {
        [STUFieldAttribute(0xAB12250C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_AB12250C;

        [STUFieldAttribute(0xB35CCFBE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B35CCFBE;

        [STUFieldAttribute(0xD9F68719, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarFilter m_D9F68719;
    }
}
