// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xAA6ADB38)]
    public class STU_AA6ADB38 : STUStatescriptState {
        [STUFieldAttribute(0x2E72F700, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2E72F700;
    }
}
