// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC1AB3E05)]
    public class STU_C1AB3E05 : STU_C7C085F6 {
        [STUFieldAttribute(0x2A399D82)]
        public teStructuredDataAssetRef<ulong> m_2A399D82;

        [STUFieldAttribute(0x37EE887D)]
        public teStructuredDataAssetRef<ulong> m_37EE887D;

        [STUFieldAttribute(0x4C66BDF0)]
        public teStructuredDataAssetRef<ulong> m_4C66BDF0;

        [STUFieldAttribute(0xD90E77D6)]
        public teStructuredDataAssetRef<ulong> m_D90E77D6;

        [STUFieldAttribute(0xE0F63426)]
        public teStructuredDataAssetRef<ulong> m_E0F63426;

        [STUFieldAttribute(0xD32FA452, "m_categoryDataFlow")]
        public teStructuredDataAssetRef<ulong> m_categoryDataFlow;

        [STUFieldAttribute(0x9A94649A)]
        public teStructuredDataAssetRef<ulong> m_9A94649A;

        [STUFieldAttribute(0xEC42051A, "m_userWeights", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimUserWeights m_userWeights;

        [STUFieldAttribute(0xF0E4656D, "m_globalLayerMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalLayerMultipliers m_globalLayerMultipliers;

        [STUFieldAttribute(0x25E600E5)]
        public float m_25E600E5;

        [STUFieldAttribute(0x85018E4C)]
        public float m_85018E4C;

        [STUFieldAttribute(0xD4961B1F)]
        public float m_D4961B1F;

        [STUFieldAttribute(0x83CE3EB5)]
        public float m_83CE3EB5;
    }
}
