// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x6D4B3836)]
    public class STU_6D4B3836 : STUConfigVarBoolBase {
    }
}
