// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x221B83D5)]
    public class STU_221B83D5 : STUInstance {
        [STUFieldAttribute(0xA31770AF, "m_parameter")]
        public teStructuredDataAssetRef<STUSoundParameter> m_parameter;

        [STUFieldAttribute(0xBA891264, "m_dataFlow")]
        public teStructuredDataAssetRef<STUDataFlow> m_dataFlow;

        [STUFieldAttribute(0x9DF46DB2)]
        public byte m_9DF46DB2;

        [STUFieldAttribute(0x7B670420)]
        public byte m_7B670420;

        [STUFieldAttribute(0x1F3357A2)]
        public byte m_1F3357A2;
    }
}
