// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xAE2F63FC)]
    public class STU_AE2F63FC : STU_A3C7077A {
        [STUFieldAttribute(0xCDBFC5EC)]
        public teStructuredDataAssetRef<ulong> m_CDBFC5EC;

        [STUFieldAttribute(0x6EE70996)]
        public teStructuredDataAssetRef<ulong> m_6EE70996;

        [STUFieldAttribute(0x09E32A58)]
        public teStructuredDataAssetRef<ulong> m_09E32A58;

        [STUFieldAttribute(0xA665A5E4)]
        public teStructuredDataAssetRef<ulong> m_A665A5E4;

        [STUFieldAttribute(0xB999DDE2)]
        public teStructuredDataAssetRef<ulong> m_B999DDE2;

        [STUFieldAttribute(0x0F10EA0D)]
        public teVec2 m_0F10EA0D;

        [STUFieldAttribute(0x220E06E7)]
        public teVec2 m_220E06E7;

        [STUFieldAttribute(0xA05C4AB0)]
        public teVec2 m_A05C4AB0;

        [STUFieldAttribute(0xD7D21151)]
        public byte m_D7D21151;

        [STUFieldAttribute(0x61B6514D)]
        public byte m_61B6514D;

        [STUFieldAttribute(0x9710D80F)]
        public byte m_9710D80F;
    }
}
