// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xED306913)]
    public class STU_ED306913 : STUStatescriptState {
        [STUFieldAttribute(0x599AB8D7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_599AB8D7;

        [STUFieldAttribute(0xB4FC39B6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B4FC39B6;

        [STUFieldAttribute(0xFCC616FC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FCC616FC;

        [STUFieldAttribute(0x0B1FCF3D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0B1FCF3D;

        [STUFieldAttribute(0xCBC2605E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_8644CE0D m_CBC2605E;

        [STUFieldAttribute(0x2624BE5A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_2624BE5A;
    }
}
