// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x013C5A8D)]
    public class STU_013C5A8D : STUConfigVarBoolBase {
    }
}
