// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5ACD7C67, "STUAnimTriangulationMap")]
    public class STUAnimTriangulationMap : STUInstance {
        [STUFieldAttribute(0x0D50490E, "m_triangles", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimTriangulationMap_Triangle[] m_triangles;

        [STUFieldAttribute(0xB853170A)]
        public teVec2 m_B853170A;

        [STUFieldAttribute(0x18A188D2)]
        public teVec2 m_18A188D2;
    }
}
