// Generated by TankLibHelper
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0xC8B1D2D7, "STUAnimNode_AnimationPose2d")]
    public class STUAnimNode_AnimationPose2d : STUAnimNode_Base
    {
        [STUField(0xEB391735, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimBlendDriverParam m_EB391735;
        
        [STUField(0xE5E309D5, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimBlendDriverParam m_E5E309D5;
        
        [STUField(0x3F5B86A4, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_215BE8F3 m_animation;
        
        [STUField(0xA3081C7F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_15EF3A7E m_A3081C7F;
        
        [STUField(0x73038249, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_15EF3A7E m_73038249;
        
        [STUField(0xC14EEC71, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimNode_AnimationTrackOverride[] m_animTrackOverrides;
        
        [STUField(0x29AFF063, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_5861C542 m_29AFF063;
        
        [STUField(0xB774CFA6)]
        public Enum_9250F4C2 m_B774CFA6;
    }
}
