// Generated by TankLibHelper
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x978A87DE, 160)]
    public class STUAnimGameData_PoseData : STUInstance
    {
        [STUField(0x44B8E377, 0)] // size: 16
        public teVec3A m_44B8E377;

        [STUField(0x0B5E9CF6, 16, ReaderType = typeof(InlineInstanceFieldReader))] // size: 48
        public STU_7C02B6CA m_0B5E9CF6;

        [STUField(0x03E0A520, 64)] // size: 16
        public teVec3A[] m_poseDataVecs;

        [STUField(0x678CFBB8, 80)] // size: 16
        public ushort[] m_678CFBB8;

        [STUField(0xD65E1B08, 96, ReaderType = typeof(InlineInstanceFieldReader))] // size: 16
        public STUAnimGameData_GeoSetFlags[] m_geoSetFlags;

        [STUField(0x699307AB, 112)] // size: 16
        public float[] m_699307AB;

        [STUField(0x7B071C78, 128)] // size: 16
        public float[] m_7B071C78;

        [STUField(0xDB11C2C0, 144)] // size: 4
        public uint m_animationID;

        [STUField(0x41AB2FCB, 148)] // size: 4
        public uint m_41AB2FCB;

        [STUField(0x7EEFB57A, 152)] // size: 2
        public ushort m_flags;

        [STUField(0xAE2D8911, 154)] // size: 2
        public ushort m_index;

        [STUField(0x3016B9A1, 156)] // size: 2
        public ushort m_3016B9A1;

        [STUField(0xC1B611DF, 158)] // size: 2
        public ushort m_C1B611DF;
    }
}
