// Generated by TankLibHelper
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x0519019F, "STUAIWeaponFireControlInfo")]
    public class STUAIWeaponFireControlInfo : STUInstance
    {
        [STUField(0xF2810377)]
        public teStructuredDataAssetRef<STUIdentifier> m_F2810377;
        
        [STUField(0xC3657821)]
        public teStructuredDataAssetRef<STUHardPoint> m_C3657821;
        
        [STUField(0x4F5E7D4C)]
        public STULogicalButton m_4F5E7D4C = (STULogicalButton)0xFFFFFFFF;
        
        [STUField(0xED6D601D)]
        public uint m_ED6D601D;
        
        [STUField(0xA60150E2)]
        public uint m_A60150E2;
    }
}
