// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x391AC5F1, "STUAnimGameData_Base")]
    public class STUAnimGameData_Base : STUInstance {
    }
}
