// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x20CA83FA, "STUAITacticalMetaData")]
    public class STUAITacticalMetaData : STUInstance {
        [STUFieldAttribute(0x1EBBD451, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_6BEFADDB[] m_1EBBD451;
    }
}
