// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0xF34A7244, 632)]
    public class STUAnimNode_BlendPartition : STUAnimNode_Base
    {
        [STUField(0x57C51236, 40, ReaderType = typeof(InlineInstanceFieldReader))] // size: 248
        public STUAnimBlendDriverParam m_57C51236;

        [STUField(0xEDDE8B55, 288, ReaderType = typeof(InlineInstanceFieldReader))] // size: 56
        public STU_3426C7F2 m_EDDE8B55;

        [STUField(0xA1946787, 344, ReaderType = typeof(InlineInstanceFieldReader))] // size: 104
        public STUAnimBlendTimeParams m_A1946787;

        [STUField(0xD61E9A22, 448, ReaderType = typeof(InlineInstanceFieldReader))] // size: 32
        public STU_CCC326B7 m_D61E9A22;

        [STUField(0x98B05B42, 480, ReaderType = typeof(InlineInstanceFieldReader))] // size: 32
        public STU_CCC326B7 m_98B05B42;

        [STUField(0x226537CB, 512, ReaderType = typeof(InlineInstanceFieldReader))] // size: 24
        public STU_ABD8FE73 m_226537CB;

        [STUField(0x1B74A4CB, 536, ReaderType = typeof(InlineInstanceFieldReader))] // size: 24
        public STU_15EF3A7E m_1B74A4CB;

        [STUField(0x3C82DF27, 560, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 16
        public STU_629D3B64[] m_3C82DF27;

        [STUField(0x78E7248F, 576, ReaderType = typeof(InlineInstanceFieldReader))] // size: 16
        public STUAnimNode_BlendPartition_ExtraPartitionBoneItem[] m_78E7248F;

        [STUField(0x826E408F, 592, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STU_2F6BD485 m_826E408F;

        [STUField(0x04FE49C9, 600, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STU_8C127DE2 m_04FE49C9;

        [STUField(0x0857723F, 608, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STU_5861C542 m_0857723F;

        [STUField(0xCA1600A0, 616, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STU_5861C542 m_CA1600A0;

        [STUField(0xBA663469, 624)] // size: 1
        public byte m_BA663469;
    }
}
