// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0xC0F7EA53, 256)]
    public class STUAnimNode_Random : STUAnimNode_TransitionToChildBase
    {
        [STUField(0x6E125643, 176, ReaderType = typeof(InlineInstanceFieldReader))] // size: 32
        public STU_25B808BD m_6E125643;

        [STUField(0xDB5FF4D1, 208, ReaderType = typeof(InlineInstanceFieldReader))] // size: 24
        public STU_15EF3A7E m_DB5FF4D1;

        [STUField(0x134EE5BB, 232, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 16
        public STU_597F8A0B[] m_children;

        [STUField(0x27F2122D, 248)] // size: 1
        public byte m_27F2122D;
    }
}
