// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x978A87DE, "STUAnimGameData_PoseData")]
    public class STUAnimGameData_PoseData : STUInstance {
        [STUFieldAttribute(0x44B8E377)]
        public teVec3A m_44B8E377;

        [STUFieldAttribute(0x03E0A520, "m_poseDataVecs")]
        public teVec3A[] m_poseDataVecs;

        [STUFieldAttribute(0xD65E1B08, "m_geoSetFlags", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGameData_GeoSetFlags[] m_geoSetFlags;

        [STUFieldAttribute(0xDB11C2C0)]
        public uint m_DB11C2C0;

        [STUFieldAttribute(0xE0D91786)]
        public uint m_E0D91786;

        [STUFieldAttribute(0x7EEFB57A, "m_flags")]
        public ushort m_flags;

        [STUFieldAttribute(0xAE2D8911)]
        public ushort m_AE2D8911;

        [STUFieldAttribute(0x3016B9A1)]
        public ushort m_3016B9A1;

        [STUFieldAttribute(0xC1B611DF)]
        public ushort m_C1B611DF;
    }
}
