// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x0CC07049, "STUAchievement")]
    public class STUAchievement : STUInstance
    {
        [STUField(0xB48F1D22)]
        public teStructuredDataAssetRef<ulong> m_name;
        
        [STUField(0xCA7E6EDC)]
        public teStructuredDataAssetRef<ulong> m_description;
        
        [STUField(0x290B2ADF)]
        public teStructuredDataAssetRef<ulong> m_290B2ADF;
        
        [STUField(0x245A3F6D)]
        public teStructuredDataAssetRef<STUTexture> m_245A3F6D;
        
        [STUField(0xCF16B594, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_DD1EC1A0 m_CF16B594;
        
        [STUField(0xFD43B47A, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_40DCA4BB m_FD43B47A;
        
        [STUField(0xF5087894)]
        public teStructuredDataAssetRef<STUUnlock> m_unlock;
        
        [STUField(0x544A6A4F)]
        public teStructuredDataAssetRef<STUTexture> m_544A6A4F;
        
        [STUField(0x4E291DCC)]
        public teString m_4E291DCC;
        
        [STUField(0x50AA3D4C, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_8D3C97D8 m_50AA3D4C;
        
        [STUField(0x4FF98D41, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUCriteriaContainer m_criteria;
        
        [STUField(0xE1F5C73D)]
        public int m_E1F5C73D;
        
        [STUField(0x07DD813E)]
        public int m_value;
        
        [STUField(0x628D48CC)]
        public int m_gamerScore;
        
        [STUField(0x5351832E)]
        public int m_5351832E = -1;
    }
}
