// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x419E5D60, 120)]
    public class STUAnimationSettings : STUInstance
    {
        [STUField(0x41A3777D, 8)] // size: 16
        public teString m_41A3777D;
        
        [STUField(0xC021742D, 24)] // size: 16
        public teStructuredDataAssetRef<STU_4F4F4806> m_C021742D;
        
        [STUField(0x7FA6B71A, 40, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 16
        public STU_35BFBF20[] m_7FA6B71A;
        
        [STUField(0x7006FA69, 56, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STU_5D353F8D m_7006FA69;
        
        [STUField(0x491C8A84, 64, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUAnimBoneWeightMask m_491C8A84;
        
        [STUField(0x4ED7C887, 72, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STU_BBBFC3C9 m_4ED7C887;
        
        [STUField(0x41180910, 80)] // size: 4
        public uint m_41180910;
        
        [STUField(0xEBDCB029, 84)] // size: 4
        public uint m_EBDCB029;
        
        [STUField(0xF01E6DA2, 88)] // size: 4
        public int m_F01E6DA2;
        
        [STUField(0x11993C03, 92)] // size: 4
        public uint m_11993C03;
        
        [STUField(0xCD25B370, 96)] // size: 4
        public float m_CD25B370;
        
        [STUField(0x0258F64B, 100)] // size: 1
        public byte m_0258F64B;
        
        [STUField(0x5A50286D, 101)] // size: 1
        public byte m_5A50286D;
        
        [STUField(0x4DDA41EB, 102)] // size: 1
        public byte m_4DDA41EB;
        
        [STUField(0x59903079, 103)] // size: 1
        public byte m_59903079;
        
        [STUField(0xA794731B, 104)] // size: 1
        public byte m_A794731B;
        
        [STUField(0x85020063, 105)] // size: 1
        public byte m_85020063;
        
        [STUField(0x59DB9B44, 106)] // size: 1
        public byte m_59DB9B44;
        
        [STUField(0xB81EAB00, 107)] // size: 1
        public byte m_B81EAB00;
        
        [STUField(0x7E0DCF00, 108)] // size: 1
        public byte m_7E0DCF00;
        
        [STUField(0xF5150933, 109)] // size: 1
        public byte m_F5150933;
        
        [STUField(0xFF8E0FC4, 110)] // size: 1
        public byte m_FF8E0FC4;
        
        [STUField(0x37EE887D, 111)] // size: 1
        public byte m_37EE887D;
        
        [STUField(0x0A40CFA0, 112)] // size: 1
        public byte m_0A40CFA0;
        
        [STUField(0xEF3CD3D1, 113)] // size: 1
        public byte m_EF3CD3D1;
    }
}
