// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x949FA931, "STUAnimConfigBoneWeight_Item")]
    public class STUAnimConfigBoneWeight_Item : STUInstance
    {
        [STUField(0x9CDDC24D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_ABD8FE73 m_weight;
        
        [STUField(0xF97609C8)]
        public teStructuredDataAssetRef<STUBoneLabel> m_bone;
    }
}
