// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0xF51269FD, "STUAILevelPlacedMetaDataInstanceData")]
    public class STUAILevelPlacedMetaDataInstanceData : STUComponentInstanceData
    {
        [STUField(0x2032E7EA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUAILevelPlacedMetaData m_metaData;
    }
}
