// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x78D39627, "STUConfigVarColorBase")]
    public class STUConfigVarColorBase : STUConfigVar
    {
    }
}
