// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1D9159F2, "STUChildEntityDefinition")]
    public class STUChildEntityDefinition : STUInstance {
        [STUFieldAttribute(0x436BEFE6, "m_child")]
        public teStructuredDataAssetRef<ulong> m_child;

        [STUFieldAttribute(0x2D3CDFA9, "m_hardPoint")]
        public teStructuredDataAssetRef<ulong> m_hardPoint;

        [STUFieldAttribute(0x49F782CE)]
        public teStructuredDataAssetRef<ulong> m_49F782CE;

        [STUFieldAttribute(0x2263EA37)]
        public byte m_2263EA37;
    }
}
