// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x8BB02FF3, "STUConfigVarFilter")]
    public class STUConfigVarFilter : STUConfigVar
    {
        [STUField(0x93FA1642, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_1E8E0BC3[] m_93FA1642;
        
        [STUField(0x84065FD1)]
        public ulong m_84065FD1;
        
        [STUField(0x1E14CCA8)]
        public ulong m_1E14CCA8;
        
        [STUField(0x4EA686DB)]
        public ulong m_4EA686DB;
        
        [STUField(0x27CF71D5)]
        public ulong m_27CF71D5;
        
        [STUField(0x66747E7D)]
        public ulong m_66747E7D;
        
        [STUField(0x89831602)]
        public ulong m_89831602;
        
        [STUField(0xBAA74493, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_condition;
        
        [STUField(0x9C7BD8B8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9C7BD8B8;
        
        [STUField(0xB486603E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B486603E;
        
        [STUField(0x8B2A4DF3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8B2A4DF3;
        
        [STUField(0xC1903771, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C1903771;
        
        [STUField(0xF61726FE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F61726FE;
        
        [STUField(0xB40362FC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B40362FC;
    }
}
