// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0xA7AAA35A, "STUConfigVarGetSkinOverride")]
    public class STUConfigVarGetSkinOverride : STUConfigVarResource
    {
        [STUField(0xB91CFF97, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_base;
        
        [STUField(0xA83C2C26, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;
    }
}
