// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xACCDE63F, "STUCelebration")]
    public class STUCelebration : STUInstance {
        [STUFieldAttribute(0x71D9486D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUUnlocks m_71D9486D;

        [STUFieldAttribute(0xED999C8B)]
        public teStructuredDataAssetRef<STU_9CADF2EC> m_ED999C8B;

        [STUFieldAttribute(0xF81F4386, "m_startTime")]
        public teStructuredDataDateAndTime m_startTime;

        [STUFieldAttribute(0xFBEBAD6F, "m_endTime")]
        public teStructuredDataDateAndTime m_endTime;

        [STUFieldAttribute(0xEDE36CB7)]
        public ulong m_EDE36CB7;
    }
}
