// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0xA67443FE, "STUConfigVarCelebration")]
    public class STUConfigVarCelebration : STU_E4324757
    {
        [STUField(0xE02BEE24)]
        public teStructuredDataAssetRef<STUCelebration> m_celebration;
    }
}
