// Generated by TankLibHelper
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x2F33B1B7, 48)]
    public class STUCriteria : STUInstance
    {
        [STUField(0x3EE5B751, 8)] // size: 16
        public teStructuredDataAssetRef<ulong> m_3EE5B751;

        [STUField(0xA20DCD80, 24)] // size: 8
        public ulong m_A20DCD80;

        [STUField(0x9063EABE, 32)] // size: 4
        public int m_9063EABE;

        [STUField(0x0619C597, 36)] // size: 4
        public STUCriteriaType m_type;

        [STUField(0x967A138B, 40)] // size: 4
        public Enum_AB6CE3D1 m_967A138B;

        [STUField(0x07D0F7AA, 44)] // size: 4
        public int m_07D0F7AA;
    }
}
