// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA7E04FB2, "STUConfigVarExpression")]
    public class STUConfigVarExpression : STUConfigVar {
        [STUFieldAttribute(0x7C7B1C8D, "m_expression", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUConfigVarExpressionData m_expression;

        [STUFieldAttribute(0x57CBDD1E, "m_configVars", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar[] m_configVars;
    }
}
