// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x5054972D, "STUContactSetComponent")]
    public class STUContactSetComponent : STUEntityComponent
    {
        [STUField(0x0A84537A)]
        public teStructuredDataAssetRef<STUContactSet> m_contactSet;
    }
}
