// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0xF264A657, "STUConfigVarGamePadVibration")]
    public class STUConfigVarGamePadVibration : STU_E4324757
    {
        [STUField(0x479BD164)]
        public teStructuredDataAssetRef<STUGamePadVibration> m_vibration;
    }
}
