// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0xDA2D62F7, 32)]
    public class STUDynamicTreeDef : STUInstance
    {
        [STUField(0xEF601C02, 0)] // size: 16
        public byte[] m_aNodes;
        
        [STUField(0xF91B8EDD, 16)] // size: 4
        public int m_nodeCount;
        
        [STUField(0x131257CD, 20)] // size: 4
        public int m_root;
        
        [STUField(0x6CDE6226, 24)] // size: 4
        public int m_proxyCount;
    }
}
