// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDA2D62F7, "STUDynamicTreeDef")]
    public class STUDynamicTreeDef : STUInstance {
        [STUFieldAttribute(0xEF601C02, "m_aNodes")]
        public byte[] m_aNodes;

        [STUFieldAttribute(0xF91B8EDD, "m_nodeCount")]
        public int m_nodeCount;

        [STUFieldAttribute(0x131257CD, "m_root")]
        public int m_root;

        [STUFieldAttribute(0x6CDE6226, "m_proxyCount")]
        public int m_proxyCount;
    }
}
