// Generated by TankLibHelper
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0xB0D18D50, "STUECGravityAreaInstanceData")]
    public class STUECGravityAreaInstanceData : STUComponentInstanceData
    {
        [STUField(0x50F3348D)]
        public teVec3A m_50F3348D;
        
        [STUField(0x2746D7E4)]
        public teUUID m_2746D7E4;
        
        [STUField(0xDB660199)]
        public float m_DB660199 = 1f;
    }
}
