// Generated by TankLibHelper
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x6E63F8E1, "STUGraphLink")]
    public class STUGraphLink : STUInstance
    {
        [STUField(0xE3B4FA5C)]
        public teUUID m_uniqueID;
        
        [STUField(0x498B0009, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUGraphPlug m_outputPlug;
        
        [STUField(0xEA1269DF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUGraphPlug m_inputPlug;
    }
}
