// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x3FA4FF52, "STUGenericSettings_GamePad")]
    public class STUGenericSettings_GamePad : STUGenericSettings_Base
    {
        [STUField(0x33522782, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUGamePadMoveRegion[] m_regions;
        
        [STUField(0xEB44B6BE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUAnimCurve m_EB44B6BE;
        
        [STUField(0x5B875268, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUAnimCurve m_5B875268;
        
        [STUField(0x4F2CB32E)]
        public float m_4F2CB32E;
        
        [STUField(0x43FFCCCA)]
        public float m_43FFCCCA;
        
        [STUField(0xB5AA16FB)]
        public float m_B5AA16FB = 0.75f;
        
        [STUField(0x4E89FF0D)]
        public float m_4E89FF0D = 1.25f;
        
        [STUField(0xB8F4A86C)]
        public float m_B8F4A86C;
        
        [STUField(0x3489BF62)]
        public float m_3489BF62;
        
        [STUField(0xBB6F2ECC)]
        public float m_BB6F2ECC;
    }
}
