// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x43F40C0F, "STUGameRuleset")]
    public class STUGameRuleset : STUInstance {
        [STUFieldAttribute(0xEB4F2408, "m_gamemode", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUGameRulesetGameMode m_gamemode;

        [STUFieldAttribute(0x2690B60B)]
        public teString m_2690B60B;

        [STUFieldAttribute(0x26E97DBB)]
        public teStructuredDataAssetRef<ulong>[] m_26E97DBB;
    }
}
