// Generated by TankLibHelper
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x8FAF5745, "STUGraphItem")]
    public class STUGraphItem : STUInstance
    {
        [STUField(0x5DB91CE2)]
        public teString m_displayName;
        
        [STUField(0x6EAB6810)]
        public teString m_comment;
        
        [STUField(0xA10A5EAF)]
        public teVec2 m_pos;
        
        [STUField(0xE3B4FA5C)]
        public uint m_uniqueID;
    }
}
