// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0xA658CA1C, "STUHealthComponent")]
    public class STUHealthComponent : STUMirroredEntityComponent
    {
        [STUField(0x73AEA60D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_9EA55F3D[] m_73AEA60D;
        
        [STUField(0x28994152)]
        public teStructuredDataAssetRef<ulong> m_deathEffect;
        
        [STUField(0x63FBB2D3)]
        public teStructuredDataAssetRef<ulong> m_63FBB2D3;
        
        [STUField(0x0AEA1B48)]
        public teStructuredDataAssetRef<ulong> m_0AEA1B48;
        
        [STUField(0x9AF692CD)]
        public teStructuredDataAssetRef<ulong> m_9AF692CD;
        
        [STUField(0xE64867CE)]
        public int m_E64867CE = -1;
        
        [STUField(0x5AF3C1F6)]
        public float m_5AF3C1F6 = 7.5f;
        
        [STUField(0x5A007127)]
        public byte m_5A007127;
        
        [STUField(0xCDB100D1)]
        public byte m_CDB100D1 = 0x1;
        
        [STUField(0xF6CE4EAC)]
        public byte m_F6CE4EAC;
        
        [STUField(0xA80BAB3F)]
        public byte m_A80BAB3F = 0x1;
    }
}
