// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBC91AC98, "STULocalPersistedVoiceChatSettings")]
    public class STULocalPersistedVoiceChatSettings : STUInstance {
        [STUFieldAttribute(0xFD597304)]
        public byte m_FD597304;

        [STUFieldAttribute(0x59F175A3)]
        public byte m_59F175A3;

        [STUFieldAttribute(0x0776F30B)]
        public byte m_0776F30B;

        [STUFieldAttribute(0x15556D84)]
        public byte m_15556D84;

        [STUFieldAttribute(0x6EEF7774)]
        public byte m_6EEF7774;
    }
}
