// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0xA4EA3ED5, 24)]
    public class STULocalPersistedHeroSetting : STUInstance
    {
        [STUField(0x37AB13D3, 0)] // size: 8
        public ulong m_hero;
        
        [STUField(0xB2C0B929, 8)] // size: 8
        public ulong m_settingId;
        
        [STUField(0x07DD813E, 16)] // size: 8
        public ulong m_value;
    }
}
