// Generated by TankLibHelper
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0xEA8F8295, "STULootBoxRarityRules")]
    public class STULootBoxRarityRules : STUInstance
    {
        [STUField(0xBB99FCD3)]
        public STUUnlockRarity m_rarity;
        
        [STUField(0xA07D6F99)]
        public uint m_A07D6F99;
        
        [STUField(0xCBE06580)]
        public uint m_CBE06580;
    }
}
