// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xCFFB28E5, "STUMapFontKerningPair")]
    public class STUMapFontKerningPair : STUInstance {
        [STUFieldAttribute(0xD18773B2)]
        public uint m_D18773B2;

        [STUFieldAttribute(0xBB73A241)]
        public uint m_BB73A241;

        [STUFieldAttribute(0x96987C24)]
        public short m_96987C24;
    }
}
