// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0xB1FDD8AF, "STUMapFontGlyph")]
    public class STUMapFontGlyph : STUInstance
    {
        [STUField(0x6FF59B86)]
        public short m_6FF59B86;
        
        [STUField(0x25517A47)]
        public short m_25517A47;
        
        [STUField(0x5DC5168B)]
        public short m_width;
        
        [STUField(0xA16426C6)]
        public short m_height;
        
        [STUField(0x4FAFF680)]
        public short m_4FAFF680;
        
        [STUField(0xFE767CBF)]
        public short m_FE767CBF;
        
        [STUField(0xC1775158)]
        public short m_C1775158;
    }
}
