// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3A9B5E90, "STUMap")]
    public class STUMap : STUShippable {
        [STUFieldAttribute(0xC4A1DCA0, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_73AAFBE9 m_C4A1DCA0;

        [STUFieldAttribute(0xDEA3E7DA, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_60D2D598 m_DEA3E7DA;

        [STUFieldAttribute(0x06B5A4F1)]
        public teStructuredDataAssetRef<STU_C208081C> m_06B5A4F1;

        [STUFieldAttribute(0x9297ADB4, "m_look")]
        public teStructuredDataAssetRef<STU_687B11E7> m_look;

        [STUFieldAttribute(0xD7A516EC)]
        public teString m_D7A516EC;

        [STUFieldAttribute(0xCA7E6EDC, "m_description")]
        public teString m_description;

        [STUFieldAttribute(0x5DB91CE2, "m_displayName")]
        public teStructuredDataAssetRef<ulong> m_displayName;

        [STUFieldAttribute(0xC8EBCDFA, "m_aliases")]
        public teString[] m_aliases;

        [STUFieldAttribute(0x5AFE2F61)]
        public teStructuredDataAssetRef<ulong> m_5AFE2F61;

        [STUFieldAttribute(0x8EBADA44)]
        public teStructuredDataAssetRef<ulong> m_8EBADA44;

        [STUFieldAttribute(0xACB95597)]
        public teStructuredDataAssetRef<ulong> m_ACB95597;

        [STUFieldAttribute(0x389CB894)]
        public teStructuredDataAssetRef<ulong> m_389CB894;

        [STUFieldAttribute(0xEBE72514)]
        public teStructuredDataAssetRef<STUTexture> m_EBE72514;

        [STUFieldAttribute(0xD58D0365)]
        public teStructuredDataAssetRef<STUTexture> m_D58D0365;

        [STUFieldAttribute(0x9386E669)]
        public teStructuredDataAssetRef<STUTexture> m_9386E669;

        [STUFieldAttribute(0xEBCFAD22)]
        public teStructuredDataAssetRef<ulong> m_EBCFAD22;

        [STUFieldAttribute(0x5FF3ACFB, "m_celebrationOverrides", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUMapCelebrationOverride[] m_celebrationOverrides;

        [STUFieldAttribute(0x1C706502)]
        public teStructuredDataAssetRef<ulong> m_1C706502;

        [STUFieldAttribute(0x8F0478F9)]
        public teStructuredDataAssetRef<STUTexture> m_8F0478F9;

        [STUFieldAttribute(0x32102087)]
        public teStructuredDataAssetRef<STUTexture> m_32102087;

        [STUFieldAttribute(0xA0AE2E3E, "m_musicTease")]
        public teStructuredDataAssetRef<STUEffect> m_musicTease;

        [STUFieldAttribute(0x956158FF, "m_announcerWelcome")]
        public teStructuredDataAssetRef<STUEffect> m_announcerWelcome;

        [STUFieldAttribute(0x7F5B54B2)]
        public teStructuredDataAssetRef<STUVoiceSet> m_7F5B54B2;

        [STUFieldAttribute(0x719AA043, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_01AA07B0[] m_719AA043;

        [STUFieldAttribute(0x4FAD0FE9)]
        public teStructuredDataAssetRef<STU_387B4158> m_4FAD0FE9;

        [STUFieldAttribute(0x0DE1BA16, "m_layers")]
        public teStructuredDataAssetRef<STUMapLayer>[] m_layers;

        [STUFieldAttribute(0x0BF8AB9F)]
        public teStructuredDataAssetRef<STUEntityDefinition> m_0BF8AB9F;

        [STUFieldAttribute(0xD608E9F3)]
        public teStructuredDataAssetRef<STUGameMode>[] m_D608E9F3;

        [STUFieldAttribute(0x6B04495C)]
        public teStructuredDataAssetRef<STUTexture> m_6B04495C;

        [STUFieldAttribute(0x837D2E43)]
        public teStructuredDataAssetRef<STUTexture> m_837D2E43;

        [STUFieldAttribute(0xF0535DCF, "m_reflectionData", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_63ABE55E[] m_reflectionData;

        [STUFieldAttribute(0x38F33424, "m_baseMap")]
        public teStructuredDataAssetRef<STUMap> m_baseMap;

        [STUFieldAttribute(0xF542263E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_7D6D8405[] m_F542263E;

        [STUFieldAttribute(0x62354864)]
        public ulong m_62354864;

        [STUFieldAttribute(0x1DD3A0CD, "m_mapType")]
        public Enum_A0F51DCC m_mapType;

        [STUFieldAttribute(0x44D13CC2)]
        public int m_44D13CC2;

        [STUFieldAttribute(0xC0E32840)]
        public float m_C0E32840;

        [STUFieldAttribute(0xA125818B)]
        public Enum_668FA6B6 m_A125818B;

        [STUFieldAttribute(0xA8BF9196)]
        public byte m_A8BF9196;

        [STUFieldAttribute(0x5FB9732D)]
        public byte m_5FB9732D;

        [STUFieldAttribute(0x61550F4E)]
        public byte m_61550F4E;

        [STUFieldAttribute(0xC11DA2F7)]
        public byte m_C11DA2F7;

        [STUFieldAttribute(0x7BF9245C)]
        public byte m_7BF9245C;

        [STUFieldAttribute(0x13D8A0DD)]
        public byte m_13D8A0DD;
    }
}
