// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBE9DDFDF, "STUModelHardpoint")]
    public class STUModelHardpoint : STU_F0E34581 {
    }
}
