// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x02DEEEA0, "STUModelComponentInstanceData")]
    public class STUModelComponentInstanceData : STUComponentInstanceData {
        [STUFieldAttribute(0x9297ADB4, "m_look")]
        public teStructuredDataAssetRef<ulong> m_look;

        [STUFieldAttribute(0x592F316A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_8D38C163[] m_592F316A;

        [STUFieldAttribute(0x7A429A56)]
        public teVec3 m_7A429A56;

        [STUFieldAttribute(0x59D2DC64)]
        public teVec3 m_59D2DC64;

        [STUFieldAttribute(0xCC9B90A5)]
        public float m_CC9B90A5;

        [STUFieldAttribute(0xB5BCCD69)]
        public float m_B5BCCD69;

        [STUFieldAttribute(0xD197FFE0)]
        public float m_D197FFE0;

        [STUFieldAttribute(0xC9A391CD)]
        public float m_C9A391CD;

        [STUFieldAttribute(0x86C122AB)]
        public byte m_86C122AB;

        [STUFieldAttribute(0xEED141D9)]
        public byte m_EED141D9;
    }
}
