// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0xE1111C8D, "STUMapFont")]
    public class STUMapFont : STUInstance
    {
        [STUField(0xA1AD5DD2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUMapFontHeader m_header;
        
        [STUField(0x25274294, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUMapFontData m_data;
    }
}
