// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x773DC32C, "STUMirroredEntityComponent")]
    public class STUMirroredEntityComponent : STUEntityComponent
    {
    }
}
