// Generated by TankLibHelper
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x191835F9, 320)]
    public class STUModelComponent : STUEntityComponent
    {
        [STUField(0xD81FE8DF, 8, ReaderType = typeof(InlineInstanceFieldReader))] // size: 24
        public STU_AA155F7F m_D81FE8DF;

        [STUField(0x523339C1, 32)] // size: 16
        public teStructuredDataAssetRef<STUAnimBlendTreeSet> m_animBlendTreeSet;

        [STUField(0x36F54327, 48)] // size: 16
        public teStructuredDataAssetRef<STUAnimBlendTree> m_36F54327;

        [STUField(0xFD090EAD, 64)] // size: 16
        public teStructuredDataAssetRef<STUAnimation> m_FD090EAD;

        [STUField(0x9C3F817E, 80)] // size: 16
        public teStructuredDataAssetRef<STUSkeleton> m_9C3F817E;

        [STUField(0x2D124BE2, 96)] // size: 16
        public teStructuredDataAssetRef<STUModel> m_model;

        [STUField(0xF5ADE169, 112)] // size: 16
        public teStructuredDataAssetRef<STU_5CA5A90D> m_F5ADE169;

        [STUField(0xEE77FFF9, 128)] // size: 16
        public teStructuredDataAssetRef<STU_4189AEA5> m_EE77FFF9;

        [STUField(0x9297ADB4, 144)] // size: 16
        public teStructuredDataAssetRef<STUModelLook> m_look;

        [STUField(0xA6041C8B, 160, ReaderType = typeof(InlineInstanceFieldReader))] // size: 16
        public STUCollisionConfig m_collisionConfig;

        [STUField(0x33DA887B, 176)] // size: 16
        public teStructuredDataAssetRef<STU_CBD8CDF3>[] m_33DA887B;

        [STUField(0x9955A0BF, 192)] // size: 16
        public teStructuredDataAssetRef<STU_CBD8CDF3>[] m_9955A0BF;

        [STUField(0x14256239, 208, ReaderType = typeof(InlineInstanceFieldReader))] // size: 36
        public STURagdollConfig m_ragdollConfig;

        [STUField(0x93178192, 244, ReaderType = typeof(InlineInstanceFieldReader))] // size: 12
        public STURigidBodyConfig m_rigidBodyConfig;

        [STUField(0xDEB1159A, 256, ReaderType = typeof(InlineInstanceFieldReader))] // size: 12
        public STUBreakableConfig m_breakableConfig;

        [STUField(0xA7A9DA23, 268, ReaderType = typeof(InlineInstanceFieldReader))] // size: 8
        public STUClothConfig m_clothConfig;

        [STUField(0xBE0D6D29, 276)] // size: 4
        public uint m_BE0D6D29 = 0x1;

        [STUField(0x94546E3D, 280)] // size: 4
        public float m_94546E3D;

        [STUField(0x52202BFF, 284)] // size: 4
        public float m_52202BFF;

        [STUField(0x0DBF43D5, 288)] // size: 4
        public float m_0DBF43D5;

        [STUField(0x524B0242, 292)] // size: 4
        public Enum_C185E6E8 m_524B0242 = (Enum_C185E6E8)0x1;

        [STUField(0x65777ADA, 296)] // size: 1
        public byte m_65777ADA;

        [STUField(0xFFAD7FF2, 297)] // size: 1
        public byte m_FFAD7FF2;

        [STUField(0x4881B362, 298)] // size: 1
        public byte m_4881B362;

        [STUField(0x60BFA90D, 299)] // size: 1
        public byte m_60BFA90D;

        [STUField(0x6312F23B, 300)] // size: 1
        public byte m_6312F23B;

        [STUField(0x6DC5AE9B, 301)] // size: 1
        public byte m_6DC5AE9B;

        [STUField(0x2056559D, 302)] // size: 1
        public byte m_2056559D;

        [STUField(0xADC54E57, 303)] // size: 1
        public byte m_ADC54E57;

        [STUField(0xB287A07F, 304)] // size: 1
        public byte m_B287A07F;

        [STUField(0x4A82B056, 305)] // size: 1
        public byte m_4A82B056;

        [STUField(0x83B99596, 306)] // size: 1
        public byte m_83B99596;

        [STUField(0x24474FBE, 307)] // size: 1
        public byte m_24474FBE = 0x1;

        [STUField(0x4961ACEC, 308)] // size: 1
        public byte m_4961ACEC = 0x1;

        [STUField(0xCFC25B50, 309)] // size: 1
        public byte m_CFC25B50 = 0x0;
    }
}
