// Generated by TankLibHelper
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x3FBEDE0E, 8)]
    public class STUProfileStatCategory : STUInstance
    {
        [STUField(0x2C54AEAF, 0)] // size: 4
        public Enum_6CBB673B m_category;
        
        [STUField(0x18983896, 4)] // size: 4
        public int m_18983896;
    }
}
