// Generated by TankLibHelper
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0xA0F2FE14, "STURankedTierDefinition")]
    public class STURankedTierDefinition : STUInstance
    {
        [STUField(0x4BF7CD58)]
        public uint m_4BF7CD58;
        
        [STUField(0xD2F14FFA)]
        public uint m_D2F14FFA;
        
        [STUField(0x85CA53C8)]
        public Enum_4BE16CA5 m_85CA53C8;
    }
}
