// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA1D1B633, "STUStatescriptWeaponVolleyLaunch")]
    public class STUStatescriptWeaponVolleyLaunch : STUInstance {
        [STUFieldAttribute(0xF4104199, "m_muzzles", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUStatescriptWeaponVolleyMuzzle[] m_muzzles;

        [STUFieldAttribute(0x22CE7F30, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_22CE7F30;

        [STUFieldAttribute(0xE2FD6F04, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E2FD6F04;

        [STUFieldAttribute(0x1C78B91C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1C78B91C;

        [STUFieldAttribute(0x6425FFB9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6425FFB9;
    }
}
