// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x52B46D44, "STUStatescriptActionCriteria")]
    public class STUStatescriptActionCriteria : STUStatescriptAction
    {
        [STUField(0x4D2DB658, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_identifier;
        
        [STUField(0xE3798C00, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_targets;
        
        [STUField(0x8C8C5285, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8C8C5285;
        
        [STUField(0x297E0B63, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_297E0B63;
        
        [STUField(0xA732F9A2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A732F9A2;
    }
}
