// Generated by TankLibHelper
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x6226036A, 336)]
    public class STUStatescriptStateCombatModFilter : STU_FC063208
    {
        [STUField(0xF60AA143, 192)] // size: 16
        public teStructuredDataAssetRef<STUIdentifier>[] m_F60AA143;

        [STUField(0x5CFFCBAE, 208)] // size: 16
        public teStructuredDataAssetRef<STUIdentifier>[] m_5CFFCBAE;

        [STUField(0x029060AC, 224)] // size: 16
        public teStructuredDataAssetRef<STUIdentifier>[] m_029060AC;

        [STUField(0x6AA5D70F, 240, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVarFilter m_6AA5D70F;

        [STUField(0x5E6F1B8B, 248, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVarFilter m_5E6F1B8B;

        [STUField(0x73A57332, 256, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_73A57332;

        [STUField(0x00768EF7, 264, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_00768EF7;

        [STUField(0x50530EAB, 272, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_50530EAB;

        [STUField(0x941C56C2, 280, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_941C56C2;

        [STUField(0x893AABFC, 288, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_893AABFC;

        [STUField(0xE9517777, 296, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_E9517777;

        [STUField(0xF7872851, 304, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_F7872851;

        [STUField(0x72EDDF72, 312)] // size: 4
        public Enum_98B96E4A m_72EDDF72;

        [STUField(0x7724EC51, 316)] // size: 4
        public uint m_7724EC51 = 0x1;

        [STUField(0x5BF820E4, 320)] // size: 4
        public uint m_5BF820E4 = 0x3;

        [STUField(0xDE43A93C, 324)] // size: 4
        public uint m_DE43A93C;

        [STUField(0x41B10FF2, 328)] // size: 4
        public Enum_32773B82 m_41B10FF2;
    }
}
