// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC2DC60F6, "STUStatescriptBase")]
    public class STUStatescriptBase : STUGraphNode {
        [STUFieldAttribute(0xBF5B22B7, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUStatescriptRemoteSyncVar[] m_BF5B22B7;

        [STUFieldAttribute(0x8BF03679, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUStatescriptRemoteSyncVar[] m_8BF03679;

        [STUFieldAttribute(0xA2287776)]
        public Enum_46B5ADCA m_A2287776;

        [STUFieldAttribute(0x871A8203)]
        public int m_871A8203;

        [STUFieldAttribute(0x602E1F8F)]
        public int m_602E1F8F;

        [STUFieldAttribute(0xAED90719)]
        public Enum_CEBBB217 m_AED90719;

        [STUFieldAttribute(0x2BBEEAB8)]
        public byte m_2BBEEAB8;

        [STUFieldAttribute(0xADEB6E05)]
        public byte m_ADEB6E05;

        [STUFieldAttribute(0xE1B0C07F, "m_clientOnly")]
        public byte m_clientOnly;

        [STUFieldAttribute(0x9A861B79, "m_serverOnly")]
        public byte m_serverOnly;
    }
}
