// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD96D3396, "STUSoundParameter")]
    public class STUSoundParameter : STUInstance {
        [STUFieldAttribute(0xC27830B3)]
        public teString m_C27830B3;

        [STUFieldAttribute(0xB04205C5)]
        public uint m_B04205C5;
    }
}
