// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x6540C278, "STUStatescriptStateWait")]
    public class STUStatescriptStateWait : STUStatescriptState
    {
        [STUField(0xEF6581D3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_timeout;
        
        [STUField(0x5DA62D02, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onAbortPlug;
        
        [STUField(0xA0B58111, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;
        
        [STUField(0x0DBAFD7F)]
        public byte m_0DBAFD7F;
        
        [STUField(0xBF1A93B0)]
        public byte m_BF1A93B0;
    }
}
