// Generated by TankLibHelper
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x1C95493A, 24)]
    public class STUStatescriptRemoteSyncVar : STUInstance
    {
        [STUField(0x0D09D2D9, 0)] // size: 16
        public teStructuredDataAssetRef<STUIdentifier> m_0D09D2D9;
        
        [STUField(0x56341592, 16)] // size: 4
        public Enum_143375DF m_56341592;
    }
}
