// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0xFC999513, "STUStatescriptStateGroup")]
    public class STUStatescriptStateGroup : STUInstance
    {
    }
}
