// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x826613B7, "STUStatescriptStateModifyHealth")]
    public class STUStatescriptStateModifyHealth : STUStatescriptState {
        [STUFieldAttribute(0x95F1FB0B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_95F1FB0B;

        [STUFieldAttribute(0x0FD4CCC6, "m_modifyHealth", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptModifyHealth m_modifyHealth;

        [STUFieldAttribute(0xA3A0BDD6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A3A0BDD6;

        [STUFieldAttribute(0xFA3ECC43, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FA3ECC43;

        [STUFieldAttribute(0xB12BFE8B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B12BFE8B;

        [STUFieldAttribute(0xC744A524, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C744A524;

        [STUFieldAttribute(0x79758CE9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_79758CE9;

        [STUFieldAttribute(0xFF9E82FA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FF9E82FA;

        [STUFieldAttribute(0x48BED081, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_48BED081;

        [STUFieldAttribute(0x7BE02F89, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7BE02F89;

        [STUFieldAttribute(0x5DA62D02, "m_onAbortPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onAbortPlug;

        [STUFieldAttribute(0xA0B58111, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;

        [STUFieldAttribute(0xDD792FF0)]
        public Enum_D4BAD8E7 m_DD792FF0;

        [STUFieldAttribute(0x7B2B3F5C)]
        public byte m_7B2B3F5C;

        [STUFieldAttribute(0x8B707686)]
        public byte m_8B707686;
    }
}
