// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5981B16B, "STUStatescriptSchema")]
    public class STUStatescriptSchema : STUInstance {
        [STUFieldAttribute(0x16B4863C, "m_entries", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptSchemaEntry[] m_entries;

        [STUFieldAttribute(0xF902AED1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_6B6014C2[] m_F902AED1;
    }
}
