// Generated by TankLibHelper
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0xCA60E86E, 552)]
    public class STUStatescriptStateAnim : STUStatescriptState
    {
        [STUField(0x1B797E7D, 232, ReaderType = typeof(InlineInstanceFieldReader))] // size: 16
        public STU_7307C5F4 m_1B797E7D;
        
        [STUField(0xB791993D, 248, ReaderType = typeof(InlineInstanceFieldReader))] // size: 16
        public STU_7307C5F4 m_B791993D;
        
        [STUField(0xC2F82271, 264, ReaderType = typeof(InlineInstanceFieldReader))] // size: 16
        public STU_B6D44250[] m_C2F82271;
        
        [STUField(0x38643E8F, 280, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 16
        public STU_94F8BEB5[] m_38643E8F;
        
        [STUField(0xB141AAE4, 296, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_entityID;
        
        [STUField(0x11E0A658, 304, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_11E0A658;
        
        [STUField(0x22326315, 312, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_22326315;
        
        [STUField(0x37EE887D, 320, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_37EE887D;
        
        [STUField(0xE0584DD8, 328, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_speedScalar;
        
        [STUField(0x86701C3E, 336, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_86701C3E;
        
        [STUField(0x2DEAE6A9, 344, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_2DEAE6A9;
        
        [STUField(0x7CCEC4F0, 352, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STU_076E0DBA m_7CCEC4F0;
        
        [STUField(0xF81F4386, 360, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_startTime;
        
        [STUField(0xFBEBAD6F, 368, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_endTime;
        
        [STUField(0x2B98273A, 376, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STU_43994986 m_2B98273A;
        
        [STUField(0x3D3C13D0, 384, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_3D3C13D0;
        
        [STUField(0xBB16810A, 392, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_priority;
        
        [STUField(0x6ECCC859, 400, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_6ECCC859;
        
        [STUField(0x7CC54480, 408, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_7CC54480;
        
        [STUField(0xC827B320, 416, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_C827B320;
        
        [STUField(0x16F0B638, 424, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_16F0B638;
        
        [STUField(0x3A3A95AA, 432, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STU_076E0DBA m_3A3A95AA;
        
        [STUField(0xEBEFB4A7, 440, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STU_076E0DBA m_EBEFB4A7;
        
        [STUField(0xD44E0893, 448, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STU_076E0DBA m_D44E0893;
        
        [STUField(0x23C9E1D5, 456, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STU_076E0DBA m_23C9E1D5;
        
        [STUField(0xE84F7DD7, 464, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STU_076E0DBA m_E84F7DD7;
        
        [STUField(0xD91EFE74, 472, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STU_076E0DBA m_D91EFE74;
        
        [STUField(0xE563CD67, 480, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STU_076E0DBA m_E563CD67;
        
        [STUField(0x51801303, 488, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STU_076E0DBA m_51801303;
        
        [STUField(0x3A65CBD3, 496, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STU_076E0DBA m_3A65CBD3;
        
        [STUField(0x28A0D32B, 504, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUConfigVar m_28A0D32B;
        
        [STUField(0x89AABA94, 512, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STU_AC03CA3F m_89AABA94;
        
        [STUField(0xA0B58111, 520, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUStatescriptOutputPlug m_onFinishedPlug;
        
        [STUField(0xA3B86BB0, 528, ReaderType = typeof(EmbeddedInstanceFieldReader))] // size: 8
        public STUStatescriptOutputPlug m_A3B86BB0;
        
        [STUField(0xC4FAB48B, 536)] // size: 4
        public Enum_92D6330B m_C4FAB48B;
        
        [STUField(0xB2E34614, 540)] // size: 4
        public STUPlayAnimSlot m_B2E34614;
        
        [STUField(0x0637108B, 544)] // size: 1
        public byte m_0637108B;
        
        [STUField(0xCD097FFA, 545)] // size: 1
        public byte m_CD097FFA;
    }
}
