// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x6CF1089B, "STUStatescriptWeaponProjectileEntity")]
    public class STUStatescriptWeaponProjectileEntity : STUInstance {
        [STUFieldAttribute(0x915AF62D)]
        public teStructuredDataAssetRef<STUEntityDefinition>[] m_915AF62D;

        [STUFieldAttribute(0x7DD89F4F, "m_entityDef", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entityDef;

        [STUFieldAttribute(0xA9A62FD0)]
        public byte m_A9A62FD0;
    }
}
