// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x74F95AE2, "STUStatescriptDeflectProjectileBox")]
    public class STUStatescriptDeflectProjectileBox : STUInstance {
        [STUFieldAttribute(0xCBA118B2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_CBA118B2;

        [STUFieldAttribute(0xAEF67365, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_AEF67365;
    }
}
