// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0xD2EA359E, "STUStatescriptAbilityVarToSet")]
    public class STUStatescriptAbilityVarToSet : STUInstance
    {
        [STUField(0x592D15F7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076E0DBA m_out_Var;
        
        [STUField(0x07DD813E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_value;
    }
}
