// Generated by TankLibHelper
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x42270D59, "STUSkinTheme")]
    public class STUSkinTheme : STUSkinBase
    {
        [STUField(0xA5C9CA02)]
        public teString m_internalName;
        
        [STUField(0xECCC4A5D)]
        public teStructuredDataAssetRef<ulong> m_ECCC4A5D;
        
        [STUField(0x88F5CF3E)]
        public teStructuredDataAssetRef<STUHeroWeapon>[] m_heroWeapons;
        
        [STUField(0x71818BC5)]
        public teStructuredDataAssetRef<STUEffect>[] m_71818BC5;
        
        [STUField(0xB8DC6D46)]
        public teStructuredDataAssetRef<STUTeamColor> m_teamColor;
        
        [STUField(0x70D5F086, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_882807BA[] m_70D5F086;
        
        [STUField(0x02F889AE)]
        public teStructuredDataAssetRef<STUSkinTheme> m_02F889AE;
        
        [STUField(0xC3E03C7F)]
        public teColorRGBA m_color;
        
        [STUField(0xE9DA85BB)]
        public byte m_E9DA85BB;
    }
}
