// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x2201B8A5, "STUUXPopup")]
    public class STUUXPopup : STUUXElement {
    }
}
