// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x6F37773E, "STUUXElement")]
    public class STUUXElement : STUUXDependencyObject
    {
        [STUField(0xB1B74816, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUUXResourceDictionary m_resources;
    }
}
