// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x932A2F6B, "STUUXTankEffect")]
    public class STUUXTankEffect : STUUXAnimatable {
    }
}
