// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x6F37773E, "STUUXElement")]
    public class STUUXElement : STUUXDependencyObject {
        [STUFieldAttribute(0xB1B74816, "m_resources", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUUXResourceDictionary m_resources;
    }
}
