// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0xAE80FF68, "STUUXCollectionViewGroupRoot")]
    public class STUUXCollectionViewGroupRoot : STUUXCollectionViewGroup
    {
    }
}
