// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB456B24F, "STUUXDisplayText")]
    public class STUUXDisplayText : STU_A94C5E3B {
    }
}
