// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x84515D93, "STUUnlock_SprayPaint")]
    public class STUUnlock_SprayPaint : STU_3021DDED
    {
        [STUField(0x1B25AB90, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUUnlock_SprayPaintEffect m_1B25AB90;
        
        [STUField(0xE29A79B7)]
        public teStructuredDataAssetRef<ulong> m_E29A79B7;
    }
}
