// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x2E042A64, "STUUXHeaderedContentControl")]
    public class STUUXHeaderedContentControl : STUUXContentControl
    {
    }
}
