// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x440D818B, "STUUXComponent")]
    public class STUUXComponent : STUEntityComponent {
    }
}
