// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA5E1423A, "STUUXBehavior")]
    public class STUUXBehavior : STUUXAnimatable {
    }
}
