// Generated by TankLibHelper

// ReSharper disable All
namespace TankLib.STU.Types
{
    [STU(0x5C713BD4, "STUUnlock_SprayPaintEffect")]
    public class STUUnlock_SprayPaintEffect : STUInstance
    {
        [STUField(0x58D56DD4)]
        public teStructuredDataAssetRef<STUEffect> m_effect;
        
        [STUField(0x2B522C5B)]
        public teStructuredDataAssetRef<STUEffectLook> m_effectLook;
    }
}
