// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0xAE70AFC0)]
    public enum Enum_AE70AFC0 : uint {
        [STUFieldAttribute(0xE03353AB)]
        xE03353AB = 0x1,
        [STUFieldAttribute(0xA1998740)]
        xA1998740 = 0x2,
    }
}
