// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0x11961581)]
    public enum Enum_11961581 : uint {
        [STUFieldAttribute(0xD01D7682)]
        xD01D7682 = 0x1,
        [STUFieldAttribute(0x9D67C7D3)]
        x9D67C7D3 = 0x2,
        [STUFieldAttribute(0xC4334097)]
        xC4334097 = 0x4,
    }
}
