// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0x3E8E11FF)]
    public enum Enum_3E8E11FF : uint {
        [STUFieldAttribute(0x5F5702A0)]
        x5F5702A0 = 0x0,
        [STUFieldAttribute(0xDB6FC63B)]
        xDB6FC63B = 0x1,
        [STUFieldAttribute(0x1BB441A1)]
        x1BB441A1 = 0x2,
        [STUFieldAttribute(0x3E5EC384)]
        x3E5EC384 = 0x3,
        [STUFieldAttribute(0x635DD3FF)]
        x635DD3FF = 0x4,
        [STUFieldAttribute(0xA5E7B0FF)]
        xA5E7B0FF = 0x5,
        [STUFieldAttribute(0x469FD2FA)]
        x469FD2FA = 0x6,
        [STUFieldAttribute(0x7E3990B1)]
        x7E3990B1 = 0x7,
    }
}
