// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0xB748E23E)]
    public enum Enum_B748E23E : uint {
        [STUFieldAttribute(0xCC1EC89F)]
        xCC1EC89F = 0x0,
        [STUFieldAttribute(0xAD92EA0A)]
        xAD92EA0A = 0x1,
        [STUFieldAttribute(0x7DBEE0F3)]
        x7DBEE0F3 = 0x2,
        [STUFieldAttribute(0x2EA017D6)]
        x2EA017D6 = 0x3,
        [STUFieldAttribute(0x9D22B8CE)]
        x9D22B8CE = 0x4,
        [STUFieldAttribute(0x5D3D6394)]
        x5D3D6394 = 0x5,
        [STUFieldAttribute(0x581A6570)]
        x581A6570 = 0x6,
        [STUFieldAttribute(0x3956C2D3)]
        x3956C2D3 = 0x7,
        [STUFieldAttribute(0x72050CBB)]
        x72050CBB = 0x8,
        [STUFieldAttribute(0x85E438EC)]
        x85E438EC = 0x9,
        [STUFieldAttribute(0x4FA664DD)]
        x4FA664DD = 0xA,
        [STUFieldAttribute(0x3243946A)]
        x3243946A = 0xB,
        [STUFieldAttribute(0x248ACE74)]
        x248ACE74 = 0xC,
        [STUFieldAttribute(0x861B7D3B)]
        x861B7D3B = 0xD,
        [STUFieldAttribute(0xC37107D3)]
        xC37107D3 = 0xE,
        [STUFieldAttribute(0x40CE6362)]
        x40CE6362 = 0xF,
        [STUFieldAttribute(0x7F7D3533)]
        x7F7D3533 = 0x0,
    }
}
