// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0x2F83D604)]
    public enum Enum_2F83D604 : uint {
        [STUFieldAttribute(0xF0BF2A7B)]
        xF0BF2A7B = 0x0,
        [STUFieldAttribute(0x7A6CA400)]
        x7A6CA400 = 0x1,
        [STUFieldAttribute(0xF0C1DE85)]
        xF0C1DE85 = 0x2,
        [STUFieldAttribute(0x144210EC)]
        x144210EC = 0x3,
    }
}
