// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0x98D75356)]
    public enum Enum_98D75356 : uint {
        [STUFieldAttribute(0x79C315DC)]
        x79C315DC = 0x1,
    }
}
