// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0x1F3AB514)]
    public enum Enum_1F3AB514 : uint {
        [STUFieldAttribute(0x520A9489)]
        x520A9489 = 0x40,
        [STUFieldAttribute(0x666E803B)]
        x666E803B = 0x20,
        [STUFieldAttribute(0xEB69ADB3)]
        xEB69ADB3 = 0xA,
        [STUFieldAttribute(0x231BF37B)]
        x231BF37B = 0x2D,
        [STUFieldAttribute(0x654B59D4)]
        x654B59D4 = 0x14,
        [STUFieldAttribute(0xD312B014)]
        xD312B014 = 0x5A,
    }
}
