// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0x25C5DF4F)]
    public enum Enum_25C5DF4F : uint {
        [STUFieldAttribute(0xD8EC8434)]
        xD8EC8434 = 0x0,
        [STUFieldAttribute(0x8CD8AFA0)]
        x8CD8AFA0 = 0x1,
        [STUFieldAttribute(0x3181B169)]
        x3181B169 = 0x2,
        [STUFieldAttribute(0x2491BB47)]
        x2491BB47 = 0x3,
    }
}
