// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0x79A5F030)]
    public enum Enum_79A5F030 : uint {
        [STUFieldAttribute(0xAD1AE88F)]
        xAD1AE88F = 0x0,
        [STUFieldAttribute(0xE7FBCEA2)]
        xE7FBCEA2 = 0x1,
    }
}
