// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0x04335D3F)]
    public enum Enum_04335D3F : uint {
        [STUFieldAttribute(0x29A0B578)]
        x29A0B578 = 0x0,
        [STUFieldAttribute(0xEED08D30)]
        xEED08D30 = 0x1,
        [STUFieldAttribute(0x8033BFFB)]
        x8033BFFB = 0x2,
    }
}
