// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0x2758B676)]
    public enum Enum_2758B676 : uint {
        [STUFieldAttribute(0x99A95DEB)]
        x99A95DEB = 0x0,
        [STUFieldAttribute(0x5251F0A7)]
        x5251F0A7 = 0x1,
        [STUFieldAttribute(0xB108BA59)]
        xB108BA59 = 0x2,
        [STUFieldAttribute(0x036DE578)]
        x036DE578 = 0x3,
        [STUFieldAttribute(0x47FFF217)]
        x47FFF217 = 0x4,
        [STUFieldAttribute(0xAF2EE1DE)]
        xAF2EE1DE = 0x5,
        [STUFieldAttribute(0x246A8AA5)]
        x246A8AA5 = 0x6,
    }
}
