// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0x240B3234)]
    public enum Enum_240B3234 : uint {
        [STUFieldAttribute(0x8550E38C)]
        x8550E38C = 0x0,
        [STUFieldAttribute(0xEDE20505)]
        xEDE20505 = 0x1,
        [STUFieldAttribute(0x15913BE5)]
        x15913BE5 = 0x2,
        [STUFieldAttribute(0x689C686C)]
        x689C686C = 0x3,
        [STUFieldAttribute(0x4268279B)]
        x4268279B = 0x4,
        [STUFieldAttribute(0x122AC5EA)]
        x122AC5EA = 0x5,
    }
}
