// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0x5DAED5C6)]
    public enum Enum_5DAED5C6 : uint {
        [STUFieldAttribute(0x01E5E24D)]
        x01E5E24D = 0x1,
        [STUFieldAttribute(0x26EFEC1D)]
        x26EFEC1D = 0x2,
    }
}
