// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0xED4AE624)]
    public enum Enum_ED4AE624 : uint {
        [STUFieldAttribute(0x8F71720A)]
        x8F71720A = 0x0,
        [STUFieldAttribute(0x1C1E1844)]
        x1C1E1844 = 0x1,
        [STUFieldAttribute(0x27AB533D)]
        x27AB533D = 0x2,
        [STUFieldAttribute(0x14123B1D)]
        x14123B1D = 0x3,
    }
}
