// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0x3748C39B)]
    public enum Enum_3748C39B : uint {
        [STUFieldAttribute(0x07D614BB)]
        x07D614BB = 0x0,
        [STUFieldAttribute(0x926B7E9E)]
        x926B7E9E = 0x1,
        [STUFieldAttribute(0x1C68D3F3)]
        x1C68D3F3 = 0x2,
    }
}
