// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0x255164EF)]
    public enum Enum_255164EF : uint {
        [STUFieldAttribute(0x6A7F0D0B)]
        x6A7F0D0B = 0x0,
        [STUFieldAttribute(0xF3639124)]
        xF3639124 = 0x1,
        [STUFieldAttribute(0xE8969461)]
        xE8969461 = 0x2,
        [STUFieldAttribute(0x44E6E6C5)]
        x44E6E6C5 = 0x3,
    }
}
