// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0x668FA6B6)]
    public enum Enum_668FA6B6 : uint {
        [STUFieldAttribute(0x1A62C6F0)]
        Enabled = 0x0,
        [STUFieldAttribute(0xF4C0BC0F)]
        Disabled = 0x1,
    }
}
