// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0x78E63990)]
    public enum Enum_78E63990 : uint {
        [STUFieldAttribute(0xF0FF9C65)]
        xF0FF9C65 = 0x0,
        [STUFieldAttribute(0x8C145E04)]
        x8C145E04 = 0x1,
    }
}
