// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0xE95E2013, "STUStatType")]
    public enum STUStatType : uint {
    }
}
