// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types {
    [STU(0x34F6B4CF)]
    public class STUChatReplacementSingle : STUInstance {
        [STUField(0x123179A6)]
        public STUGUID Triggers;

        [STUField(0xC6A72790)]
        public STUChatReplacementGroup[] Groups;

        [STUField(0xA7DC8A2F)]
        public STUGUID[] GlobalReplacementStrings;

        [STUField(0x115DDDBF)]
        public STUGUID m_115DDDBF;  // STUCelebration

        [STUField(0xE9443298)]
        public STUGUID[] Heroes;  // STULib.Types.STUHero

        [STUField(0xB0199D5E)]
        public STUGUID[] HeroChatReplacementStrings;

        [STUField(0xEDE36CB7)]
        public ulong m_EDE36CB7;
    }
}
