// File auto generated by STUHashTool

using STULib.Types.Generic;

namespace STULib.Types {
    [STU(0xD05AEF31, "STUConfigVar")]
    public class STUConfigVar : Common.STUInstance {
        [STUField(0xEE729DCB)]
        public ulong m_EE729DCB;  // pre = 83E83924
    }
}
