// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types {
    [STU(0x74F359CA)]
    public class STULanguageMonths : STUInstance {
        [STUField(0x565ECF6B)]
        public string January;

        [STUField(0xC17BC33C)]
        public string February;

        [STUField(0x053AC3EF)]
        public string March;

        [STUField(0x0177243B)]
        public string April;

        [STUField(0x4D447320)]
        public string May;

        [STUField(0x0932ED44)]
        public string June;

        [STUField(0x3D9CF6A1)]
        public string July;

        [STUField(0x57523531)]
        public string August;

        [STUField(0x20A27023)]
        public string September;

        [STUField(0x68152D6F)]
        public string October;

        [STUField(0xFC8ED794)]
        public string November;

        [STUField(0xF5FE5F2C)]
        public string December;
    }
}
