// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types {
    [STU(0x875F19AE)]
    public class STUPose : STUInstance {
        [STUField(0xBEF008DE)]
        public STUPoseSub Sub1;

        [STUField(0x0189332F)]
        public STUPoseSub Sub2;

        [STUField(0xDE70F501)]
        public STUPoseSub Sub3;

        [STUField(0xE599EB7C)]
        public STUGUID Animation;

        [STUField(0x40AF7E2D)]
        public float UnknownFloat;
    }
}
