// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types {
    [STU(0x2F33B1B7)]
    public class STUSoundInfo : STUInstance {
        [STUField(0xA20DCD80)]
        public ulong m_A20DCD80;

        [STUField(0x0619C597, "m_type")]
        public Enums.STUEnum_1AA009C2 Type;

        [STUField(0x967A138B)]
        public Enums.STUEnum_AB6CE3D1 m_967A138B;

        [STUField(0x07D0F7AA)]
        public int m_07D0F7AA;
    }

    [STU(0xD815520F)]
    public class STUSoundHeroInfo : STUSoundInfo {
        [STUField(0x8C8C5285)]
        public STUGUID Hero;

        [STUField(0x57D96E27)]
        public byte Unknown;
    }

    [STU(0xC37857A5)]
    public class STUSoundInfoUnknown1 : STUSoundInfo {
        [STUField(0xED999C8B)]
        public STUGUID Virtual01C;
    }

    [STU(0xD0364821)]
    public class STUSoundInfoUnknown2 : STUSoundInfo {
        [STUField(0x4D2DB658)]
        public STUGUID Virtual01C;

        [STUField(0x57D96E27)]
        public byte UnknownByte;
    }

    [STU(0x7C69EA0F)]
    public class STUSoundInfoUnknown3 : STUSoundInfo {
        [STUField(0x4FF98D41, EmbeddedInstance = true)]
        public STU_C1A2DB26[] UnknownEmbedArray;

        [STUField(0xAF872E86)]
        public uint Unknown;
    }

    [STU(0xE9DB72FF)]
    public class STUSoundInfoUnknown4 : STUSoundInfo {
        [STUField(0x4E87690F)]
        public STUGUID UnknownMapData;  // why is map data here?

        [STUField(0xA2C1FA17)]
        public byte Unknown;
    }

    [STU(0xC7CA73B1)]
    public class STUSoundInfoUnknown5 : STUSoundInfo {
        [STUField(0xE02BEE24, "m_celebration")]
        public STUGUID Celebration;
    }

    // Found in 068
    [STU(0xC9AAE3AE)]
    public class STU_C9AAE3AE : STUSoundInfo {
        [STUField(0xBC4326FF )]
        public STUGUID m_BC4326FF;  // STU_C7BAA017

        [STUField(0xAF872E86)]
        public double m_AF872E86;

        [STUField(0x411ABFEA)]
        public ulong m_411ABFEA;

        [STUField(0x4889445F)]
        public uint m_4889445F;

        [STUField(0x5D32D524)]
        public STUEnum_2D0A59BA m_5D32D524;

        [STUField(0x5ED79353)]
        public STUEnum_10064D07 m_5ED79353;

        [STUField(0xAB103723)]
        public byte m_AB103723;
    }

    // Found in 068
    [STU(0x857C15FC)]
    public class STU_857C15FC : STUSoundInfo {
        [STUField(0xBC4326FF)]
        public STUGUID m_BC4326FF;  // STU_C7BAA017

        [STUField(0xAF872E86)]
        public double m_AF872E86;

        [STUField(0x7FE9F87A)]
        public ulong m_7FE9F87A;

        [STUField(0xEA58FA50)]
        public ulong m_EA58FA50;

        [STUField(0x411ABFEA)]
        public ulong m_411ABFEA;

        [STUField(0x5D32D524)]
        public STUEnum_2D0A59BA m_5D32D524;

        [STUField(0x5ED79353)]
        public STUEnum_10064D07 m_5ED79353;

        [STUField(0xAB103723)]
        public byte m_AB103723;
    }

    // Found in 068
    [STUEnum(0x2D0A59BA)]
    public enum STUEnum_2D0A59BA : uint {
    }

    // Found in 068
    [STUEnum(0x10064D07)]
    public enum STUEnum_10064D07 : uint {
    }
}

    // todo: A95E4B99
    // todo: BDD783B9
    // todo: D931E2CF
    // todo: C9F4617F
