// File auto generated by STUHashTool

namespace STULib.Types {
    [STU(0x614BC677, "STUUnlock_Currency")]  // old hash: 0BCAF9C9
    public class STUUnlock_Currency : STUUnlock {
        [STUField(0x4CE56BC0)]
        public int Amount;
    }
}

