// File auto generated by STUHashTool
using STULib.Types.Generic;

namespace STULib.Types {
    [STU(0x8E77E8A1)]
    public class STUUnlock_HighlightIntro : STUUnlock {
        public override string RealName => "HighlightIntro";

        [STUField(0x3F5B86A4, "m_animation")]
        public Common.STUGUID Animation;

        [STUField(0x0619C597, "m_type")]
        public uint Type;  // STUEnum_E5327514
    }
}
