// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types {
    [STU(0x00C21225, "STUVoiceLineInstance")]
    public class STUVoiceLineInstance : STUInstance {  // todo: these names are so bad
        [STUField(0xD0C28030)]
        public STUGUID m_D0C28030;

        [STUField(0x43C90056)]
        public STUGUID Subtitle;

        [STUField(0xAF226247, EmbeddedInstance = true)]
        public STUSoundConainer SoundContainer;

        [STUField(0xBC474019, EmbeddedInstance = true)]
        public STUSoundDataContainer SoundDataContainer;  // todo: these names are so bad

        [STUField(0x38BFB46C)]
        public ulong m_38BFB46C;
    }
}
