// File auto generated by STUHashTool

using STULib.Types.Generic;

namespace STULib.Types.Statescript.ConfigVar {
    [STU(0x31535F33)]
    public class STU_31535F33 : STUStatescriptDataStoreBase {
        [STUField(0xEE483487)]
        public Common.STUGUID m_EE483487;  // STU_A0CFB0F7
    }
}
