// File auto generated by STUHashTool

using STULib.Types.Generic;

namespace STULib.Types.Statescript.ConfigVar {
    [STU(0xCB43F2B1)]
    public class STUStatescriptDataStore015 : STUStatescriptDataStoreBase4 {
        [STUField(0x2C54AEAF, "m_category")]
        public Common.STUGUID Category;
    }
}
