// File auto generated by STUHashTool

using STULib.Types.Generic;

namespace STULib.Types.StatesciptComponents {
    [STU(0x44897C73)]
    public class STU_44897C73 : Common.STUInstance {
        [STUField(0xE1B0C07F)]
        public byte m_E1B0C07F;

        [STUField(0xEDA30E4A)]
        public byte m_EDA30E4A;

        [STUField(0xD7C2FC23)]
        public byte m_D7C2FC23;
    }
}
