// File auto generated by STUHashTool

using STULib.Types.Generic;

namespace STULib.Types.StatesciptComponents {
    [STU(0x9D28963F)]
    public class STUStatescriptSubreferenceComponent : STUStatescriptComponent {
        [STUField(0xA83C2C26)]
        public Common.STUGUID GUIDx003;  // STU_73BB2F3A

        [STUField(0x4B75D84E)]
        public float m_4B75D84E;

        [STUField(0xE29993A5)]
        public float m_E29993A5;

        [STUField(0x816B830F)]
        public float m_816B830F;
    }
}
